force-app/main/default/objects/PaymentCondition__c/PaymentCondition__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena toda as condições de pagamentos, na fase 01 esse objeto será alimentado através de cargas provenientes do SAP.</description>
    
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome da Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentCondition__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo externo que receberá a chave do pedido no SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Campo externo que receberá a chave do pedido no SAP.</inlineHelpText>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PaymentConditionDAO.cls
public with sharing class PaymentConditionDAO {
    
    public static List<PaymentCondition__c> getPaymentConditionByExternalId(List<String> externalIds, Set<String> paymentConditionUsedFields) {

        String query = new Q(PaymentCondition__c.SObjectType)
            .selectFields(paymentConditionUsedFields)
            .add(Q.condition('ExternalId__c').isIn(externalIds))
            .build();
            
        return Database.query(query);
    }

}