force-app/main/default/objects/Case/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CulturePlot__c.field-meta.xml
<CustomField>
    <fullName>CulturePlot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultura do Talhão</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <filterItems>
            <field>DelimitedLandCultures__c.DelimitedLand__c</field>
            <operation>equals</operation>
            <valueField>$Source.Plot__c</valueField>
        </filterItems>
        <filterItems>
            <field>DelimitedLandCultures__c.Crop__c</field>
            <operation>equals</operation>
            <valueField>$Source.Crop__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DelimitedLandCultures__c</referenceTo>
    <relationshipLabel>Ocorrências</relationshipLabel>
    <relationshipName>Ocorrencias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/DamagedArea__c.field-meta.xml
<CustomField>
    <fullName>DamagedArea__c</fullName>
    <label>Área afetada</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/IncidentTypePicklist__c.field-meta.xml
<CustomField>
    <fullName>IncidentTypePicklist__c</fullName>
    <label>Tipo de Ocorrência</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pragas</fullName>
            </value>
            <value>
                <fullName>Doencas</fullName>
                <label>Doenças</label>
            </value>
            <value>
                <fullName>Climaticas</fullName>
                <label>Climáticas</label>
            </value>
            <value>
                <fullName>Fertilizacao</fullName>
                <label>Fertilização</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Plot__c.field-meta.xml
<CustomField>
    <fullName>Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Talhão</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>DelimitedLand__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DelimitedLand__c</referenceTo>
    <relationshipLabel>Ocorrências</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Crop__c/Crop__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Safra provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Safra</label>
    <nameField>
        <label>Nome de Safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateCaseController.cls
@RestResource(urlMapping='/ForcaAgroApp/1_0/sendCaseData/*')
global with sharing class CreateCaseController {

    @HttpPost
    global static CaseResponse createCaseApp(String caseReq){
        CaseResponse caseResponse = null;
        Savepoint sp = null;

        CaseRequest caseRequest = (CaseRequest)JSON.deserialize(caseReq, CaseRequest.class);
        try{
            sp = Database.setSavepoint();

            Case caseObj = serializeCase(caseRequest);

            if (caseRequest.deleted) {
                List<Case> caseList = [SELECT Id FROM Case WHERE Id = :caseObj.Id];
                if (caseList.size() > 0) {
                    Database.DeleteResult delResult = Database.delete(caseObj, false);

                    if(delResult.isSuccess()){
                        return new CaseResponse(caseRequest, delResult.getId());
                    } else {
                        return new CaseResponse(delResult.getErrors()[0].getMessage(), caseRequest);
                    }
                } else {
                    return new CaseResponse(caseRequest, caseObj.Id);
                }
            } else {
                Boolean updateContext = (caseObj.Id != null);

                Database.SaveResult upsResult = updateContext ? Database.update(caseObj, false) : Database.insert(caseObj, false); 

                if(upsResult.isSuccess()){
                    return new CaseResponse(caseRequest, upsResult.getId());
                } else {
                    return new CaseResponse(upsResult.getErrors()[0].getMessage(), caseRequest);
                }
            }

        } catch (Exception e) {
            Database.rollback(sp);
            caseResponse = new CaseResponse(e, caseRequest);
        }

        return caseResponse;
    }

    global class CaseRequest extends CaseBaseRequest{}

    global abstract class CaseBaseRequest{
        public String  id                   {get;set;}
        public Integer appCode              {get;set;}
        public String  subject              {get;set;}
        public String  description          {get;set;}
        public String  incidentTypePicklist {get;set;}
        public String  origin               {get;set;}
        public String  accountId            {get;set;}
        public String  cropId               {get;set;}
        public String  plotId               {get;set;}
        public String  culturePlotId        {get;set;}
        public Decimal damagedArea          {get;set;}
        public Boolean deleted              {get;set;}
    }

    public static Case serializeCase(CaseRequest caseRequest) {
        Case caseObj = new Case(
            Id                      = caseRequest.id,
            Subject                 = caseRequest.subject,
            Description             = caseRequest.description,
            IncidentTypePicklist__c = caseRequest.incidentTypePicklist,
            Origin                  = caseRequest.origin,
            Status                  = 'New',
            AccountId               = caseRequest.accountId,
            Crop__c                 = caseRequest.cropId,
            Plot__c                 = caseRequest.plotId,
            CulturePlot__c          = caseRequest.culturePlotId,
            DamagedArea__c          = caseRequest.damagedArea
        );

        return caseObj;
    }

    global class CaseResponse extends CaseBaseRequest{
        public Boolean hasError {get;set;}
        public String errorMsg  {get;set;}

        public CaseResponse(Exception ex, CaseRequest caseRequest){
            this.hasError = true;
            this.errorMsg = ex.getMessage() + '\n Erro :' + ex.getStackTraceString();
            this.appCode  = caseRequest.appCode;
            this.deleted  = caseRequest.deleted;
        } 
        public CaseResponse(String error, CaseRequest caseRequest){
            this.hasError = true;
            this.errorMsg = error;
            this.appCode  = caseRequest.appCode;
            this.deleted  = caseRequest.deleted;
        }
        public CaseResponse(CaseRequest caseRequest, String caseId){
            this.hasError = false;
            this.errorMsg = null;
            this.id       = caseId;
            this.appCode  = caseRequest.appCode;
            this.deleted  = caseRequest.deleted;
        }  
    }
}