force-app/main/default/objects/Campaign/recordTypes/ForcaAgro.recordType-meta.xml
<RecordType>
    <fullName>ForcaAgro</fullName>
    <active>true</active>
    <label>ForcaAgro</label>
</RecordType>

force-app/main/default/objects/CampaignOrderItem__c/CampaignOrderItem__c.object-meta.xml
<CustomObject>
    <description>Objeto que irá armazenar os registros de vínculo entre as campanhas e os produtos do pedido.</description>
    
    <label>Campanha do Produto do Pedido</label>
    <nameField>
        <displayFormat>CAM-{000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campanhas dos Produtos do Pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignOrderItem__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campanha</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campanhas dos Produtos do Pedido</relationshipLabel>
    <relationshipName>Campanhas_dos_Produtos_do_Pedido</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CampaignOrderItem__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Desconto</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignOrderItem__c/fields/FixedUnitPriceCampaign__c.field-meta.xml
<CustomField>
    <fullName>FixedUnitPriceCampaign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado para marcar se o produto contem uma campanha de preço fixo.</description>
    <inlineHelpText>Campo utilizado para marcar se o produto contem uma campanha de preço fixo.</inlineHelpText>
    <label>Campanha de Preço Fixo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignOrderItem__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do pedido</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Campanhas dos Produtos do Pedido</relationshipLabel>
    <relationshipName>Campanhas_dos_Produtos_do_Pedido</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CampaignIndustryPercent__c.field-meta.xml
<CustomField>
    <fullName>CampaignIndustryPercent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Percentual de Campanha (Industria)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CampaignPercent__c.field-meta.xml
<CustomField>
    <fullName>CampaignPercent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Percentual de Campanha</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CampaigPercent__c.field-meta.xml
<CustomField>
    <fullName>CampaigPercent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Percentual de Campanha (ForcaAgro)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CampaignOrderItemTriggerHelper.cls
public without sharing class CampaignOrderItemTriggerHelper {
    private static Boolean runTrigger;

    static {
        runTrigger = true;
    }

    public static Boolean isTriggerEnabled(){
        return runTrigger;
    }

    public static Boolean enableTrigger(){
        return runTrigger = true;
    }

    public static Boolean disableTrigger(){
        return runTrigger = false;
    }
    public static void checkDiscountOrderItem(CampaignOrderItem__c[] context){ 
        Map<Id, OrderItem> ordItemMap = new Map<Id, OrderItem>();
        for(CampaignOrderItem__c campaigns : context){
            ordItemMap.put(campaigns.OrderItem__c, new OrderItem(Id = campaigns.OrderItem__c, CampaignPercent__c = 0, CampaignIndustryPercent__c = 0, CampaigPercent__c = 0));
        }

        for(CampaignOrderItem__c campaings : [SELECT id, FixedUnitPriceCampaign__c, OrderItem__c, Discount__c, Campaign__r.RecordType.DeveloperName FROM CampaignOrderItem__c WHERE OrderItem__c IN :ordItemMap.keySet()]){
            OrderItem ordItem = ordItemMap.get(campaings.OrderItem__c);
            ordItem.FixedUnitPriceCampaign__c = campaings.FixedUnitPriceCampaign__c;
            if(campaings.Campaign__r.RecordType.DeveloperName != 'ForcaAgro')
                ordItem.CampaignIndustryPercent__c += campaings.Discount__c;
            else
                ordItem.CampaigPercent__c += campaings.Discount__c;
                
            ordItem.CampaignPercent__c += campaings.Discount__c;
            ordItemMap.put(campaings.OrderItem__c, ordItem);
        }

        if(!ordItemMap.isEmpty()){
            update ordItemMap.values();
        }
    }
}