force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as respostas dos usuários as perguntas feitas durante a visita.</description>
    
    <label>Resposta</label>
    <nameField>
        <displayFormat>RES-{00000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Respostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Respostas</relationshipLabel>
    <relationshipName>Respostas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Campo que armazena a resposta de livre preenchimento do usuário.</description>
    <inlineHelpText>Campo que armazena a resposta de livre preenchimento do usuário.</inlineHelpText>
    <label>Resposta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/AnswerBoolean__c.field-meta.xml
<CustomField>
    <fullName>AnswerBoolean__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Resposta Caixa de Seleção</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/AnswerDate__c.field-meta.xml
<CustomField>
    <fullName>AnswerDate__c</fullName>
    <label>Resposta Data</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/EventRelated__c.field-meta.xml
<CustomField>
    <fullName>EventRelated__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A resposta se relaciona ao Evento relacionado, que por sua vez se relaciona ao Evento (Visitas e atividades)</description>
    <label>Evento Relacionado</label>
    <referenceTo>EventRelated__c</referenceTo>
    <relationshipLabel>Respostas</relationshipLabel>
    <relationshipName>Respostas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pergunta</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Respostas</relationshipLabel>
    <relationshipName>Respostas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventRelated__c/EventRelated__c.object-meta.xml
<CustomObject>
    <description>Objeto espelho do evento, para cada evento criado, será necessário criar um registro neste objeto. Este objeto existe para que seja possível relacionar o objeto de respostas ao objeto de eventos, porém, o Salesforce não permite que seja criado um relacionamento diretamente do objeto Respostas para o objeto Eventos, então criamos um objeto evento relacionado, que se relaciona com Eventos e Respostas.</description>
    
    <label>Evento Relacionado</label>
    <nameField>
        <displayFormat>EVT-{00000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Relacionados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as perguntas que os usuários terão acesso ao criar um evento de visita.</description>
    
    <label>Pergunta</label>
    <nameField>
        <displayFormat>PER-{00000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Perguntas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/PicklistValues__c.field-meta.xml
<CustomField>
    <fullName>PicklistValues__c</fullName>
    <description>Este campo armazena os valores predefinidos que serão utilizados no tipo de resposta, separados por ponto e virgula, ex. Houve praga; Não houve praga;Não sei.</description>
    <inlineHelpText>Este campo armazena os valores predefinidos que serão utilizados no tipo de resposta, separados por ponto e virgula, ex. Houve praga; Não houve praga;Não sei.</inlineHelpText>
    <label>Valores Predefinidos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/QuestionDescription__c.field-meta.xml
<CustomField>
    <fullName>QuestionDescription__c</fullName>
    <description>Descrição da pergunta que o usuário fará para o cliente final.</description>
    <inlineHelpText>Descrição da pergunta que o usuário fará para o cliente final.</inlineHelpText>
    <label>Descrição da Pergunta</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/QuestionType__c.field-meta.xml
<CustomField>
    <fullName>QuestionType__c</fullName>
    <description>Este campo indica o tipo de resposta que a pergunta espera, caixa de seleção para Sim/Não, Data para Data (14/08/1989), Valores Predefinidos para uma lista predefinida e campo de texto para livre preenchimento.</description>
    <inlineHelpText>Este campo indica o tipo de resposta que a pergunta espera, caixa de seleção para Sim/Não, Data para Data (14/08/1989), Valores Predefinidos para uma lista predefinida e campo de texto para livre preenchimento.</inlineHelpText>
    <label>Tipo Resposta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Caixa de Seleção</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Valores Predefinidos</fullName>
            </value>
            <value>
                <fullName>Texto para livre preenchimento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo que informa se o RTV pode deixar a pergunta em branco ou não.</description>
    <inlineHelpText>Campo que informa se o RTV pode deixar a pergunta em branco ou não.</inlineHelpText>
    <label>Obrigatório</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuestionXEventType__c/QuestionXEventType__c.object-meta.xml
<CustomObject>
    
    <label>Pergunta da Visita</label>
    <nameField>
        <displayFormat>VIS-{00000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Perguntas das Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuestionXEventType__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>Tipo de Visita</label>
    <referenceTo>EventTypes__c</referenceTo>
    <relationshipLabel>Perguntas das Visitas</relationshipLabel>
    <relationshipName>Perguntas_das_Visitas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuestionXEventType__c/fields/Pergunta__c.field-meta.xml
<CustomField>
    <fullName>Pergunta__c</fullName>
    <label>Pergunta</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Perguntas das Visitas</relationshipLabel>
    <relationshipName>Perguntas_das_Visitas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AnswersAndQuestionsScreenController.cls
public with sharing class AnswersAndQuestionsScreenController {

    @AuraEnabled
    public static String getAccount (String eventId) {
        Event event = [
            SELECT Id, EventType__c, Account__c FROM Event WHERE Id =: eventId
        ];

        return event.Account__c;
    }

    @AuraEnabled
    public static String getEventRelated (String eventId) {
        Event event = [
            SELECT Id, EventType__c, Account__c, EventRelated__c FROM Event WHERE Id =: eventId
        ];

        return event.EventRelated__c;
    }

    @AuraEnabled
    public static List<QuestionObject> getQuestions (String eventId) {

        Event event = [
            SELECT Id, EventType__c, EventRelated__c FROM Event WHERE Id =: eventId
        ];

        String eventRelatedId = event.EventRelated__c;

        Boolean hasAnswers = false;

        List<Answer__c> checkAnswers = [
            SELECT Id, EventRelated__c, Question__c, Answer__c, AnswerBoolean__c, AnswerDate__c FROM Answer__c WHERE EventRelated__c =: eventRelatedId
        ];

        System.debug(checkAnswers);

        if (!checkAnswers.isEmpty()) {
            hasAnswers = true;
        }

        Map<Id, Answer__c> mapIdToAnswer = new Map<Id, Answer__c>();

        if (hasAnswers) {
            for (Answer__c answer : checkAnswers) {
                if (!mapIdToAnswer.containsKey(answer.Question__c)) {
                    mapIdToAnswer.put(answer.Question__c, answer);
                }
            }
        }

        String visitType;

        visitType = event.EventType__c;

        List<QuestionXEventType__c> questionXEventTypeList = [
            SELECT Id, Pergunta__c, EventType__c FROM QuestionXEventType__c WHERE EventType__c =: visitType
        ];

        List<String> questionIdList = new List<String>();

        for (QuestionXEventType__c questionEvent : questionXEventTypeList) {
            questionIdList.add(questionEvent.Pergunta__c);
        }

        List<Question__c> questions = [
            SELECT Id, QuestionDescription__c, Required__c, QuestionType__c, PicklistValues__c FROM Question__c WHERE Id IN: questionIdList
        ];

        List<QuestionObject> questionObjectList = new List<QuestionObject>();

        for (Question__c question : questions) {
            if (hasAnswers) {
                questionObjectList.add(new QuestionObject(question, mapIdToAnswer.get(question.Id)));
            } else {
                questionObjectList.add(new QuestionObject(question));
            }
        }

        return questionObjectList;
    }

    @AuraEnabled(cacheable=false)
    public static List<AnswerObject> saveAnswers (String answers) {

        System.debug(answers);

        List<AnswerObject> answerObjectList = (List<AnswerObject>)JSON.deserialize(answers, List<AnswerObject>.class);

        System.debug(answerObjectList);

        List<Answer__c> answerList = new List<Answer__c>();

        for(AnswerObject answer : answerObjectList) {
            answerList.add(convertToAnswerObject(answer));
        }

        System.debug(answerList.size());
        System.debug(answerList);

        upsert answerList;

        return answerObjectList;
    }

    @AuraEnabled
    public static Answer__c convertToAnswerObject(AnswerObject answerObject) {
        Answer__c answer = new Answer__c (
            Id = answerObject.id,
            Account__c = answerObject.account,
            EventRelated__c = answerObject.eventRelated,
            Question__c = answerObject.question,
            Answer__c = answerObject.answer,
            AnswerBoolean__c = answerObject.answerBoolean,
            AnswerDate__c = answerObject.answerDate
        );

        return answer;
    }

    public class QuestionObject {
        @AuraEnabled public String Id {get;set;}
        @AuraEnabled public String QuestionDescription {get;set;}
        @AuraEnabled public Boolean Required {get;set;}
        @AuraEnabled public String QuestionType {get;set;}
        @AuraEnabled public Boolean EnableCheckBox {get;set;}
        @AuraEnabled public Boolean EnableTextArea {get;set;}
        @AuraEnabled public Boolean EnableDataField {get;set;}
        @AuraEnabled public Boolean EnablePickList {get;set;}
        @AuraEnabled public String PicklistValues {get;set;}
        @AuraEnabled public Date AnswerDate {get;set;}
        @AuraEnabled public String Answer {get;set;}
        @AuraEnabled public Boolean AnswerBoolean {get;set;}
        @AuraEnabled public String AnswerId {get;set;}

        public QuestionObject(Question__c questions) {
            this.Id                     = questions.Id;
            this.QuestionDescription    = questions.QuestionDescription__c;
            this.Required               = questions.Required__c;
            this.PicklistValues         = questions.PicklistValues__c;
            this.QuestionType           = questions.QuestionType__c;
            this.EnableCheckBox         = questions.QuestionType__c == 'Caixa de Seleção' ? true : false;
            this.EnableTextArea         = questions.QuestionType__c == 'Texto para livre preenchimento' ? true : false;
            this.EnableDataField        = questions.QuestionType__c == 'Data' ? true : false;
            this.EnablePickList         = questions.QuestionType__c == 'Valores Predefinidos' ? true : false;
            this.AnswerDate             = null;
            this.Answer                 = null;
            this.AnswerBoolean          = false;
            this.AnswerId               = null;
        }

        public QuestionObject(Question__c questions, Answer__c answer) {
            this.Id                     = questions.Id;
            this.QuestionDescription    = questions.QuestionDescription__c;
            this.Required               = questions.Required__c;
            this.PicklistValues         = questions.PicklistValues__c;
            this.QuestionType           = questions.QuestionType__c;
            this.EnableCheckBox         = questions.QuestionType__c == 'Caixa de Seleção' ? true : false;
            if (this.EnableCheckBox) {
                this.AnswerBoolean = answer.AnswerBoolean__c ? answer.AnswerBoolean__c : false;
            }
            this.EnableTextArea         = questions.QuestionType__c == 'Texto para livre preenchimento' ? true : false;
            if (this.EnableTextArea) {
                this.Answer = answer.Answer__c;
                this.AnswerBoolean = false;
            }
            this.EnableDataField        = questions.QuestionType__c == 'Data' ? true : false;
            if (this.EnableDataField) {
                this.AnswerDate = answer.AnswerDate__c;
                this.AnswerBoolean = false;
            }
            this.EnablePickList         = questions.QuestionType__c == 'Valores Predefinidos' ? true : false;
            if (this.EnablePickList) {
                this.Answer = answer.Answer__c;
                this.AnswerBoolean = false;
            }
            this.AnswerId = answer.Id;
        }
    }

    public class AnswerObject {
        @AuraEnabled public String id {get;set;}
        @AuraEnabled public String account {get;set;}
        @AuraEnabled public String question {get;set;}
        @AuraEnabled public String eventRelated {get;set;}
        @AuraEnabled public String answer {get;set;}
        @AuraEnabled public Boolean answerBoolean {get;set;}
        @AuraEnabled public Date answerDate {get;set;}

        //public AnswerObject (String answerObj) {
        //    this.id = answerObj.id;
        //    this.account = answerObj.account;
        //    this.question = answerObj.question;
        //    this.eventRelated = answerObj.eventRelated;
        //    this.answer = answerObj.answer;
        //    this.answerBoolean = answerObj.answerBoolean;
        //    this.answerDate = answerObj.answerDate;
        //}

    }
}