force-app/main/default/objects/CustomerPerOrg__c/CustomerPerOrg__c.object-meta.xml
<CustomObject>
    <description>Armazenará as configurações de clientes por organização.</description>
    
    <label>Cliente por Organização</label>
    <nameField>
        <displayFormat>CPO-{000000}</displayFormat>
        <label>Nome de Clientes por Organização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes por Organização</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerPerOrg__c/fields/ActivitySector__c.field-meta.xml
<CustomField>
    <fullName>ActivitySector__c</fullName>
    <label>Setor de Atividade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>Agricultura</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Pecuária</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Máquinas Implementos</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Commodities</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>Outras Saídas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerPerOrg__c/fields/ClientGroup__c.field-meta.xml
<CustomField>
    <fullName>ClientGroup__c</fullName>
    <label>Grupo de Clientes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerPerOrg__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes por Organização</relationshipLabel>
    <relationshipName>CustomerPerOrg</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerPerOrg__c/fields/DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>DistributionChannel__c</fullName>
    <label>Canal de Distribuição</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>Venda Diretas</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Vendas Indiretas</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Transferências</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerPerOrg__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Clientes por Organização</relationshipLabel>
    <relationshipName>CustomerPerOrg</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerPerOrg__c/fields/SalesSector__c.field-meta.xml
<CustomField>
    <fullName>SalesSector__c</fullName>
    <label>Setor de Vendas (Regional)</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    
    <label>Organização de Vendas</label>
    <nameField>
        <label>Nome de Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizações de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerPerOrgController.cls
public with sharing class CustomerPerOrgController {
 
    @AuraEnabled(cacheable=true)
    public static ResponseCallBackLwc getCustomerPerOrg(String accountId, String orgId, String activitySector) {
        System.debug('accountId: ' + accountId);
        System.debug('orgId: ' + orgId);
        System.debug('activitySector: ' + activitySector);
        List<CustomerPerOrg__c> cpoObj = new List<CustomerPerOrg__c>();
        if(activitySector == null) {
            cpoObj = [SELECT Id, IsDeleted,
            Name, CreatedDate, CreatedById,
            LastModifiedDate, LastModifiedById,
            SystemModstamp, LastActivityDate,
            LastViewedDate, LastReferencedDate, Blocked__c, ClientGroup__c, ActivitySector__c,
            Customer__c, DistributionChannel__c,
            SalesOrg__c, SalesOrg__r.Name, SalesSector__c FROM CustomerPerOrg__c WHERE Customer__c =: accountId AND SalesOrg__c =: orgId AND Blocked__c = false AND ActivitySector__c != null AND DistributionChannel__c = '10' AND ClientGroup__c != null];
    
            return cpoObj.isEmpty() == false ? new ResponseCallBackLwc(cpoObj) : null;
        } else {
            cpoObj = [SELECT Id, IsDeleted,
            Name, CreatedDate, CreatedById,
            LastModifiedDate, LastModifiedById,
            SystemModstamp, LastActivityDate,
            LastViewedDate, LastReferencedDate, Blocked__c, ClientGroup__c, ActivitySector__c,
            Customer__c, DistributionChannel__c,
            SalesOrg__c, SalesOrg__r.Name, SalesSector__c FROM CustomerPerOrg__c WHERE Customer__c =: accountId AND SalesOrg__c =: orgId AND Blocked__c = false AND ClientGroup__c != null AND DistributionChannel__c = '10' AND ActivitySector__c =: activitySector LIMIT 1];
    
            return cpoObj.isEmpty() == false ? new ResponseCallBackLwc(cpoObj) : null;
        }
    }
 
    public class ResponseCallBackLwc {
        @AuraEnabled public Boolean IsBlock                 {get; set;}
        @AuraEnabled public Boolean HaveCustomer            {get; set;}
        @AuraEnabled public Boolean HaveSector              {get; set;}
        @AuraEnabled public String  ActivitySectorList      {get; set;}
        @AuraEnabled public CustomerPerOrg__c CustPerOrgObj {get; set;}

        //Construtor
        public ResponseCallBackLwc(List<CustomerPerOrg__c> customerPerOrg) {
            this.CustPerOrgObj                       = new CustomerPerOrg__c();
            List<String> strListActivitySector       = new List<String>();
            List<String> strListActivitySectorToJoin = new List<String>();

            for(CustomerPerOrg__c cpo : customerPerOrg) {
                if(cpo.ActivitySector__c.contains(';')) {
                    strListActivitySector = cpo.ActivitySector__c.split(';');
                    if(!strListActivitySectorToJoin.contains(strListActivitySector[0])) {
                        strListActivitySectorToJoin.add(strListActivitySector[0]);
                    }
                } else {
                    if(!strListActivitySectorToJoin.contains(cpo.ActivitySector__c)) {
                        strListActivitySectorToJoin.add(cpo.ActivitySector__c);
                    }
                }
                this.ActivitySectorList = strListActivitySectorToJoin.size() > 1 ? String.join(strListActivitySectorToJoin,';') : strListActivitySectorToJoin[0];
                this.IsBlock       = false;
                this.HaveSector    = true;
                this.HaveCustomer  = true;
                this.CustPerOrgObj = cpo;
            }
        }
    }
}