force-app/main/default/objects/CustomerPerOrg__c/CustomerPerOrg__c.object-meta.xml
<CustomObject>
    <description>Armazenará as configurações de clientes por organização.</description>
    
    <label>Cliente por Organização</label>
    <nameField>
        <displayFormat>CPO-{000000}</displayFormat>
        <label>Nome de Clientes por Organização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes por Organização</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerPerOrg__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes por Organização</relationshipLabel>
    <relationshipName>CustomerPerOrg</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerPerOrg__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CustomerPerOrgDAO.cls
public with sharing class CustomerPerOrgDAO {

    public static List<CustomerPerOrg__c> getCustomerPerOrgByExternalId(List<String> externalIds, Set<String> customerPerOrgUsedFields) {

        String query = new Q(CustomerPerOrg__c.SObjectType)
            .selectFields(customerPerOrgUsedFields)
            .add(Q.condition('ExternalId__c').isIn(externalIds))
            .add(Q.condition('Blocked__c').equalsTo(false))
            .build();
            
        return Database.query(query);
    }

    public static List<CustomerPerOrg__c> getCustomerPerOrgByAccountIdDiffIds(List<String> ids, List<String> accountIds, Set<String> customerPerOrgUsedFields){
        
        String query = new Q(CustomerPerOrg__c.SObjectType)
            .selectFields(customerPerOrgUsedFields)
            .add(Q.condition('Id').isNotIn(ids))
            .add(Q.condition('Customer__c').isIn(accountIds))
            .add(Q.condition('Blocked__c').equalsTo(false))
            .build();
            
        return Database.query(query);
    }

}