force-app/main/default/objects/SalesTeam__c/SalesTeam__c.object-meta.xml
<CustomObject>
    
    <label>Equipe de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes de Vendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente Comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesTeams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesTeamDAO.cls
public with sharing class SalesTeamDAO {
    
    public static List<SalesTeam__c> getSalesTeamByExternalId(List<String> externalIds, Set<String> salesTeamUsedFields) {

        String query = new Q(SalesTeam__c.SObjectType)
            .selectFields(salesTeamUsedFields)
            .add(Q.condition('ExternalId__c').isIn(externalIds))
            .build();
            
        return Database.query(query);
    }
    public static List<SalesTeam__c> getSalesTeamById(List<String> Ids, Set<String> salesTeamUsedFields) {

        String query = new Q(SalesTeam__c.SObjectType)
            .selectFields(salesTeamUsedFields)
            .add(Q.condition('Id').isIn(Ids))
            .build();
            
        return Database.query(query);
    }

    public static List<SalesTeam__c> getSalesTeamByManager(List<String> managers, Set<String> salesTeamUsedFields) {

        String query = new Q(SalesTeam__c.SObjectType)
            .selectFields(salesTeamUsedFields)
            .add(Q.condition('Manager__c').isIn(managers))
            .build();
            
        return Database.query(query);
    }

}