force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena o custo de frete por tonelada considerando a cidade origem e a cidade destino.</description>
    
    <label>Frete</label>
    <nameField>
        <displayFormat>FRT-{0000}</displayFormat>
        <label>Nome do Frete</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Freight__c/fields/ExternalIDIndex__c.field-meta.xml
<CustomField>
    <fullName>ExternalIDIndex__c</fullName>
    <externalId>true</externalId>
    <label>External ID Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FreightHelper.cls
public with sharing class FreightHelper {
    private static Boolean isEnabled;

    static{
        isEnabled = true;
    }

    public static Boolean isTriggerEnabled(){
        return isEnabled;
    }
    
    public static Boolean disableTrigger(){
        return isEnabled = false;
    }

    public static Boolean enableTrigger(){
        return isEnabled = true;
    }
    public static void mapRecords(List<Freight__c> context){
        for(Freight__c fre : context){
            fre.ExternalId__c = fre.ExternalIdIndex__c;
        }
    }
}