force-app/main/default/objects/Integration__c/Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Informações de autenticação da integração com o SAP</description>
    <label>Integration</label>
</CustomObject>

force-app/main/default/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    
    <label>Log de Integração</label>
    <nameField>
        <displayFormat>LOG{0000000000}</displayFormat>
        <label>Nome de Log de Integração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs de Integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegrationLog__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Data de Execução</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/ExternalIds__c.field-meta.xml
<CustomField>
    <fullName>ExternalIds__c</fullName>
    <description>Comcatenação de códigos para fácil localização do Log de Integração</description>
    <externalId>true</externalId>
    <label>Códigos Externos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/HasAttachment__c.field-meta.xml
<CustomField>
    <fullName>HasAttachment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Devido a quantidade de dados no payload, é necessário um anexo?</description>
    <inlineHelpText>Devido a quantidade de dados no payload, é necessário um anexo?</inlineHelpText>
    <label>Possui Anexo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/Integration__c.field-meta.xml
<CustomField>
    <fullName>Integration__c</fullName>
    <description>Nome da integração que deu origem a este log</description>
    <inlineHelpText>Nome da integração que deu origem a este log</inlineHelpText>
    <label>Integração</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/PayloadIN__c.field-meta.xml
<CustomField>
    <fullName>PayloadIN__c</fullName>
    <description>Payload com informações de entrada</description>
    <inlineHelpText>Payload com informações de entrada</inlineHelpText>
    <label>Payload IN</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/PayloadOUT__c.field-meta.xml
<CustomField>
    <fullName>PayloadOUT__c</fullName>
    <description>Payload com informações de saida</description>
    <inlineHelpText>Payload com informações de saida</inlineHelpText>
    <label>Payload OUT</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>OK/Erro</description>
    <inlineHelpText>OK/Erro</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>Erro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationLog.cls
public with sharing class IntegrationLog {
    public static Map<String, ID> logRecordTypeIDMap;
    
    public static void initializeLog(){
        if (logRecordTypeIDMap == null){
            logRecordTypeIDMap = new Map<String, ID>();

            for (RecordType rType : RecordTypeDAO.getRecordTypeBySObjectType(new List<String>{'IntegrationLog__c'}, new Set<String>{'Id, DeveloperName'})){
                logRecordTypeIDMap.put(rType.DeveloperName, rType.ID);
            }
        }
    }

    public static void createIntegrationLog(String integrationName, String recordTypeName, String payloadIN, String payloadOUT, Boolean hasAnyErrors){
        createIntegrationLog(integrationName, recordTypeName, payloadIN, payloadOUT, hasAnyErrors, null);
    }

    public static void createIntegrationLog(String integrationName, String recordTypeName, String payloadIN, String payloadOUT, Boolean hasAnyErrors, String ExternalIds){
        System.debug('ON WS LOG: '+ integrationName);

        initializeLog();
        System.debug('recordTypeName: ' + recordTypeName);
        System.debug('logRecordTypeIDMap: ' + logRecordTypeIDMap);
        System.debug('get do logRecordTypeIdMap: ' + logRecordTypeIDMap.get(recordTypeName));
        Boolean shouldUseAttachmentIN  = (payloadIN.length() > 100000);
        Boolean shouldUseAttachmentOUT = (payloadOUT.length() > 100000);

        Datetime tNow = System.now();

        ID rType;
        if ((rType = logRecordTypeIDMap.get(recordTypeName)) == null){
            System.debug('FAILED TO GET RECORDTYPE FROM LIST');
        }
        IntegrationLog__c log = new IntegrationLog__c(
            RecordTypeId       = rType,
            Integration__c     = integrationName,
            hasAttachment__c   = (shouldUseAttachmentIN || shouldUseAttachmentOUT),
            PayloadIN__c       = (shouldUseAttachmentIN  ? '' : payloadIN),
            PayloadOUT__c      = (shouldUseAttachmentOUT ? '' : payloadOUT),
            Status__c          = (hasAnyErrors ? 'Error' : 'OK'),
            Date__c 		   = tNow,
            ExternalIds__c     = ExternalIds
        );

        try{
            insert log;

            // Maximum Size for a String
            if (shouldUseAttachmentIN){
            	createAttachment(log.Id, integrationName, 'IN', log.Name, String.valueOf(tNow), payloadIN);
            }

            if (shouldUseAttachmentOUT){
            	createAttachment(log.Id, integrationName, 'OUT', log.Name, String.valueOf(tNow), payloadOUT);
            }

            System.debug('NEW LOG CREATED: '+log.Id);
        }catch(Exception e){
            System.debug('EXCEPTION ON LOG - Please review parameters - '+e.getMessage()+' - '+e.getStackTraceString());
        }
    }

    @TestVisible
    private static void createAttachment(String recordId, String integrationName, String inOrOut, String logName, String timeAsString, String payload){
    	Attachment att = new Attachment();
    	att.Name = 'LOG-'+integrationName+'-'+inOrOut+'-'+timeAsString+'.txt';
    	att.Body = Blob.valueOf(payload);
    	att.ParentId = recordId;
    	insert att;
    }
}