force-app/main/default/objects/RelatedUserSalesTeam__c/RelatedUserSalesTeam__c.object-meta.xml
<CustomObject>
    
    <label>Equipe de Vendas X Usuarios</label>
    <nameField>
        <displayFormat>EVU-{0000}</displayFormat>
        <label>Nome de Equipe de Vendas dos Usuarios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipe de Vendas X Usuarios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RelatedUserSalesTeam__c/fields/RTV__c.field-meta.xml
<CustomField>
    <fullName>RTV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RelatedUserSalesTeams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelatedUserSalesTeamDAO.cls
public with sharing class RelatedUserSalesTeamDAO {
    
    public static List<RelatedUserSalesTeam__c> getRelatedUserSalesTeamByRTV(List<String> rtvs, Set<String> relatedUserSalesTeamUsedFields) {

        String query = new Q(RelatedUserSalesTeam__c.SObjectType)
            .selectFields(relatedUserSalesTeamUsedFields)
            .add(Q.condition('RTV__c').isIn(rtvs))
            .build();
            
        return Database.query(query);
    }

}