force-app/main/default/objects/SalesCondition__c/SalesCondition__c.object-meta.xml
<CustomObject>
    
    <label>Condição de venda</label>
    <nameField>
        <label>Nome de Condição de venda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de venda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesCondition__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SalesConditionDAO.cls
public with sharing class SalesConditionDAO {
    
    public static List<SalesCondition__c> getActiveSalesConditions(Set<String> salesConditionUsedFields) {

        String query = new Q(SalesCondition__c.SObjectType)
            .selectFields(salesConditionUsedFields)
            .add(Q.condition('IsActive__c').equalsTo(true))
            .build();
            
        return Database.query(query);
    }
}