force-app/main/default/objects/Account/fields/AreaCultivated__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivated__c</fullName>
    <label>Área de Plantio das Propriedades</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/AreaCultivatedLand__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivatedLand__c</fullName>
    <formula>AreaCultivated__c + AreaPasture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Este Campo é a soma de Área de Plantio mais Área de Pastagem.</inlineHelpText>
    <label>Total de Área Cultivada das Propriedades</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/AreaCultivatedLandMeters__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivatedLandMeters__c</fullName>
    <inlineHelpText>Este Campo é a soma de Áreas de Plantio mais Áreas de Pastagem.</inlineHelpText>
    <label>Total de Áreas Cultivadas</label>
    <summarizedField>DelimitedLand__c.AreaCultivatedLandMeters__c</summarizedField>
    <summaryForeignKey>DelimitedLand__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/AreaNotAllocated__c.field-meta.xml
<CustomField>
    <fullName>AreaNotAllocated__c</fullName>
    <label>Área Não Alocada das Propriedades</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/AreaNotAllocatedMeters__c.field-meta.xml
<CustomField>
    <fullName>AreaNotAllocatedMeters__c</fullName>
    <label>Área não Alocada</label>
    <summarizedField>DelimitedLand__c.AreaNotAllocatedMeters__c</summarizedField>
    <summaryForeignKey>DelimitedLand__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/AreaPasture__c.field-meta.xml
<CustomField>
    <fullName>AreaPasture__c</fullName>
    <label>Área de pastagem das Propriedades</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/AreaPreservation__c.field-meta.xml
<CustomField>
    <fullName>AreaPreservation__c</fullName>
    <label>Área de preservação das Propriedades</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/AreaPreservationMeters__c.field-meta.xml
<CustomField>
    <fullName>AreaPreservationMeters__c</fullName>
    <label>Área de Preservação Ambiental</label>
    <summarizedField>DelimitedLand__c.AreaPreservationMeters__c</summarizedField>
    <summaryForeignKey>DelimitedLand__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Crop__c/Crop__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Safra provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Safra</label>
    <nameField>
        <label>Nome de Safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Culture__c/Culture__c.object-meta.xml
<CustomObject>
    
    <label>Cultura</label>
    <nameField>
        <label>Nome da Cultura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DelimitedLand__c/DelimitedLand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os talhões, talhão é um terreno delimitado.</description>
    
    <label>Talhão</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talhões</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DelimitedLand__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Name</field>
            <operation>contains</operation>
            <value>Propriedade</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Talhões</relationshipLabel>
    <relationshipName>Talhoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaCultivated__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivated__c</fullName>
    <label>Área de Plantio</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaCultivatedLand__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivatedLand__c</fullName>
    <formula>AreaCultivated__c + AreaPasture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Este Campo é a soma de Área de Plantio mais Área de Pastagem.</inlineHelpText>
    <label>Total de Áreas Cultivadas</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaCultivatedLandMeters__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivatedLandMeters__c</fullName>
    <formula>CASE(  UnitMeasurement__c ,&quot;Hectare&quot;, 10000,&quot;Are&quot;, 100, &quot;Centiare&quot;, 1,&quot;Alqueire Mineiro&quot;, 48400, &quot;Alqueire Goiano&quot;, 48400, &quot;Alqueire Paulista&quot;, 24200, &quot;Alqueire do norte&quot;, 27225, &quot;Alqueire do RJ&quot; , 27225, &quot;Alqueire Baiano&quot;, 69800, &quot;Litro&quot;, 605, 1 ) *   AreaCultivatedLand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Este Campo é a soma de Área de Plantio mais Área de Pastagem.</inlineHelpText>
    <label>Total de Áreas Cultivadas (m2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaCultivatedMeteers__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivatedMeteers__c</fullName>
    <formula>CASE(  UnitMeasurement__c ,&quot;Hectare&quot;, 10000,&quot;Are&quot;, 100, &quot;Centiare&quot;, 1,&quot;Alqueire Mineiro&quot;, 48400, &quot;Alqueire Goiano&quot;, 48400, &quot;Alqueire Paulista&quot;, 24200, &quot;Alqueire do norte&quot;, 27225, &quot;Alqueire do RJ&quot; , 27225, &quot;Alqueire Baiano&quot;, 69800, &quot;Litro&quot;, 605, 1 ) *   AreaCultivated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Área de Plantio (m2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaNotAllocated__c.field-meta.xml
<CustomField>
    <fullName>AreaNotAllocated__c</fullName>
    <label>Área Não Alocada</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaNotAllocatedMeters__c.field-meta.xml
<CustomField>
    <fullName>AreaNotAllocatedMeters__c</fullName>
    <formula>CASE(  UnitMeasurement__c ,&quot;Hectare&quot;, 10000,&quot;Are&quot;, 100, &quot;Centiare&quot;, 1,&quot;Alqueire Mineiro&quot;, 48400, &quot;Alqueire Goiano&quot;, 48400, &quot;Alqueire Paulista&quot;, 24200, &quot;Alqueire do norte&quot;, 27225, &quot;Alqueire do RJ&quot; , 27225, &quot;Alqueire Baiano&quot;, 69800, &quot;Litro&quot;, 605, 1 ) *  AreaNotAllocated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Área não Alocada (m2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaPasture__c.field-meta.xml
<CustomField>
    <fullName>AreaPasture__c</fullName>
    <label>Área de pastagem</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaPastureMeteers__c.field-meta.xml
<CustomField>
    <fullName>AreaPastureMeteers__c</fullName>
    <formula>CASE(  UnitMeasurement__c ,&quot;Hectare&quot;, 10000,&quot;Are&quot;, 100, &quot;Centiare&quot;, 1,&quot;Alqueire Mineiro&quot;, 48400, &quot;Alqueire Goiano&quot;, 48400, &quot;Alqueire Paulista&quot;, 24200, &quot;Alqueire do norte&quot;, 27225, &quot;Alqueire do RJ&quot; , 27225, &quot;Alqueire Baiano&quot;, 69800, &quot;Litro&quot;, 605, 1 ) *  AreaPasture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Área de Pastagem (m2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaPreservation__c.field-meta.xml
<CustomField>
    <fullName>AreaPreservation__c</fullName>
    <label>Área de preservação ambiental</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaPreservationMeters__c.field-meta.xml
<CustomField>
    <fullName>AreaPreservationMeters__c</fullName>
    <formula>CASE(  UnitMeasurement__c ,&quot;Hectare&quot;, 10000,&quot;Are&quot;, 100, &quot;Centiare&quot;, 1,&quot;Alqueire Mineiro&quot;, 48400, &quot;Alqueire Goiano&quot;, 48400, &quot;Alqueire Paulista&quot;, 24200, &quot;Alqueire do norte&quot;, 27225, &quot;Alqueire do RJ&quot; , 27225, &quot;Alqueire Baiano&quot;, 69800, &quot;Litro&quot;, 605, 1 ) *   AreaPreservation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Área de Preservação Ambiental (m2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/UnitMeasurement__c.field-meta.xml
<CustomField>
    <fullName>UnitMeasurement__c</fullName>
    <description>Lista de seleção com todas as unidades de medidas</description>
    <label>Unidade de Medida</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hectare</fullName>
            </value>
            <value>
                <fullName>Are</fullName>
            </value>
            <value>
                <fullName>Centiare</fullName>
            </value>
            <value>
                <fullName>Alqueire Mineiro</fullName>
            </value>
            <value>
                <fullName>Alqueire Goiano</fullName>
            </value>
            <value>
                <fullName>Alqueire Paulista</fullName>
            </value>
            <value>
                <fullName>Alqueire do norte</fullName>
            </value>
            <value>
                <fullName>Alqueire do RJ</fullName>
            </value>
            <value>
                <fullName>Alqueire Baiano</fullName>
            </value>
            <value>
                <fullName>Litro</fullName>
            </value>
            <value>
                <fullName>Metro Quadrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/DelimitedLandCultures__c.object-meta.xml
<CustomObject>
    
    <label>Cultura do Talhão</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas dos Talhões</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DelimitedLandCultures__c/fields/AreaCultivated__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivated__c</fullName>
    <label>Área Cultivada</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Culturas dos Talhões</relationshipLabel>
    <relationshipName>Culturas_dos_Talhoes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cultura</label>
    <referenceTo>Culture__c</referenceTo>
    <relationshipLabel>Culturas dos Talhões</relationshipLabel>
    <relationshipName>Culturas_dos_Talhoes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/DelimitedLand__c.field-meta.xml
<CustomField>
    <fullName>DelimitedLand__c</fullName>
    <label>Talhão</label>
    <referenceTo>DelimitedLand__c</referenceTo>
    <relationshipLabel>Culturas dos Talhões</relationshipLabel>
    <relationshipName>Culturas_dos_Talhoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/TotalAreaMeters__c.field-meta.xml
<CustomField>
    <fullName>TotalAreaMeters__c</fullName>
    <formula>CASE(  DelimitedLand__r.UnitMeasurement__c  ,&quot;Hectare&quot;, 10000,&quot;Are&quot;, 100, &quot;Centiare&quot;, 1,&quot;Alqueire Mineiro&quot;, 48400, &quot;Alqueire Goiano&quot;, 48400, &quot;Alqueire Paulista&quot;, 24200, &quot;Alqueire do norte&quot;, 27225, &quot;Alqueire do RJ&quot; , 27225, &quot;Alqueire Baiano&quot;, 69800, &quot;Litro&quot;, 605, 1 ) *  AreaCultivated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Área Total (m²)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DelimitedLandTriggerHelper.cls
public without sharing class DelimitedLandTriggerHelper {
    private static Boolean runTrigger;

    static {
        runTrigger = true;
    }

    public static Boolean isTriggerEnabled(){
        return runTrigger;
    }

    public static Boolean enableTrigger(){
        return runTrigger = true;
    }

    public static Boolean disableTrigger(){
        return runTrigger = false;
    }

    public static void checkDelimitedLandId(List<DelimitedLandCultures__c> delimitedLandCultureList) {
        List<Id> delimitedLandIdList = new List<Id>();

        for (DelimitedLandCultures__c delimitedLandCulture : delimitedLandCultureList) {
            delimitedLandIdList.add(delimitedLandCulture.DelimitedLand__c);
        }

        sendDelimitedLandNotFuture(delimitedLandIdList);
    }

    public static void checkCultureRecords(Map<Id, DelimitedLandCultures__c> context){

        Map<Id, Set<Id>> contextMap = new Map<Id, Set<Id>>();
        List<DelimitedLand__c> contextDelimitedLand = new List<DelimitedLand__c>();
        for(DelimitedLandCultures__c cultures : context.values()){
            contextDelimitedLand.add(new DelimitedLand__c(Id = cultures.DelimitedLand__c));
            if(!contextMap.containsKey(cultures.DelimitedLand__c))
                contextMap.put(cultures.DelimitedLand__c, new Set<Id>());
            contextMap.get(cultures.DelimitedLand__c).add(cultures.Id);
        }
        
        Database.SaveResult[] results = Database.update(contextDelimitedLand, false);
        for(Database.SaveResult sv : results){
            if(sv.isSuccess()) continue;

            for(Id cultureId : contextMap.get(sv.getId()))
                context.get(cultureId).addError(getError(sv));
        }
    }
    public static void checkCultureRecords(Map<Id, DelimitedLand__c> context){
        Map<String, Decimal> delimitedMap = new Map<String, Decimal>();  
        for(DelimitedLandCultures__c culture : [SELECT id, TotalAreaMeters__c, DelimitedLand__r.AreaPasture__c, DelimitedLand__r.AreaCultivated__c, AreaCultivated__c, Crop__c, DelimitedLand__c, DelimitedLand__r.AreaCultivatedLandMeters__c, Culture__c, Culture__r.name, DelimitedLand__r.UnitMeasurement__c, DelimitedLand__r.AreaCultivatedLand__c
                                                FROM DelimitedLandCultures__c 
                                                WHERE DelimitedLand__c IN : context.keySet()]){
            String key = culture.Crop__c+'_'+culture.DelimitedLand__c+'_'+culture.Culture__r.name;

            delimitedMap.put(key, (delimitedMap.containsKey(key) ? delimitedMap.get(key) : 0) + culture.AreaCultivated__c);
            
            if(culture.DelimitedLand__r.AreaCultivatedLand__c < delimitedMap.get(key)){
                context.get(culture.DelimitedLand__c).addError('A área do Talhão ('+culture.DelimitedLand__r.AreaCultivatedLand__c.setScale(2)+' '+culture.DelimitedLand__r.UnitMeasurement__c+') é menor do que a area cultivada pela cultura: '+culture.Culture__r.name+' ('+delimitedMap.get(key).setScale(2)+' '+culture.DelimitedLand__r.UnitMeasurement__c+')');
            }
        }
    }
    public static void sumAccountLand(List<DelimitedLand__c> context){
        
        Map<Id, Account> accMap = new Map<Id, Account>();
        for(DelimitedLand__c lands : [SELECT id, Account__c, Account__r.ParentId, AreaCultivatedMeteers__c, AreaNotAllocatedMeters__c, AreaPastureMeteers__c, AreaPreservationMeters__c FROM DelimitedLand__c WHERE Account__c IN :Collection.of(context).pluckIds(DelimitedLand__c.Account__c) AND Account__r.ParentId != null]){
            Account acc = accMap.containsKey(lands.Account__r.ParentId) ? accMap.get(lands.Account__r.ParentId) : new Account(Id = lands.Account__r.ParentId, AreaCultivated__c = 0, AreaNotAllocated__c = 0, AreaPasture__c = 0, AreaPreservation__c = 0);
            acc.AreaCultivated__c   += lands.AreaCultivatedMeteers__c;
            acc.AreaNotAllocated__c += lands.AreaNotAllocatedMeters__c;
            acc.AreaPasture__c      += lands.AreaPastureMeteers__c;
            acc.AreaPreservation__c += lands.AreaPreservationMeters__c;
            accMap.put(lands.Account__r.ParentId, acc);
            accMap.put(lands.Account__c, new Account(Id = lands.Account__c));
        }

        // if(!accMap.isEmpty())
            // update accMap.values();
    }
    public static String getError(Database.SaveResult svList){
        String error = '';
        for(Database.Error err : svList.getErrors()) error += err.getMessage()+'\n';
        return error;
    }

    public static void createListIdToIntegration(List<DelimitedLand__c> delimitedLandList) {
        List<Id> delimitedLandIdSet = new List<Id>();
        for (DelimitedLand__c delimitedLand : delimitedLandList) {
            delimitedLandIdSet.add(delimitedLand.Id);
        }
        sendDelimitedLand(delimitedLandIdSet);
    }

    @future(callout = true)
    public static void sendDelimitedLand(List<Id> context){
        sendDelimitedLandNotFuture(context);
    }

    public static void sendDelimitedLandNotFuture(List<Id> context){
        DelimitedLandIntegration.invocableProcessIntegration(context);
    }

}