force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CreatedDateApp__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateApp__c</fullName>
    <label>Data de Criação App</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Moeda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DeliveryQuantity__c.field-meta.xml
<CustomField>
    <fullName>DeliveryQuantity__c</fullName>
    <label>Quantidade Total de Entrega</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/ExternalIdApp__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdApp__c</fullName>
    <label>Código Externo App</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <label>Modalidade Frete</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>PaymentCondition__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentForm__c.field-meta.xml
<CustomField>
    <fullName>PaymentForm__c</fullName>
    <label>Forma de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>#</fullName>
                <label>Bonificação</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Carteira - Clientes (Dinheiro)</label>
            </value>
            <value>
                <fullName>J</fullName>
                <label>Cheque - Clientes</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Boleto - Clientes</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Cartão de Débito - Clientes</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>Cartão de Crédito - Clientes</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Depósito - Clientes</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Antecipado - Clientes</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Transfêrencia (livre)</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Barter Cliente</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Cessão de Crédito - Cliente</label>
            </value>
            <value>
                <fullName>Z</fullName>
                <label>PIX - Clientes</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Barter Fornecedor</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Transferência - Fornecedor</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Cessão de Crédito - Fornecedor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/RTV__c.field-meta.xml
<CustomField>
    <fullName>RTV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RTVOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingAccount__c.field-meta.xml
<CustomField>
    <fullName>ShippingAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente Entrega</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos (Cliente Entrega)</relationshipLabel>
    <relationshipName>ShippingAccountOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/StatusSF__c.field-meta.xml
<CustomField>
    <fullName>StatusSF__c</fullName>
    <label>Status SF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em digitação</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Retorna RTV</fullName>
            </value>
            <value>
                <fullName>Em aprovação grãos</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/TotalAmountWithFreight__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountWithFreight__c</fullName>
    <label>Valor Total do Pedido</label>
    <summarizedField>OrderItem.TotalPrice__c</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.DeletedSAP__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/BarterSale.recordType-meta.xml
<RecordType>
    <fullName>BarterSale</fullName>
    <active>true</active>
    <description>Indica se o pedido é uma venda de barter</description>
    <label>Negociação Barter</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/ZCCO.recordType-meta.xml
<RecordType>
    <fullName>ZCCO</fullName>
    <active>true</active>
    <label>Contrato Conta e Ordem</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/ZCEF.recordType-meta.xml
<RecordType>
    <fullName>ZCEF</fullName>
    <active>true</active>
    <label>Contrato Venda Futura</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/ZCNO.recordType-meta.xml
<RecordType>
    <fullName>ZCNO</fullName>
    <active>true</active>
    <label>Contrato Venda Moeda</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <label>Modalidade Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sem frete</fullName>
                <default>true</default>
                <label>Sem frete</label>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantidade Total</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PaymentCondition__c/PaymentCondition__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena toda as condições de pagamentos, na fase 01 esse objeto será alimentado através de cargas provenientes do SAP.</description>
    
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome da Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentCondition__c/fields/PaymentForm__c.field-meta.xml
<CustomField>
    <fullName>PaymentForm__c</fullName>
    <label>Formas de Pagamento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>#</fullName>
                <label>Bonificação</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Antecipado - Clientes</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Barter Clientes (nível tesour)</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Boleto - Clientes</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>Cartão de Crédito - Clientes</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Cartão de Débito - Clientes</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Carteira - Clientes (Dinheiro)</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Cessão - Cliente (nível tes)</label>
            </value>
            <value>
                <fullName>J</fullName>
                <label>Cheque - Clientes</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Depósito - Clientes</label>
            </value>
            <value>
                <fullName>Z</fullName>
                <label>PIX - Clientes</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Transfêrencia (livre)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesTeam__c/SalesTeam__c.object-meta.xml
<CustomObject>
    
    <label>Equipe de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes de Vendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <inlineHelpText>Endereço exibido no PDF de pedidos</inlineHelpText>
    <label>Endereço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Cidade exibida no PDF de pedidos</inlineHelpText>
    <label>Cidade</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Equipes de Vendas</relationshipLabel>
    <relationshipName>SalesTeams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>CNPJ exibido no PDF de pedidos</inlineHelpText>
    <label>CNPJ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <inlineHelpText>Nome exibido no PDF de pedidos</inlineHelpText>
    <label>Nome de Exibição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/IE__c.field-meta.xml
<CustomField>
    <fullName>IE__c</fullName>
    <inlineHelpText>Inscrição Estadual exibida no PDF de pedidos</inlineHelpText>
    <label>Inscrição Estadual</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <inlineHelpText>Telefone exibido no PDF de pedidos</inlineHelpText>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <inlineHelpText>CEP exibido no PDF de pedidos</inlineHelpText>
    <label>CEP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Trigo em Grãos</fullName>
    </customValue>
    <customValue>
        <fullName>Sorgo em Grãos</fullName>
    </customValue>
    <customValue>
        <fullName>Milho em Grãos Convencional</fullName>
    </customValue>
    <customValue>
        <fullName>Milho em Grãos Transgênico</fullName>
    </customValue>
    <customValue>
        <fullName>Milho em Grãos Transgênico VTPR04</fullName>
    </customValue>
    <customValue>
        <fullName>Soja em Grãos Convencional</fullName>
    </customValue>
    <customValue>
        <fullName>Soja em Grãos Transgênica</fullName>
    </customValue>
    <customValue>
        <fullName>Algodão em Pluma 31-4-35</fullName>
    </customValue>
    <customValue>
        <fullName>Algodão em Pluma 31-4-36</fullName>
    </customValue>
    <customValue>
        <fullName>Algodão em Pluma 41-4</fullName>
    </customValue>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/OrderPDFController.cls
public with sharing class OrderPDFController {
    
    public OrderData orderData {get;set;}

    public OrderPDFController() {

        String orderIdPageReference = ApexPages.currentPage().getParameters().get('Id');

        List<Order> orderList = OrderDAO.getOrderById(
            new List<String>{orderIdPageReference}, 
            new Set<String>{
                'Id', 'SalesTeam__r.DisplayName__c', 'SalesTeam__r.Address__c', 'SalesTeam__r.City__r.Name', 'SalesTeam__r.CNPJ__c', 'SalesTeam__r.IE__c',
                'SalesTeam__r.Phone__c', 'SalesTeam__r.PostalCode__c', 'StatusSF__c', 'OrderNumber', 'CreatedDate', 'CreatedDateApp__c', 
                'ExternalIdApp__c', 'PaymentDate__c', 'Crop__r.Name', 'EndDate', 'Currency__c', 'TotalAmountWithFreight__c', 
                'PaymentCondition__r.Name', 'toLabel(PaymentForm__c) paymentForm', 'RTV__r.Name', 'RecordType.Name', 'RecordType.DeveloperName', 
                'Freight__c', 'Account.Name', 'Account.CNPJ__c', 'ShippingAccount__r.Name', 'ShippingAccount__r.CPF__c','ShippingAccount__r.CNPJ__c', 
                'ShippingAccount__r.ShippingStreet', 'ShippingAccount__r.ShippingCity', 'ShippingAccount__r.ShippingState', 
                'ShippingAccount__r.StateRegistration__c', 'Commodity__c', 'DeliveryQuantity__c', 'CommercialMeasureUnit__c'
            }
        );

        List<OrderItem> orderItemList = OrderItemDAO.getOrderItemByOrderId(
            new List<String>{orderIdPageReference}, 
            new Set<String>{
                'Id', 'Product2.Name', 'Product2.ProductCode', 'Quantity__c', 'TotalPrice__c', 'Freight__c'
            }
        );
        
        String orderFreight = 'FOB';
        List<OrderItemData> orderItemDataList = new List<OrderItemData>();
        for (OrderItem orderItem : orderItemList) {
            if (orderItem.Freight__c == 'CIF')
                orderFreight = 'CIF';
            orderItemDataList.add(new OrderItemData(orderItem));
        }

        this.orderData = new OrderData(orderList.get(0), orderFreight, orderItemDataList);

    }

    public class OrderData {
        //order data
        public String id                    {get;set;}
        public String salesTeamName         {get;set;}
        public String salesTeamAddress      {get;set;}
        public String salesTeamCity         {get;set;}
        public String salesTeamCNPJ         {get;set;}
        public String salesTeamIE           {get;set;}
        public String salesTeamPhone        {get;set;}
        public String salesTeamPostalCode   {get;set;}
        public String orderName             {get;set;}
        public String orderNumber           {get;set;}
        public String status                {get;set;}
        public String issueDate             {get;set;}
        public String cropName              {get;set;}
        public String expirationDate        {get;set;}
        public String paymentDate           {get;set;}
        public String coin                  {get;set;}
        public String coinUnit              {get;set;}
        public String totalValue            {get;set;}
        public String paymentConditionName  {get;set;}
        public String paymentForm           {get;set;}
        public String rtvName               {get;set;}
        public String orderTypeName         {get;set;}
        public String commodity             {get;set;}

        //billing data
        public String accountName           {get;set;}
    
        //delivery data
        public String accountIE             {get;set;}
        public String freightModality       {get;set;}
        public String accountRegister       {get;set;}
        public String deliveryAddress       {get;set;}
        public String deliveryCity          {get;set;}
        public String deliveryAccountName   {get;set;}
        public String deliveryState         {get;set;}

        public String hideInfoStyleClass    {get;set;}
        public String borderStyleClass      {get;set;}

        //items data
        public List<OrderItemData> orderItemDataList    {get;set;}

        public OrderData(Order order, String orderFreight, List<OrderItemData> orderItemDataList) {
            this.id                     = order.Id;
            this.salesTeamName          = order.SalesTeam__r.DisplayName__c;
            this.salesTeamAddress       = order.SalesTeam__r.Address__c;
            this.salesTeamCity          = order.SalesTeam__r.City__r?.Name;
            this.salesTeamCNPJ          = order.SalesTeam__r.CNPJ__c;
            this.salesTeamIE            = order.SalesTeam__r.IE__c;
            this.salesTeamPhone         = order.SalesTeam__r.Phone__c;
            this.salesTeamPostalCode    = order.SalesTeam__r.PostalCode__c;
            this.orderNumber            = order.OrderNumber;
            this.orderName              = isContract(order.RecordType.DeveloperName) ? 'Contrato' : 'Pedido';
            this.status                 = order.StatusSF__c;
            this.issueDate              = String.isBlank(order.ExternalIdApp__c) || order.CreatedDateApp__c == null ? order.CreatedDate.format('dd/MM/yyyy') : order.CreatedDateApp__c.format();
            this.cropName               = order.Crop__r.Name;
            this.expirationDate         = order.EndDate?.format();
            this.paymentDate            = order.PaymentDate__c?.format();
            this.coin                   = order.Currency__c == 'BRL' ? 'Real' : order.Currency__c == 'USD' ? 'Dolár' : '';
            this.coinUnit               = order.Currency__c == 'BRL' ? 'R$' : order.Currency__c == 'USD' ? 'US$' : '';
            this.totalValue             = convertToBRL(order.TotalAmountWithFreight__c);
            this.paymentConditionName   = order.PaymentCondition__r.Name;
            this.paymentForm            = String.valueof(order.get('paymentForm'));
            this.rtvName                = order.RTV__r.Name;
            this.orderTypeName          = order.RecordType.Name;
            

            this.accountName            = order.Account.Name;

            this.accountIE              = order.ShippingAccount__r.StateRegistration__c;
            this.freightModality        = orderFreight;
            this.accountRegister        = String.isNotBlank(order.ShippingAccount__r.CPF__c) ?  order.ShippingAccount__r.CPF__c : order.ShippingAccount__r.CNPJ__c;
            this.deliveryAddress        = order.ShippingAccount__r.ShippingStreet;
            this.deliveryCity           = order.ShippingAccount__r.ShippingCity;
            this.deliveryAccountName    = order.ShippingAccount__r.Name;
            this.deliveryState          = order.ShippingAccount__r.ShippingState;

            this.orderItemDataList      = orderItemDataList;
            
            
            if (order.RecordType.DeveloperName == 'BarterSale' ) {
                this.commodity          = order.Commodity__c;
                this.coinUnit           = order.CommercialMeasureUnit__c;
                this.totalValue         = convertQtdToBRL(order.DeliveryQuantity__c);
                this.hideInfoStyleClass = '';
                this.borderStyleClass   = '';
            } else {
                this.commodity          = 'Não atribuído';
                this.coinUnit           = order.Currency__c == 'BRL' ? 'R$' : order.Currency__c == 'USD' ? 'US$' : '';
                this.totalValue         = convertToBRL(order.TotalAmountWithFreight__c);
                this.hideInfoStyleClass = 'hide';
                this.borderStyleClass   = 'no-border';
            }
        }
    }

    public class OrderItemData {
        public String productCode          {get;set;}
        public String productDescription   {get;set;}
        public String quantity             {get;set;}
        public String totalPrice           {get;set;}

        public OrderItemData(OrderItem orderItem) {
            this.productCode        = orderItem.Product2.ProductCode;
            this.productDescription = orderItem.Product2.Name;
            this.quantity           = convertQtdToBRL(orderItem.Quantity__c);
            this.totalPrice         = convertToBRL(orderItem.TotalPrice__c);
        }
    }

    public static Boolean isContract(String orderType) {
        Set<String> contractDeveloperNames = new Set<String>{'ZCCO', 'ZCEF', 'ZCNO', 'BarterSale'};
        return contractDeveloperNames.contains(orderType);
    }

    public static String convertToBRL(Decimal num){
        List<String> args = new String[]{'0','number','###.###.##0,00'};
        String numConverted =  String.format(num.setScale(2).format(), args);

        if(numConverted.indexOf(',') == -1){
            numConverted += ',00';
        }
        else if (numConverted.indexOf(',') == numConverted.length() - 2){
            numConverted += '0';
        }
        
        return numConverted;
    } 

    public static String convertQtdToBRL(Decimal num){
        List<String> args = new String[]{'0','number','###.###.##0,000'};
        String numConverted =  String.format(num.setScale(3).format(), args);
        return numConverted;
    } 

    @RemoteAction
    public static void createContentDistribuction(String contentVersionId, String orderId, String fileName) {
        CreateContentDistribution.createContentDistribuction(contentVersionId, orderId, fileName);
    }

    @RemoteAction
    public static String getUserSessionKey() {
        return UserInfo.getSessionId();
    }

}