force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Crop__c/Crop__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Safra provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Safra</label>
    <nameField>
        <label>Nome de Safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crop__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Data de validada final da safra.</description>
    <inlineHelpText>Data de validada final da safra.</inlineHelpText>
    <label>Data final</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Crop__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Código externo, chave primária utilizada pelo SAP para identificar o registro.</description>
    <externalId>true</externalId>
    <inlineHelpText>Código externo, chave primária utilizada pelo SAP para identificar o registro.</inlineHelpText>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Crop__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Data inicial da Safra</description>
    <inlineHelpText>Data inicial da Safra</inlineHelpText>
    <label>Data inicial</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Centros de Distribuição provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome de Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration__c/Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Informações de autenticação da integração com o SAP</description>
    <label>Integration</label>
</CustomObject>

force-app/main/default/objects/Integration__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Campo para desativar integrações</inlineHelpText>
    <label>Desativar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Usuário</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/BarterType__c.field-meta.xml
<CustomField>
    <fullName>BarterType__c</fullName>
    <label>Tipo de Barter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BarterType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/BillingCrop__c.field-meta.xml
<CustomField>
    <fullName>BillingCrop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra de Faturamento do Insumo</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Pedidos (Safra de Faturamento do Insumo)</relationshipLabel>
    <relationshipName>Pedidos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commodity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CommodityProduct2Id__c.field-meta.xml
<CustomField>
    <fullName>CommodityProduct2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Commodity</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>CommodityProduct</relationshipLabel>
    <relationshipName>CommodityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CommodityShipping__c.field-meta.xml
<CustomField>
    <fullName>CommodityShipping__c</fullName>
    <label>Frete Commodity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ContainIntegrationError__c.field-meta.xml
<CustomField>
    <fullName>ContainIntegrationError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contém Erro Integração</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/CreatedDateApp__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateApp__c</fullName>
    <label>Data de Criação App</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Moeda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DeliveryQuantity__c.field-meta.xml
<CustomField>
    <fullName>DeliveryQuantity__c</fullName>
    <label>Quantidade Total de Entrega</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/EndDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>EndDeliveryDate__c</fullName>
    <inlineHelpText>Data de fim da Janela de Entrega.</inlineHelpText>
    <label>Data Fim Entrega Grão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/GrainTableApproval__c.field-meta.xml
<CustomField>
    <fullName>GrainTableApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprovação Mesa de Grãos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/GrossUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>GrossUnitPrice__c</fullName>
    <label>Valor Commodity Bruto</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Incoterms1__c.field-meta.xml
<CustomField>
    <fullName>Incoterms1__c</fullName>
    <label>Incoterms1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/InitialDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>InitialDeliveryDate__c</fullName>
    <inlineHelpText>Data de inicio da Janela de Entrega.</inlineHelpText>
    <label>Data Inicio Entrega Grão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/IntegrationErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>IntegrationErrorMessage__c</fullName>
    <label>Mensagem de Erro Integração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProductionDeliveryLocation__c.field-meta.xml
<CustomField>
    <fullName>ProductionDeliveryLocation__c</fullName>
    <label>Local de Entrega Produção</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProductionPickupLocation__c.field-meta.xml
<CustomField>
    <fullName>ProductionPickupLocation__c</fullName>
    <label>Local de Retirada Produção</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingCrop__c.field-meta.xml
<CustomField>
    <fullName>ShippingCrop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra de Entrega da Commodity</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Pedidos (Safra de Entrega do Grão)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/TotalDeliveryQuantity__c.field-meta.xml
<CustomField>
    <fullName>TotalDeliveryQuantity__c</fullName>
    <formula>TEXT (CEILING(TotalAmount / UnitPrice__c)) &amp;&quot; &quot;&amp;  TEXT (CommercialMeasureUnit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantidade Total de Entrega (INATIVO)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/TradeSlipCode__c.field-meta.xml
<CustomField>
    <fullName>TradeSlipCode__c</fullName>
    <externalId>true</externalId>
    <label>Código da Trade Slip</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Valor Commodity Líquido</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/BarterSale.recordType-meta.xml
<RecordType>
    <fullName>BarterSale</fullName>
    <active>true</active>
    <description>Indica se o pedido é uma venda de barter</description>
    <label>Negociação Barter</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Linha</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Incoterms1__c.field-meta.xml
<CustomField>
    <fullName>Incoterms1__c</fullName>
    <label>Incoterms1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ConvertWeightBags__c.field-meta.xml
<CustomField>
    <fullName>ConvertWeightBags__c</fullName>
    <defaultValue>60</defaultValue>
    <inlineHelpText>Conversão para envio da Commodity de Barter para o SAP</inlineHelpText>
    <label>Conversão (Kg X Sacas)</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/BarterType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ZBPD</fullName>
        <default>true</default>
        <label>Por Dentro</label>
    </customValue>
    <customValue>
        <fullName>ZBPF</fullName>
        <label>Por Fora</label>
    </customValue>
    <customValue>
        <fullName>Triangulação</fullName>
    </customValue>
    <customValue>
        <fullName>Financeiro</fullName>
        <isActive>false</isActive>
        <label>Financeiro</label>
    </customValue>
    <masterLabel>Tipo de Barter</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Commodity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Trigo em Grãos</fullName>
    </customValue>
    <customValue>
        <fullName>Sorgo em Grãos</fullName>
    </customValue>
    <customValue>
        <fullName>Milho em Grãos Convencional</fullName>
    </customValue>
    <customValue>
        <fullName>Milho em Grãos Transgênico</fullName>
    </customValue>
    <customValue>
        <fullName>Milho em Grãos Transgênico VTPR04</fullName>
    </customValue>
    <customValue>
        <fullName>Soja em Grãos Convencional</fullName>
    </customValue>
    <customValue>
        <fullName>Soja em Grãos Transgênica</fullName>
    </customValue>
    <customValue>
        <fullName>Algodão em Pluma 31-4-35</fullName>
    </customValue>
    <customValue>
        <fullName>Algodão em Pluma 31-4-36</fullName>
    </customValue>
    <customValue>
        <fullName>Algodão em Pluma 41-4</fullName>
    </customValue>
    <masterLabel>Commodity</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CalloutGrainPurchaseContract.cls
public without sharing class CalloutGrainPurchaseContract {
    @InvocableMethod
    public static void invocableProcessIntegration(List<Id> listOrderId){
        IntegrationUtils.CalloutResponse calloutResponse = processIntegration(listOrderId);
    }
    
    // CalloutGrainPurchaseContract.processIntegration(new List<Id>{'8015Y000002rPttQAE'});
    public static IntegrationUtils.CalloutResponse processIntegration(List<Id> listOrderId){
        Set<Id> orderItemIdSet = new Set<Id>();
        //HttpResponse response;
		List<Order> parentOrders = [
            SELECT Id, RecordType.DeveloperName, OrderNumber, BarterType__c, ShippingCrop__r.ExternalId__c, Currency__c, DistributionCenter__r.ExternalId__c, EndDate, Incoterms1__c, CommodityProduct2Id__r.ConvertWeightbags__c,  CommodityProduct2Id__r.ExternalId__c, CommodityShipping__c, TotalDeliveryQuantity__c, PaymentDate__c,
            InitialDeliveryDate__c, EndDeliveryDate__c, CreatedDateApp__c, CreatedDate, GrossUnitPrice__c, ProductionPickupLocation__c, ProductionDeliveryLocation__c, UnitPrice__c, Account.ExternalId__c, Commodity__c, ShippingCrop__c, ShippingCrop__r.StartDate__c, ShippingCrop__r.EndDate__c, DeliveryQuantity__c,
            BillingCrop__c, BillingCrop__r.StartDate__c, BillingCrop__r.EndDate__c,
                (
                    SELECT Id, ExternalId__c, Product2.ExternalId__c
                    FROM OrderItems
                )
            FROM Order 
            WHERE Id IN: listOrderId];


		List<Order> allOrders = parentOrders;
		Set<Id> approvedOrderIdsSet = new Set<Id>();

		IntegrationUtils.CalloutResponse calloutResponse = sendOrder(allOrders);
        System.debug('CalloutResponse Results: ' + calloutResponse);
		if (calloutResponse.success) {
			ResponseParameters resp = (ResponseParameters) calloutResponse.parsedResponseGrainPurchaseContract;
            List<ResponseMessageWrapper> respMessageWrapperList = (List<ResponseMessageWrapper>) resp.responses.Mensagens;
            HttpResponse requisitionResponse = (HttpResponse) calloutResponse.requisition;
			Map<String, Order> orderMap = new Map<String, Order>();

			for (Order ord : allOrders) {
				orderMap.put(ord.OrderNumber, ord);
			}

			List<Order> orderList = new List<Order>();
            for(Order ord : allOrders){

                if(requisitionResponse != null){
                    if (requisitionResponse.getStatusCode() != 200) {
                        ord.ContainIntegrationError__c = true;
                        ord.IntegrationErrorMessage__c = requisitionResponse.getStatus();
                    }
                    else{
                        if(resp.responses.NumeroNegociacao != null && resp.responses.NumeroNegociacao != '0000000000'){
                            ord.GrainTableApproval__c = false;
                            approvedOrderIdsSet.add(ord.Id);
                            ord.TradeSlipCode__c = resp.responses.NumeroNegociacao;
                        }
                        ord.ContainIntegrationError__c = false;
                        ord.IntegrationErrorMessage__c = '';
                    }
                }
                else{
                    ord.ContainIntegrationError__c = true;
                    ord.IntegrationErrorMessage__c = calloutResponse.errorMessage;
                }
                if(respMessageWrapperList != null){
                    for(ResponseMessageWrapper respMessageWrapper : respMessageWrapperList){
                        if(respMessageWrapper.Tipo == 'E'){
                            ord.ContainIntegrationError__c = true;
                            ord.IntegrationErrorMessage__c = ord.IntegrationErrorMessage__c + ' | ' + respMessageWrapper.Mensagem;
                        }
                    }
                }
                orderList.add(ord);
            }
            //}

			if (!orderList.isEmpty()) {
                OrderHelper.disableTrigger();
				update orderList;
                OrderHelper.enableTrigger();
			}
            if(!approvedOrderIdsSet.isEmpty()){
                //OrderHelper.disableTrigger();
                CreateOrderController.callApprovalProcess(approvedOrderIdsSet);
                //OrderHelper.enableTrigger();
            }
		}
		else{
            System.debug('DEU ERRO - SUCCESS FALSE');
            
            HttpResponse requisitionResponse = (HttpResponse) calloutResponse.requisition;

            Map<String, Order> orderMap = new Map<String, Order>();
            List<Order> orderList = new List<Order>();	

            for(Order ord : allOrders){
                if(requisitionResponse != null){
                    if (requisitionResponse.getStatusCode() != 200) {
                        ord.ContainIntegrationError__c = true;
                        ord.IntegrationErrorMessage__c = requisitionResponse.getStatus();
                    }
                    else{
                        ord.ContainIntegrationError__c = true;
                        ord.IntegrationErrorMessage__c = calloutResponse.errorMessage;
                    }
                }
                else{
                    ord.ContainIntegrationError__c = true;
                    ord.IntegrationErrorMessage__c = calloutResponse.errorMessage;
                }
				orderList.add(ord);
            }

            if (!orderList.isEmpty()) {
                OrderHelper.disableTrigger();
				update orderList;
                OrderHelper.enableTrigger();
			}
        }
		return calloutResponse;
	}

	public static IntegrationUtils.CalloutResponse sendOrder(List<Order> orders) {

		List<RequestParameters> request = new List<RequestParameters>();

        String payload;
        
        Map<String,Integration__c> integrations = Integration__c.getAll();
        System.debug('integrations: ' + integrations);
        String integrationMethod = integrations.get('IntegrationGrainPurchaseContract').Method__c;
        String integrationEndPoint = integrations.get('IntegrationGrainPurchaseContract').Endpoint__c;
        String integrationUser = integrations.get('IntegrationGrainPurchaseContract').Username__c;
        String integrationPassword = integrations.get('IntegrationGrainPurchaseContract').Password__c;

		for (Order ord : orders) {
			request.add(new RequestParameters(ord));
            payload = JSON.serialize(new RequestParameters(ord));
		}

		if(integrations.get('IntegrationGrainPurchaseContract').Inactive__c){
            IntegrationUtils.updateErrorOrder(orders);
			IntegrationLog.createIntegrationLog('Order Outbound Integration', 'Outbound', Label.InactiveIntegration, payload, true);
			return new IntegrationUtils.CalloutResponse(Label.InactiveIntegration, null);
		}

		//String payload = JSON.serialize(new Request(request));
        // -> DEU CERTO PARCIALMENTE String payload = JSON.serialize(request);
        Blob headerValue = Blob.valueOf(integrationUser + ':' + integrationPassword);

		//Metodo para busca de Access Token, depende de cada projeto, podendo estar presente dentro de uma custom settings ou relacionado com outra requisição.
		
        //String accessToken = 'Basic Uy1JRlNGT1JDRTpjNHEkNkQlL1QjQTZZOHVhR2Q0TGNBO0JJXC1cJ3NeYA==';
        String accessToken = 'Basic ' + EncodingUtil.base64Encode(headerValue);
		
		//Path geralmente cadastrado dentro de ua customSettings
		String endpoint = (!Test.isRunningTest() ? integrationEndPoint : 'http://callout.My_Named_Credential.com/some/path');
		Map<String, String> headersMap = new Map<String, String>();
		headersMap.put('Content-type', 'application/json');
		headersMap.put('Authorization', accessToken);
		
		IntegrationUtils.RequestResponseObject responseObject = IntegrationUtils.executeCallout(endpoint, payload, headersMap, integrationMethod);
        System.debug('response Objecto: ' + responseObject);
        HttpResponse response = responseObject.response;
		if (responseObject.success) {
            System.debug('RESPONSESENDORDER: ' + responseObject);
			IntegrationLog.createIntegrationLog('Order Grain Purchase Contract Outbound Integration', 'Outbound', response.getBody(), payload, false);
            System.debug('Response Try: ' + response);
            System.debug('Response getBody Try: ' + response.getBody());

			try {
				ResponseParametersWrapper responses = (ResponseParametersWrapper) JSON.deserialize(response.getBody(), ResponseParametersWrapper.class);
                System.debug('Responses do Try: ' + responses);
				return new IntegrationUtils.CalloutResponse(new ResponseParameters(responses), response);
			} catch (Exception e) {
				
				String defaultErrorMessage = 'Malformatted HTTP Response Exception: ' + e.getMessage();

				return new IntegrationUtils.CalloutResponse(defaultErrorMessage, response);
			}
		} else {
			IntegrationLog.createIntegrationLog('Order Outbound Integration', 'Outbound', responseObject.exceptionObject.getMessage(), payload, true);
			return new IntegrationUtils.CalloutResponse(responseObject.exceptionObject.getMessage(), response);
		}
	}

    public class Request {
        public List<RequestParameters> request;
        public Request(List<RequestParameters> request) {
            this.request = request;
        }
    }

	public class RequestParameters {
		//Order Fields
		//Example
		public String CodigoSalesforce;
        public String TipoDocumento;
        public String TipoContrato;
        public String Moeda;
        public String Centro;
        public Date DataEntrega;
        public String Incoterms1;
        public String Quantidade;
        public Date DataPagamento;
        public String AnoSafra;
        public Date DataNegociacao;
        public Double PrecoFechado;
        public String Parceiro;
        public String ProdutoAgricola;

        public Double PrecoUnitario;
        public Date DataInicioEntrega;
        public Date DataFimEntrega;
        public String LocalRetirada;

        String Material;

		public RequestParameters(Order ord) {

			this.CodigoSalesforce = ord.OrderNumber;
            //this.TipoDocumento = ord.RecordType.DeveloperName;
            if(ord.RecordType.DeveloperName != 'BarterSale'){
                this.TipoDocumento = 'ZVNO';
            }
            else{
                this.TipoDocumento = 'ZBPD';
            }
            this.TipoContrato = ord.BarterType__c;
            this.Moeda = ord.Currency__c;
            this.Centro = ord.DistributionCenter__r.ExternalId__c;
            this.DataEntrega = ord.EndDate;
            this.Incoterms1 = ord.CommodityShipping__c;
            this.Quantidade = String.valueof(ord.DeliveryQuantity__c * (ord.CommodityProduct2Id__r.ConvertWeightbags__c == null ? 60 : ord.CommodityProduct2Id__r.ConvertWeightbags__c));
            this.DataPagamento = Date.valueOf(ord.PaymentDate__c);
            this.AnoSafra = getCorrectCrop(ord.ShippingCrop__r.ExternalId__c);
            if(ord.CreatedDateApp__c != null){
                this.DataNegociacao = ord.CreatedDateApp__c;
            }
            else{
                this.DataNegociacao = ord.CreatedDate.date();
            }
            this.PrecoFechado = ord.GrossUnitPrice__c;
            this.PrecoUnitario = ord.UnitPrice__c;
            this.DataInicioEntrega = ord.InitialDeliveryDate__c;
            this.DataFimEntrega = ord.EndDeliveryDate__c;


            if(ord.CommodityShipping__c == 'CIF' || ord.CommodityShipping__c == 'FCA'){
                this.LocalRetirada = ord.ProductionDeliveryLocation__c;    
            }
            else{
                this.LocalRetirada = ord.ProductionPickupLocation__c;
            }

            this.Parceiro = ord.Account.ExternalId__c;
            this.ProdutoAgricola = ord.CommodityProduct2Id__r.ExternalId__c;
            
            for(OrderItem ordIt : ord.OrderItems){
                this.Material = ordIt.Product2.ExternalId__c;
            }
		}
        public string getCorrectCrop(String crop){
            return crop == null ? null : '20'+crop.split('/')[0]+'/'+'20'+crop.split('/')[1]; 
        }
	}

	public class ResponseParameters {
		public ResponseParametersWrapper responses;
        
		public ResponseParameters(ResponseParametersWrapper responses) {
			this.responses = responses;
		}
	}

	public class ResponseParametersWrapper {
        public String CodigoSalesforce;
        public String NumeroNegociacao;
        public List<ResponseMessageWrapper> Mensagens;
	}

    public class ResponseMessageWrapper {
        public String Tipo;
        public String Mensagem;
    }
}