force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/fields/GGN__c.field-meta.xml
<CustomField>
    <fullName>GGN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Gerente Geral de Negócios</inlineHelpText>
    <label>GGN</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesOffices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesOfficeDAO.cls
public with sharing class SalesOfficeDAO {
    
    public static List<SalesOffice__c> getSalesOfficeByExternalId(List<String> externalIds, Set<String> salesOfficeUsedFields) {

        String query = new Q(SalesOffice__c.SObjectType)
            .selectFields(salesOfficeUsedFields)
            .add(Q.condition('ExternalId__c').isIn(externalIds))
            .build();
            
        return Database.query(query);
    }

    public static List<SalesOffice__c> getSalesOfficeByGGN(List<String> gnns, Set<String> salesOfficeUsedFields) {

        String query = new Q(SalesOffice__c.SObjectType)
            .selectFields(salesOfficeUsedFields)
            .add(Q.condition('GGN__c').isIn(gnns))
            .build();
            
        return Database.query(query);
    }

}