force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    
    <label>Família de Produto</label>
    <nameField>
        <label>Nome de Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Família de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RangeDiscount__c/RangeDiscount__c.object-meta.xml
<CustomObject>
    
    <label>Desconto de Banda</label>
    <nameField>
        <displayFormat>DESC-{0000}</displayFormat>
        <label>Desconto de Banda</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Descontos de Banda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RangeDiscount__c/fields/CustomerCategory__c.field-meta.xml
<CustomField>
    <fullName>CustomerCategory__c</fullName>
    <label>Categoria do Cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Descontos de Banda</relationshipLabel>
    <relationshipName>RangeDiscounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Indica se o tipo de pagamento será a vista ou a prazo.</description>
    <inlineHelpText>Indica se o tipo de pagamento será a vista ou a prazo.</inlineHelpText>
    <label>Tipo de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTypeGlobalList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Descontos de Banda</relationshipLabel>
    <relationshipName>RangeDiscounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/PaymentTypeGlobalList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PresentPayment</fullName>
        <default>true</default>
        <label>A vista</label>
    </customValue>
    <customValue>
        <fullName>FuturePayment</fullName>
        <label>A prazo</label>
    </customValue>
    <masterLabel>Lista global de tipos de pagamentos</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RangeDiscountDAO.cls
public with sharing class RangeDiscountDAO {
    
    public static List<RangeDiscount__c> getRangeDiscountByAllInfos(List<String> customerCategorys, List<String> salesOffices, List<String> paymentTypes, List<String> familys, Set<String> rangeDiscountUsedFields) {

        String query = new Q(RangeDiscount__c.SObjectType)
            .selectFields(rangeDiscountUsedFields)
            .add(Q.condition('CustomerCategory__c').isIn(customerCategorys))
            .add(Q.condition('SalesOffice__c').isIn(salesOffices))
            .add(Q.condition('PaymentType__c').isIn(paymentTypes))
            .add(Q.condition('Family__c').isIn(familys))
            .add(Q.condition('Status__c').equalsTo('Aprovado'))
            .build();
            
        return Database.query(query);
    }

}