force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    
    <label>Família de Produto</label>
    <nameField>
        <label>Nome de Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Família de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena o custo de frete por tonelada considerando a cidade origem e a cidade destino.</description>
    
    <label>Frete</label>
    <nameField>
        <displayFormat>FRT-{0000}</displayFormat>
        <label>Nome do Frete</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight__c/fields/DestinationCity__c.field-meta.xml
<CustomField>
    <fullName>DestinationCity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cidade Destino</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Fretes (Cidade Destino)</relationshipLabel>
    <relationshipName>DestinationFreights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data de Termino</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Freight__c/fields/ExternalIDIndex__c.field-meta.xml
<CustomField>
    <fullName>ExternalIDIndex__c</fullName>
    <externalId>true</externalId>
    <label>External ID Index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Formula que verifica a maior especificidade para atribuir o grau de especificidade do registro.</description>
    <formula> IF(NOT(IsBlank(Product2Id__c)), 10, 0) + IF(NOT(IsBlank(Family__c)), 1,  0) </formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula que verifica a maior especificidade para atribuir o grau de especificidade do registro.</inlineHelpText>
    <label>Prioridade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/SourceCity__c.field-meta.xml
<CustomField>
    <fullName>SourceCity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cidade de Origem</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Fretes (Cidade de Origem)</relationshipLabel>
    <relationshipName>SourceFreights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data de Inicio</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/ValuePerTon__c.field-meta.xml
<CustomField>
    <fullName>ValuePerTon__c</fullName>
    <label>Valor por Tonelada em R$ BRL</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/ValuePerTonDolar__c.field-meta.xml
<CustomField>
    <fullName>ValuePerTonDolar__c</fullName>
    <label>Valor por Tonelada em $ USD</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <label>Modalidade Frete</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Product2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetFreigthController.cls
public class GetFreigthController {
    @AuraEnabled(cacheable=true)
    public static SObject getFreigth(String destinationCityId, String sourceCityId, String product2Id) {
        if(String.isNotBlank(destinationCityId) && String.isNotBlank(sourceCityId) && String.isNotBlank(product2Id)) {
            try {
                System.debug('TA DENTRO DO GET FREIGH, METODO DO APEX');
                Product2 prod = [SELECT id, Family__c FROM Product2 WHERE ID = :product2Id];
                SObject record = [SELECT 
                Id, 
                OwnerId, IsDeleted, 
                Name, CreatedDate, 
                CreatedById, LastModifiedDate, 
                LastModifiedById, SystemModstamp, 
                LastActivityDate, LastViewedDate, 
                LastReferencedDate, DestinationCity__c, 
                EndDate__c, ExternalIDIndex__c, 
                ExternalId__c, IsActive__c, 
                Product2Id__c, SourceCity__c,
                StartDate__c, ValuePerTonDolar__c,
                ValuePerTon__c 
                FROM Freight__c 
                WHERE IsActive__c = true AND DestinationCity__c =: destinationCityId AND SourceCity__c =: sourceCityId AND (Product2Id__c =: product2Id OR Family__c = :prod.Family__c) ORDER BY Priority__c DESC LIMIT 1];
                return record;
            } catch(Exception e) {
                return NULL;
            }
        }
        else {
            return NULL;
        }
    }
}