force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    
    <label>Família de Produto</label>
    <nameField>
        <label>Nome de Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Família de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FamilyDAO.cls
public with sharing class FamilyDAO {
    
    public static List<Family__c> getFamilyByExternalId(List<String> externalIds, Set<String> familyUsedFields) {

        String query = new Q(Family__c.SObjectType)
            .selectFields(familyUsedFields)
            .add(Q.condition('ExternalId__c').isIn(externalIds))
            .build();
            
        return Database.query(query);
    }


}