force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    
    <label>Família de Produto</label>
    <nameField>
        <label>Nome de Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Família de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena o custo de frete por tonelada considerando a cidade origem e a cidade destino.</description>
    
    <label>Frete</label>
    <nameField>
        <displayFormat>FRT-{0000}</displayFormat>
        <label>Nome do Frete</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight__c/fields/DestinationCity__c.field-meta.xml
<CustomField>
    <fullName>DestinationCity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cidade Destino</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Fretes (Cidade Destino)</relationshipLabel>
    <relationshipName>DestinationFreights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/SourceCity__c.field-meta.xml
<CustomField>
    <fullName>SourceCity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cidade de Origem</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Fretes (Cidade de Origem)</relationshipLabel>
    <relationshipName>SourceFreights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PricingParamExternalKeyMapper.cls
public with sharing class PricingParamExternalKeyMapper {
    private static Map<String, Set<String>> tableToKeyFields;
    static {
        tableToKeyFields = new Map<String, Set<String>>{
            'Freight__c'             => new Set<String>{ 'DestinationCity__c', 'SourceCity__c', 'Product2Id__c', 'Family__c' }
        };       
    }

    public static void mapRecords(SObject[] records, SObjectType sobjectType){
        PricingParamValidator.assignExternalId(records, tableToKeyFields.get(sobjectType.getDescribe().getName()));
    }
}