force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    
    <label>Cluster</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    
    <label>Família de Produto</label>
    <nameField>
        <label>Nome de Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Família de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ListPrice__c/ListPrice__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena dos dados do catalogo de preço, esse objeto será alimentado através de integração com o SAP, o SAP irá manipular os registros através da API padrão do  salesforce.</description>
    
    <label>Catálogo de preço</label>
    <nameField>
        <displayFormat>CAT-{0000}</displayFormat>
        <label>Nome do Catalogo de preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Catalogos de preço</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ListPrice__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Valor utilizado durante o calculo de margem do produto do pedido.</inlineHelpText>
    <label>Custo</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <description>Data efetiva do catalogo de preços, recebe o valor do campo KONP - VALDT no SAP.</description>
    <inlineHelpText>Data efetiva do catalogo de preços, recebe o valor do campo KONP - VALDT no SAP.</inlineHelpText>
    <label>Data Efetiva</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Família de produto do catalogo de preço, referente ao campo XXXX - XXXX no SAP.</description>
    <inlineHelpText>Família de produto do catalogo de preço, referente ao campo XXXX - XXXX no SAP.</inlineHelpText>
    <label>Família de Produtos</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Catalogos de preço</relationshipLabel>
    <relationshipName>ListPrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo que armazena o escritório de vendas, referente ao campo VBAK - VKBUR no SAP.</description>
    <inlineHelpText>Campo que armazena o escritório de vendas, referente ao campo VBAK - VKBUR no SAP.</inlineHelpText>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Catalogos de preço</relationshipLabel>
    <relationshipName>ListPrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <description>Valor unitário do produto, referente ao campo KONP - KBETR no SAP.</description>
    <inlineHelpText>Valor unitário do produto, referente ao campo KONP - KBETR no SAP.</inlineHelpText>
    <label>Valor</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DirectMargin__c.field-meta.xml
<CustomField>
    <fullName>DirectMargin__c</fullName>
    <inlineHelpText>Margem Direta é considerada a Margem Recomposta e as Campanhas, tanto da indústria quanto ForcaAgro, para formar o valor final previsto de cada negociação.

Cálculo: Preço Unitário - Custo / Preço Unitário</inlineHelpText>
    <label>Margem Direta</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/HasOrderItemWithLowerMargin__c.field-meta.xml
<CustomField>
    <fullName>HasOrderItemWithLowerMargin__c</fullName>
    <formula>OrderItemWithoutLowerMargin__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contem Produtos com margem abaixo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/HasOrderItemWithoutCost__c.field-meta.xml
<CustomField>
    <fullName>HasOrderItemWithoutCost__c</fullName>
    <formula>OrderItemWithoutCost__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contem produtos sem Custo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/HasOrderItemWithoutMargin__c.field-meta.xml
<CustomField>
    <fullName>HasOrderItemWithoutMargin__c</fullName>
    <formula>OrderItemWithoutMargin__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contem produtos sem margem cadastrada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <inlineHelpText>Margem recomposta é calculada com base no valor comercial do produto, já considerando juros/antecipação e desconto comercial, comparando com o custo projetado(ZPRS).

Cálculo: Preço Unitário Sem Campanha - Custo / Preço Unitário Sem Campanha</inlineHelpText>
    <label>Margem Recomposta</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarginApprovalNote__c.field-meta.xml
<CustomField>
    <fullName>MarginApprovalNote__c</fullName>
    <label>Observação da Margem</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarginApprover__c.field-meta.xml
<CustomField>
    <fullName>MarginApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aprovador Margem</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pedidos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Valor Commodity Líquido</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Custo</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CustomListPrice__c.field-meta.xml
<CustomField>
    <fullName>CustomListPrice__c</fullName>
    <label>Preço de Lista</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DirectFamilyMargin__c.field-meta.xml
<CustomField>
    <fullName>DirectFamilyMargin__c</fullName>
    <label>Margem Direta da Familia</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DirectMargin__c.field-meta.xml
<CustomField>
    <fullName>DirectMargin__c</fullName>
    <label>Margem Direta do Produto</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <label>Valor Desconto</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <label>Percentual de desconto</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FamilyMargin__c.field-meta.xml
<CustomField>
    <fullName>FamilyMargin__c</fullName>
    <label>Margem Recomposta da Familia</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/InvalidCost__c.field-meta.xml
<CustomField>
    <fullName>InvalidCost__c</fullName>
    <formula>Cost__c = 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Custo Invalido?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ListPrice__c.field-meta.xml
<CustomField>
    <fullName>ListPrice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Catálogo de preço</label>
    <referenceTo>ListPrice__c</referenceTo>
    <relationshipLabel>Produtos do pedido</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LowerMargin__c.field-meta.xml
<CustomField>
    <fullName>LowerMargin__c</fullName>
    <formula>DirectFamilyMargin__c &lt; ProjectedMargin__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Abaixo da margem Projetada?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margem Recomposta do Produto</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <formula>CASESAFEID(Product2.Family__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Familia do produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ProductFamilyName__c.field-meta.xml
<CustomField>
    <fullName>ProductFamilyName__c</fullName>
    <formula>Product2.Family__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome da Familia do produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ProjectedMargin__c.field-meta.xml
<CustomField>
    <fullName>ProjectedMargin__c</fullName>
    <label>Margem Projetada</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantidade Total</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <description>Campo de preço total que utiliza a seguinte fórmula : Preço unitário * Quantidade total.</description>
    <formula>(UnitPrice *  Quantity__c) +  FreightValue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Campo de preço total que utiliza a seguinte fórmula : Preço unitário * Quantidade total.</inlineHelpText>
    <label>Preço total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/UnitMeasure__c.field-meta.xml
<CustomField>
    <fullName>UnitMeasure__c</fullName>
    <label>Unidade de Medida</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/UnitPriceWithoutCampaign__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceWithoutCampaign__c</fullName>
    <formula>UnitPrice * (1+(CampaignPercent__c/100)) </formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preço Unitario Sem Campanha</label>
    <precision>10</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Product2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectedMargin__c/ProjectedMargin__c.object-meta.xml
<CustomObject>
    
    <label>Margem Projetada</label>
    <nameField>
        <displayFormat>Margem-{0000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margem Projetada</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectedMargin__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipName>Margem_Projetado</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectedMargin__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margem</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Escritórios de Vendas</relationshipLabel>
    <relationshipName>SalesOffices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/fields/SalesDirector__c.field-meta.xml
<CustomField>
    <fullName>SalesDirector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo opcional de diretor para o escritorio de vendas</description>
    <label>Diretor de vendas</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Escrit_rios_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderItemHelper.cls
public with sharing class OrderItemHelper {
    private static Boolean runTrigger = true;

    public static Boolean isTriggerEnabled(){
        return runTrigger;
    }

    public static Boolean enableTrigger(){
        return runTrigger = true;
    }

    public static Boolean disableTrigger(){
        return runTrigger = false;
    }   
    
    public static void setMargin(List<OrderItem> newItems){
        for(OrderItem curOrderItem: newItems){
            curOrderItem.DirectMargin__c = calcMarginProduct(curOrderItem.UnitPrice, curOrderItem.Cost__c);
            curOrderItem.Margin__c = calcMarginProduct(curOrderItem.UnitPriceWithoutCampaign__c, curOrderItem.Cost__c);
        }
    }
    public static Decimal calcMarginProduct(Decimal unitVal, Decimal costs){
        if(unitVal != null && unitVal != 0 && costs != null)
            return ((unitVal - costs) / unitVal *100).setScale(4, RoundingMode.HALF_UP);
        else
            return null;
    }
    public static void calcMargem(List<OrderItem> newItems){
        Set<Id> ordIdSet =new Set<Id>();
        for(OrderItem ordItem: newItems){
            if(Approval.isLocked(ordItem.OrderId)) continue;
            ordIdSet.add(ordItem.OrderId);
        }

        if(ordIdSet.isEmpty()) return;
        
        Map<String, List<OrderItem>> ordItemMap = new Map<String, List<OrderItem>>();
        Map<Id, Order> orderMap = new Map<Id, Order>();
        for(OrderItem ordItem : [SELECT id, OrderId, Order.SalesOffice__r.ParentId__r.MarketingManager__c, Order.SalesOffice__r.SalesDirector__c, Order.SalesOffice__r.ParentId__r.Director__c, ProductFamily__c, DirectMargin__c, Margin__c,
                                Order.HasOrderItemWithoutMargin__c, Order.HasOrderItemWithoutCost__c, Order.HasOrderItemWithLowerMargin__c, Order.MarginApprovalNote__c,
                                Product2Id, Product2.Name, Product2.Family__c, ProductFamilyName__c,
                                InvalidCost__c, Cost__c,
                                Product2.Family__r.Name, ListPrice__c,DiscountAmount__c, 
                                ListPrice__r.UnitPrice__c, ListPrice__r.EffectiveDate__c,
                                LowerMargin__c,DirectFamilyMargin__c, FamilyMargin__c, ProjectedMargin__c,
                                DiscountPercent__c, TotalPrice__c, UnitMeasure__c, Quantity__c, CustomListPrice__c
                                FROM OrderItem WHERE OrderId IN :ordIdSet]){
            if(!ordItemMap.containsKey(ordItem.OrderId))
                ordItemMap.put(ordItem.OrderId, new List<OrderItem>());
            ordItemMap.get(ordItem.OrderId).add(ordItem);

            orderMap.put(ordItem.OrderId, ordItem.Order);
        }   

        List<Order> ordListUpdate = new List<Order>();
        List<OrderItem> ordItemListUpdate = new List<OrderItem>();
        for(Id ordId : ordItemMap.keySet()){
            Order ord = new Order(Id = ordId);
            
            Map<String, List<Decimal>> ordItemDirectFamMap = new Map<String, List<Decimal>>();
            Map<String, List<Decimal>> ordItemMarginFamMap = new Map<String, List<Decimal>>();

            Map<String, List<Decimal>> ordItemDirectMap = new Map<String, List<Decimal>>();
            Map<String, List<Decimal>> ordItemMarginMap = new Map<String, List<Decimal>>();

            for(OrderItem ordItem : ordItemMap.get(ordId)){
                ordItem.DirectFamilyMargin__c   = averageMargin(ordItem.ProductFamily__c, ordItem.DirectMargin__c,  ordItemDirectFamMap);
                ordItem.FamilyMargin__c         = averageMargin(ordItem.ProductFamily__c, ordItem.Margin__c,        ordItemMarginFamMap);
                ord.DirectMargin__c             = averageMargin(ordId,                    ordItem.DirectMargin__c,  ordItemDirectMap);
                ord.Margin__c                   = averageMargin(ordId,                    ordItem.Margin__c,        ordItemMarginMap);
            }
            ordItemListUpdate.addAll(ordItemMap.get(ordId));
            ordListUpdate.add(ord);

        }
        
        OrderHelper.setApprovalJustification(orderMap, ordItemMap);

        if (!ordItemListUpdate.isEmpty()){
            OrderItemHelper.disableTrigger();
            OrderHelper.disableTrigger();
            update ordItemListUpdate;
            update ordListUpdate;
            OrderItemHelper.enableTrigger();
            OrderHelper.enableTrigger();
        }
 
        //Inactive Margin
        /*
        List<Order> ordUpdate = new List<Order>();
        for(Order ord : [SELECT id,HasOrderItemWithoutMargin__c, HasOrderItemWithoutCost__c, HasOrderItemWithLowerMargin__c, SalesOffice__r.ParentId__r.MarketingManager__c,SalesOffice__r.SalesDirector__c,SalesOffice__r.ParentId__r.Director__c 
                        FROM Order 
                        WHERE Id IN :ordIdSet]){
            if(ord.HasOrderItemWithoutMargin__c || ord.HasOrderItemWithoutCost__c || ord.HasOrderItemWithLowerMargin__c){
                if(ord.HasOrderItemWithoutMargin__c || ord.HasOrderItemWithoutCost__c)
                    ord.MarginApprover__C = ord.SalesOffice__r.ParentId__r.MarketingManager__c;
                else
                    ord.MarginApprover__C = ord.SalesOffice__r.SalesDirector__c != null ? ord.SalesOffice__r.SalesDirector__c : ord.SalesOffice__r.ParentId__r.Director__c;
            }
            ordUpdate.add(ord);
        }
        if (!ordUpdate.isEmpty()){
            OrderItemHelper.disableTrigger();
            OrderHelper.disableTrigger();
            update ordUpdate;
            OrderItemHelper.enableTrigger();
            OrderHelper.enableTrigger();
        }
        */
    }

    public static void inputMap(String key, Decimal val, Map<String, List<Decimal>> ordMap){
        if(!ordMap.containsKey(key)) 
            ordMap.put(key, new List<Decimal>());
        ordMap.get(key).add(val);
    }

    public static Decimal averageMargin(String key, Decimal val, Map<String, List<Decimal>> ordMap){
        inputMap(key, val, ordMap);
        return ordMap.containsKey(key) ? new DecimalCollection(ordMap.get(key)).average(4, RoundingMode.HALF_UP) : null;
    }

    /*public static void calcMargem(List<OrderItem> newItems){
        Map<Id, Order> orders =new Map<Id, Order>();
        for(OrderItem curOrderItem: newItems){
            if(Approval.isLocked(curOrderItem.OrderId)) continue;
            orders.put(curOrderItem.OrderId, null);
        }

        orders =new Map<Id, Order>([SELECT
            Id, DirectMargin__c
            FROM Order
            WHERE Id in :orders.keySet()
        ]);
        newItems =[
            SELECT Id, Product2Id, OrderId, DirectMargin__c, DirectFamilyMargin__c, ProductFamily__c
            FROM OrderItem
            WHERE OrderId in :orders.keySet()
        ];        
        Map<Id, Map<Id, List<OrderItem>>> orderFamilyItem =new Map<Id, Map<Id, List<OrderItem>>>();
        for(OrderItem curOrderItem: newItems){
            if(Approval.isLocked(curOrderItem.OrderId)) continue;
            Map<Id, List<OrderItem>> familyItems =orderFamilyItem.get(curOrderItem.OrderId);
            if (familyItems==null){
                familyItems =new Map<Id, List<OrderItem>>();
                List<OrderItem> newList =new List<OrderItem>();
                newList.add(curOrderItem);
                familyItems.put(curOrderItem.ProductFamily__c, newList);
                orderFamilyItem.put(curOrderItem.OrderId, familyItems);
                continue;
            }
            List<OrderItem> items =familyItems.get(curOrderItem.ProductFamily__c);
            if (items==null){
                items =new List<OrderItem>();
                items.add(curOrderItem);
                familyItems.put(curOrderItem.ProductFamily__c, items);
                continue;
            }
            items.add(curOrderItem);
        }

        Map<Id, Map<Id, Decimal>> orderFamilyFmargin =new Map<Id, Map<Id, Decimal>>();
        List<Order> ordersToUpdate =new List<Order>();
        for(Id orderId: orderFamilyItem.keySet()){
            Integer orderQtd =0;
            Decimal orderSum =0;
            Map<Id, List<OrderItem>> curFamilyMap =orderFamilyItem.get(orderId);
            for(Id familyId: curFamilyMap.keySet()){                
                List<OrderItem> curOrderList =curFamilyMap.get(familyId);
                Integer qtd =0;
                Decimal sum =0;
                for(OrderItem curOrderItem: curOrderList){
                    if (curOrderItem.DirectMargin__c !=null){
                        qtd++;
                        orderQtd++;
                        orderSum = orderSum+curOrderItem.DirectMargin__c;
                        sum =sum +curOrderItem.DirectMargin__c;
                    }
                }
                Decimal toFamilyMargin =null;
                if (qtd>0){
                    toFamilyMargin =sum/qtd;
                    toFamilyMargin =toFamilyMargin.setScale(4, RoundingMode.HALF_UP);
                }
                Map<Id, Decimal> newFamilyMargMap =orderFamilyFmargin.get(orderId);
                if (newFamilyMargMap==null){
                    newFamilyMargMap =new Map<Id, Decimal>();
                    orderFamilyFmargin.put(orderId, newFamilyMargMap);
                }
                newFamilyMargMap.put(familyId, toFamilyMargin);
            }
            Order curOrder =orders.get(orderId);
            Decimal toOrderDirectMargin =null;
            if (orderQtd>0){
                toOrderDirectMargin =orderSum/orderQtd;
                toOrderDirectMargin =toOrderDirectMargin.setScale(4, RoundingMode.HALF_UP);
            }
            if (curOrder.DirectMargin__c!=toOrderDirectMargin){
                curOrder.DirectMargin__c =toOrderDirectMargin;
                ordersToUpdate.add(curOrder);
            }            
        }
        List<OrderItem> toUpdate =new List<OrderItem>();
        for(OrderItem curOrderItem: newItems){
            if(Approval.isLocked(curOrderItem.OrderId)) continue;
            Map<Id, Decimal> familyMargMap =orderFamilyFmargin.get(curOrderItem.OrderId);     
            if (familyMargMap ==null){
                System.debug('calcMargem Error: have not found familyMargMap');
                curOrderItem.DirectFamilyMargin__c =null;
                continue;
            }
            Decimal famMargin =familyMargMap.get(curOrderItem.ProductFamily__c);            
            if (curOrderItem.DirectFamilyMargin__c!=famMargin){
                curOrderItem.DirectFamilyMargin__c =famMargin;
                toUpdate.add(curOrderItem);
            }
        }
        if (!toUpdate.isEmpty()){
            OrderItemHelper.disableTrigger();
            update toUpdate;
            OrderItemHelper.enableTrigger();
        }
        if (!ordersToUpdate.isEmpty()){
            OrderHelper.disableTrigger();
            update ordersToUpdate;
            OrderHelper.enableTrigger();
        }
        
        // Realizar um select nos produtos dos pedidos de todos os pedidos,
        // agrupando pela seguinte chave:
        // OrderId + Id da Familia do produto.        
    }*/

}