force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    
    <label>Cluster</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    
    <label>Família de Produto</label>
    <nameField>
        <label>Nome de Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Família de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/RangeDiscount__c.object-meta.xml
<CustomObject>
    
    <label>Desconto de Banda</label>
    <nameField>
        <displayFormat>DESC-{0000}</displayFormat>
        <label>Desconto de Banda</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Descontos de Banda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RangeDiscount__c/fields/ApprovingAuthority__c.field-meta.xml
<CustomField>
    <fullName>ApprovingAuthority__c</fullName>
    <label>Alçada Aprovadora</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ClusterDirector</fullName>
                <label>Diretor do Cluster</label>
            </value>
            <value>
                <fullName>InvesteeDirector</fullName>
                <label>Diretor da Investida</label>
            </value>
            <value>
                <fullName>GGN</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
                <label>Gerente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/ClusterExternalId__c.field-meta.xml
<CustomField>
    <fullName>ClusterExternalId__c</fullName>
    <description>Campo utilizado para filtrar a politica comercial, filtrando por cluster os registros de desconto de banda.</description>
    <inlineHelpText>Campo utilizado para filtrar a politica comercial, filtrando por cluster os registros de desconto de banda.</inlineHelpText>
    <label>Chave do Cluster</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/CustomerCategory__c.field-meta.xml
<CustomField>
    <fullName>CustomerCategory__c</fullName>
    <label>Categoria do Cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Descontos de Banda</relationshipLabel>
    <relationshipName>RangeDiscounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/FinalDate__c.field-meta.xml
<CustomField>
    <fullName>FinalDate__c</fullName>
    <label>Data Final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Indica se o tipo de pagamento será a vista ou a prazo.</description>
    <inlineHelpText>Indica se o tipo de pagamento será a vista ou a prazo.</inlineHelpText>
    <label>Tipo de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTypeGlobalList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Descontos de Banda</relationshipLabel>
    <relationshipName>RangeDiscounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RangeDiscount__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Escritórios de Vendas</relationshipLabel>
    <relationshipName>SalesOffices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/PaymentTypeGlobalList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PresentPayment</fullName>
        <default>true</default>
        <label>A vista</label>
    </customValue>
    <customValue>
        <fullName>FuturePayment</fullName>
        <label>A prazo</label>
    </customValue>
    <masterLabel>Lista global de tipos de pagamentos</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RangeDiscountHelper.cls
public with sharing class RangeDiscountHelper {
    private static Boolean isEnabled;
    private static Map<String, Set<String>> tableToKeyFields;
    private static Boolean isRunning;
    static{
        isEnabled = true;
    
        isRunning = false;      
    }

    public static Boolean isTriggerEnabled(){
        return isEnabled;
    }
    
    public static Boolean disableTrigger(){
        return isEnabled = false;
    }

    public static Boolean enableTrigger(){
        return isEnabled = true;
    }

    public static void initRangeDiscountValidation(List<RangeDiscount__c> newRangeDiscountList){
        System.debug('newRangeDiscountList: ' + newRangeDiscountList);
        Set<Id> familyIdSet = new Set<Id>();
        Set<Id> salesOfficeIdSet = new Set<Id>();
        for(RangeDiscount__c rd : newRangeDiscountList){
            familyIdSet.add(rd.Family__c);
            salesOfficeIdSet.add(rd.SalesOffice__c);
        }
        Map<Id,Family__c> familyIdMap = new Map<Id,Family__c>([SELECT Id, Name FROM Family__c WHERE Id IN :familyIdSet]);
        Map<Id,SalesOffice__c> salesOfficeIdMap = new Map<Id,SalesOffice__c>([SELECT Id, Name, ParentId__c, ParentId__r.ExternalId__c FROM SalesOffice__c WHERE Id IN :salesOfficeIdSet]);
        for (RangeDiscount__c rd : newRangeDiscountList) {
            rd.ExternalId__c = rd.ApprovingAuthority__c + ';' + rd.PaymentType__c + ';' + familyIdMap.get(rd.Family__c).Name + ';' + rd.CustomerCategory__c + ';' + salesOfficeIdMap.get(rd.SalesOffice__c).Name;
            rd.ClusterExternalId__c = salesOfficeIdMap.get(rd.SalesOffice__c).ParentId__r.ExternalId__c;
            System.debug('rd.ExternalId__c: ' + rd.ExternalId__c);
        }
    }
    public static void rangeDiscountValidation(Map<Id,RangeDiscount__c> rangeDiscountMap) {
        if(isRunning == true){
            return;
        }
        Set<String> approvedAuthoritySet = new Set<String> ();
        Set<String> paymentTypesSet = new Set<String> ();
        Set<Id> productFamilyIdSet = new Set<Id> ();
        Set<Id> salesOfficeIdSet = new Set<Id> ();
        Set<String> customerCategorySet = new Set<String> ();
        
        for (RangeDiscount__c rangeDiscount : rangeDiscountMap.values()) {
            approvedAuthoritySet.add(rangeDiscount.ApprovingAuthority__c);
            paymentTypesSet.add(rangeDiscount.PaymentType__c);
            productFamilyIdSet.add(rangeDiscount.Family__c);
            customerCategorySet.add(rangeDiscount.CustomerCategory__c);
            salesOfficeIdSet.add(rangeDiscount.SalesOffice__c);
        }
        Map<Id,RangeDiscount__c> changeRangeDiscountMap = new Map<Id,RangeDiscount__c> ([
            SELECT Id, ApprovingAuthority__c, FinalDate__c, PaymentType__c, Family__c, CustomerCategory__c,SalesOffice__c, Status__c
            FROM RangeDiscount__c WHERE ApprovingAuthority__c IN: approvedAuthoritySet AND PaymentType__c IN: paymentTypesSet AND
            Family__c IN: productFamilyIdSet AND CustomerCategory__c IN: customerCategorySet AND SalesOffice__c IN: salesOfficeIdSet AND Status__c = 'Aprovado'
        ]);

        //System.debug(changeRangeDiscountMap.values());
        Set<Id> changeRangeDiscountId = new Set<Id> ();
        if (!changeRangeDiscountMap.isEmpty()) {
            for (RangeDiscount__c rangeDiscount : rangeDiscountMap.values()) {
                for (RangeDiscount__c changeRangeDis : changeRangeDiscountMap.values()) {
                    if (changeRangeDis.ApprovingAuthority__c == rangeDiscount.ApprovingAuthority__c &&
                        changeRangeDis.PaymentType__c == rangeDiscount.PaymentType__c &&
                        changeRangeDis.Family__c == rangeDiscount.Family__c &&
                        changeRangeDis.CustomerCategory__c == rangeDiscount.CustomerCategory__c &&
                        changeRangeDis.SalesOffice__c == rangeDiscount.SalesOffice__c &&
                        changeRangeDis.Id != rangeDiscount.Id) {

                        if (!changeRangeDiscountId.contains(changeRangeDis.Id)) {
                            changeRangeDiscountId.add(rangeDiscount.Id);
                            changeRangeDiscountId.add(changeRangeDis.Id);
                            changeRangeDis.FinalDate__c = System.today()-1;  
                            changeRangeDis.Status__c = 'Bloqueado';             
                        }
                    }
                }  
            }
            isRunning = true;
            update changeRangeDiscountMap.values();
            isRunning = false;
        }
    }
}