force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    
    <label>Cluster</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/FinancialAdministrativeManager__c.field-meta.xml
<CustomField>
    <fullName>FinancialAdministrativeManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que indica se o pedido precisa de aprovação financeira, caso este campo esteja preenchido, o pedido precisa ser aprovado com o usuário que foi preenchido nesse campo.</description>
    <inlineHelpText>Campo que indica se o pedido precisa de aprovação financeira, caso este campo esteja preenchido, o pedido precisa ser aprovado com o usuário que foi preenchido nesse campo.</inlineHelpText>
    <label>Gerente Financeiro Administrativo</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ManagerOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/HasRefuseReason__c.field-meta.xml
<CustomField>
    <fullName>HasRefuseReason__c</fullName>
    <label>Tem motivo de recusa</label>
    <summaryFilterItems>
        <field>OrderItem.HasRefuseReason__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/RTV__c.field-meta.xml
<CustomField>
    <fullName>RTV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RTVOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/HasRefuseReason__c.field-meta.xml
<CustomField>
    <fullName>HasRefuseReason__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tem motivo de recusa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/RefuseReason__c.field-meta.xml
<CustomField>
    <fullName>RefuseReason__c</fullName>
    <label>Motivo Recusa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/fields/GGN__c.field-meta.xml
<CustomField>
    <fullName>GGN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Gerente Geral de Negócios</inlineHelpText>
    <label>GGN</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesOffices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Escritórios de Vendas</relationshipLabel>
    <relationshipName>SalesOffices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    
    <label>Organização de Vendas</label>
    <nameField>
        <label>Nome de Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizações de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrg__c/fields/Director__c.field-meta.xml
<CustomField>
    <fullName>Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Diretor Investida</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesOrgs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/SalesTeam__c.object-meta.xml
<CustomObject>
    
    <label>Equipe de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes de Vendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente Comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesTeams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Equipes de Vendas</relationshipLabel>
    <relationshipName>SalesTeams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Equipes de Vendas</relationshipLabel>
    <relationshipName>SalesTeams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingDivision__c/ShippingDivision__c.object-meta.xml
<CustomObject>
    
    <label>Divisão de Remessa</label>
    <nameField>
        <label>Divisão de Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisões de Remessa</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingDivision__c/fields/OrderCurrency__c.field-meta.xml
<CustomField>
    <fullName>OrderCurrency__c</fullName>
    <formula>Text(OrderItem__r.Order.Currency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moeda do pedido</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShippingDivision__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do pedido</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Divisões de Remessa</relationshipLabel>
    <relationshipName>ShippingDivisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingDivision__c/fields/RecalcShare__c.field-meta.xml
<CustomField>
    <fullName>RecalcShare__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recalcular Aprovadores</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShippingDivision__c/fields/RefuseReason__c.field-meta.xml
<CustomField>
    <fullName>RefuseReason__c</fullName>
    <label>Motivo de Recusa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShippingDivision__c/fields/ShippingValue__c.field-meta.xml
<CustomField>
    <fullName>ShippingValue__c</fullName>
    <description>Campo criado para multiplicar a quantidade da remessa com o valor unitário.</description>
    <formula>IF(ISBLANK(RefuseReason__c), IF(Quantity__c = 0, ConfirmedQuantity__c, Quantity__c), (Quantity__c * -1)) * OrderItem__r.UnitPrice</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Campo criado para multiplicar a quantidade da remessa com o valor unitário.</inlineHelpText>
    <label>Valor da Remessa</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ShippingDivision__c/fields/TableauShippingValue__c.field-meta.xml
<CustomField>
    <fullName>TableauShippingValue__c</fullName>
    <label>Valor da Remessa</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ShippingDivisionHelper.cls
public without sharing class ShippingDivisionHelper {
    private static Boolean runTrigger;

    static {
        runTrigger = true;
    }

    public static Boolean isTriggerEnabled(){
        return runTrigger;
    }

    public static Boolean enableTrigger(){
        return runTrigger = true;
    }

    public static Boolean disableTrigger(){
        return runTrigger = false;
    }

    public static void tablueuField(List<ShippingDivision__c> context) {
        for(ShippingDivision__c ship : context){
            ship.TableauShippingValue__c = ship.ShippingValue__c;
            ship.CurrencyIsoCode = ship.OrderCurrency__c;
        }
    }
    public static void checkRefuseReason(List<ShippingDivision__c> newShippingDivisionList, Map<Id, ShippingDivision__c> oldShippingDivisionMap) {
        Map<Id, OrderItem> orderItemMap = new Map<Id, OrderItem>();
        for (ShippingDivision__c shippingDivision : newShippingDivisionList) {
            if ((oldShippingDivisionMap == null || String.isBlank(oldShippingDivisionMap.get(shippingDivision.Id).RefuseReason__c)) && 
                shippingDivision.RefuseReason__c == '25' && String.isNotBlank(shippingDivision.OrderItem__c)) {
                orderItemMap.put(
                    shippingDivision.OrderItem__c, 
                    new OrderItem(
                        Id = shippingDivision.OrderItem__c,
                        HasRefuseReason__c = true
                    )
                );
            }
        }

        if (orderItemMap.size() > 0) {
            update orderItemMap.values();
        }
    }

    public static void createShippingDivision(List<ShippingDivision__c> spList){
        List<Id> orderIdList = new List<Id>();
        List<Id> shippingList = new List<Id>();
        for (ShippingDivision__c sd : spList){
            shippingList.add(sd.Id);
        }
        List<ShippingDivision__c> sdSearch = [
            SELECT Id, OrderItem__r.Order.OwnerId
            FROM ShippingDivision__c
            WHERE Id IN: shippingList
        ];
        for(ShippingDivision__c sd : sdSearch){
            sd.OwnerId = sd.OrderItem__r.Order.OwnerId;
        }
        ShippingDivisionHelper.disableTrigger();
        update sdSearch;
        ShippingDivisionHelper.enableTrigger();
    }

    public static void updateShare(List<ShippingDivision__c> spList){
        List<ShippingDivision__c> shipList = new List<ShippingDivision__c>();
        for(ShippingDivision__c ship : spList){
            if(ship.RecalcShare__c) 
                shipList.add(ship);
            ship.RecalcShare__c = false;
        }
        if(!shipList.isEmpty()){
            createShareShippingDivision(shipList);
        }
    }
    public static void createShareShippingDivision(List<ShippingDivision__c> spList){
        Set<String> nameSet = new Set<String>();
        Set<Id> orderIdSet = new Set<Id>();
        Set<Id> spIdSet = new Set<Id>();

        for (ShippingDivision__c sp : spList){
            spIdSet.add(sp.Id);
        }
        
        List<ShippingDivision__c> spNewList = [
            SELECT Id, OrderItem__r.OrderId
            FROM ShippingDivision__C
            WHERE Id IN: spIdSet
        ];

        for (ShippingDivision__c sp : spNewList) {
            orderIdSet.add(sp.OrderItem__r.OrderId);
        }
        Map<Id,Order> orderMap = new Map<Id,Order>([
            SELECT Name, Id, SalesTeam__c, RTV__c, CreatedById, SalesOrg__r.Director__c, SalesTeam__r.Manager__c, SalesOffice__r.GGN__c, SalesTeam__r.Name, SalesOffice__r.ParentId__r.Director__c, SalesOffice__r.ParentId__r.MarketingManager__c,SalesOffice__r.ParentId__r.FinancialAdministrativeManager__c, OwnerId
            FROM Order
            WHERE  Id IN: orderIdSet
        ]);

        Map<Id, Set<Id>> userIdMap = new Map<Id,  Set<Id>>();

        for (Order order : orderMap.values()) {
            // nameSet.add('AT_'+order.SalesTeam__r.Name);
            nameSet.add('Gerente_Comercial_'+order.SalesTeam__r.Name);
            // nameSet.add('RTV_'+order.SalesTeam__r.Name);
            nameSet.add('Vendedor_Interno_'+order.SalesTeam__r.Name);

            if(!userIdMap.containsKey(order.id)){
                userIdMap.put(order.id, new Set<Id>());
            }

            
            if(order.SalesTeam__r.Manager__c != null && order.OwnerId != order.SalesTeam__r.Manager__c)
                userIdMap.get(order.id).add(order.SalesTeam__r.Manager__c);

            if(order.SalesOffice__r.GGN__c != null)
                userIdMap.get(order.id).add(order.SalesOffice__r.GGN__c);

            if(order.SalesOffice__r.ParentId__r.Director__c != null)
                userIdMap.get(order.id).add(order.SalesOffice__r.ParentId__r.Director__c);

            if(order.SalesOffice__r.ParentId__r.MarketingManager__c != null)
                userIdMap.get(order.id).add(order.SalesOffice__r.ParentId__r.MarketingManager__c);

            if(order.SalesOffice__r.ParentId__r.FinancialAdministrativeManager__c != null)
                userIdMap.get(order.id).add(order.SalesOffice__r.ParentId__r.FinancialAdministrativeManager__c);

            if(order.SalesOrg__r.Director__c != null)
                userIdMap.get(order.id).add(order.SalesOrg__r.Director__c);
            
            if(!userIdMap.get(order.id).contains(order.RTV__c)){
                userIdMap.get(order.id).add(order.RTV__c);
            }

            if(!userIdMap.get(order.id).contains(order.OwnerId)){
                userIdMap.get(order.id).add(order.OwnerId);
            }

            if(!userIdMap.get(order.id).contains(order.CreatedById)){
                userIdMap.get(order.id).add(order.CreatedById);
            }

        }
        List<Group> GroupList = new List<Group>([
            SELECT DeveloperName, Id
            FROM Group
            WHERE DeveloperName IN: nameSet AND DeveloperName != null
        ]);

        System.debug('userIdMap: ' + userIdMap);
        System.debug('GroupList: ' + GroupList);
        
        //Set<ShippingDivision__c> sharesCreate = new Set<ShippingDivision__c>();
        Set<ShippingDivision__Share> SDShareCreate = new Set<ShippingDivision__Share>();

        
        if (!userIdMap.IsEmpty()) {
            for (ShippingDivision__c shippingDivision : spNewList) {
                if(userIdMap.containsKey(shippingDivision.OrderItem__r.OrderId)){
                    for(Id usId : userIdMap.get(shippingDivision.OrderItem__r.OrderId)){
                        ShippingDivision__Share shippingDivisionShare  = new ShippingDivision__Share();
                        shippingDivisionShare.ParentId = shippingDivision.Id;
                        shippingDivisionShare.UserOrGroupId = usId;
                        shippingDivisionShare.AccessLevel = 'Edit';    
                        SDShareCreate.add(shippingDivisionShare); 
                    }
                }
            }
        }

        if (!GroupList.IsEmpty()) {
            for (ShippingDivision__c shippingDivision : spNewList) {
                for (Group userGroup : GroupList) {
                    if (orderMap.containsKey(shippingDivision.OrderItem__r.OrderId) && orderMap.get(shippingDivision.OrderItem__r.OrderId).SalesTeam__r.Name != null &&  userGroup.DeveloperName.contains(orderMap.get(shippingDivision.OrderItem__r.OrderId).SalesTeam__r.Name)) {
                        ShippingDivision__Share shippingDivisionShare  = new ShippingDivision__Share();
                        shippingDivisionShare.ParentId = shippingDivision.Id;
                        shippingDivisionShare.UserOrGroupId = userGroup.Id;
                        shippingDivisionShare.AccessLevel = 'Edit';    
                        SDShareCreate.add(shippingDivisionShare); 
                    }
                }
            }
        }

        System.debug('ShareCreate: ' + SDShareCreate);
        if (!SDShareCreate.isEmpty()) {
            insertDML(JSON.serialize(SDShareCreate));
        }
    }

    public static void insertDML(string SDShareCreate){
        Database.Insert((List<ShippingDivision__Share>)JSON.deserialize(SDShareCreate, List<ShippingDivision__Share>.class), false);
    }

}