force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    
    <label>Cluster</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crop__c/Crop__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Safra provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Safra</label>
    <nameField>
        <label>Nome de Safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crop__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Código externo, chave primária utilizada pelo SAP para identificar o registro.</description>
    <externalId>true</externalId>
    <inlineHelpText>Código externo, chave primária utilizada pelo SAP para identificar o registro.</inlineHelpText>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Centros de Distribuição provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome de Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    
    <label>Família de Produto</label>
    <nameField>
        <label>Nome de Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Família de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ActivePrinciple__c.field-meta.xml
<CustomField>
    <fullName>ActivePrinciple__c</fullName>
    <label>Principio Ativo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Product2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/ProductManagement__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para controlar os produtos que podem ser vendidos, stop de vendas e que cairão para aprovação</description>
    
    <label>Controle de produto</label>
    <nameField>
        <displayFormat>PMG-{0000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controle de produtos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductManagement__c/fields/AvailableInventory__c.field-meta.xml
<CustomField>
    <fullName>AvailableInventory__c</fullName>
    <description>Campo de totalização que soma o estoque físico com as compras e subtrai as vendas.</description>
    <formula>Inventory__c +  FutureInventory__c -  SalesInventory__c + Tolerance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Campo de totalização que soma o estoque físico com as compras e subtrai as vendas.</inlineHelpText>
    <label>Estoque Disponível</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloquear Venda?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Controle de produtos</relationshipLabel>
    <relationshipName>Controle_de_produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Centro de distribuição onde esta localizado o estoque.</description>
    <inlineHelpText>Centro de distribuição onde esta localizado o estoque.</inlineHelpText>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Saldo de estoque</relationshipLabel>
    <relationshipName>Controle_de_produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Controle de produtos</relationshipLabel>
    <relationshipName>Controle_de_produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Controle de produtos</relationshipLabel>
    <relationshipName>Controle_de_produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/Tolerance__c.field-meta.xml
<CustomField>
    <fullName>Tolerance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Campo para definir a quantidade de tolerância de produto com estoque zerado.</description>
    <label>Quantidade de Tolerância</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/UnitMeasurement__c.field-meta.xml
<CustomField>
    <fullName>UnitMeasurement__c</fullName>
    <label>Unidade de Medida</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/recordTypes/ExclusionList.recordType-meta.xml
<RecordType>
    <fullName>ExclusionList</fullName>
    <active>true</active>
    <description>Tipo de registro utilizado para listas de exclusão</description>
    <label>Lista de exclusão</label>
</RecordType>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Escritórios de Vendas</relationshipLabel>
    <relationshipName>SalesOffices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/SalesTeam__c.object-meta.xml
<CustomObject>
    
    <label>Equipe de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes de Vendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <inlineHelpText>Nome exibido no PDF de pedidos</inlineHelpText>
    <label>Nome de Exibição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Equipes de Vendas</relationshipLabel>
    <relationshipName>SalesTeams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Equipes de Vendas</relationshipLabel>
    <relationshipName>SalesTeams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Campo referente ao ID do usuário no SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Campo referente ao ID do usuário no SAP.</inlineHelpText>
    <label>Código Externo</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/StockListScreenController.cls
public with sharing class StockListScreenController {
    public class StockData{
        @AuraEnabled public String recordId      {get;set;}
        @AuraEnabled public String productName   {get;set;}
        @AuraEnabled public String productCode   {get;set;}
        @AuraEnabled public Decimal tolerance   {get;set;}
        @AuraEnabled public Boolean showTolerance   {get;set;}
        @AuraEnabled public String salesTeamId   {get;set;}
        @AuraEnabled public String salesTeamName {get;set;}
        @AuraEnabled public Boolean hasCrop   {get;set;}
        @AuraEnabled public String cropId   {get;set;}
        @AuraEnabled public String cropName {get;set;}
        @AuraEnabled public String externalId    {get;set;}
        @AuraEnabled public Decimal stock         {get;set;}
        @AuraEnabled public Decimal stockBaseCalc {get;set;}
        @AuraEnabled public Boolean isBlocked     {get;set;}
        @AuraEnabled public Boolean hasExcluded   {get;set;}
        @AuraEnabled public Boolean hasStock   {get;set;}
        @AuraEnabled public Boolean showActive   {get;set;}
        @AuraEnabled public String distId        {get;set;}
        @AuraEnabled public String distName      {get;set;}
        @AuraEnabled public String unitmeasure     {get;set;}
        @AuraEnabled public String styleColor     {get;set;}
        @AuraEnabled public String styleTextColor     {get;set;}
        @AuraEnabled public String styleText     {get;set;}
        public StockData(Product2 prod, SalesTeam__c salesteam, ProductManagement__c prodExcluded){
            this.recordId      = prod.Id+'_'+salesTeam.Id;
            this.productName   = prod.name;
            this.productCode   = prod.ProductCode;
            this.salesTeamId   = salesteam.id;
            this.salesTeamName = salesteam.DisplayName__c == null ? salesteam.Name: salesteam.DisplayName__c;
            this.externalId    = prod.Id+'_'+salesTeam.Id;
            this.stock         = null;
            this.stockBaseCalc = null;
            this.tolerance     = null;
            this.showTolerance = false;
            this.isBlocked     = false;
            this.hasCrop       = false;
            this.distId        = salesteam.DistributionCenter__c;
            this.distName      = salesteam.DistributionCenter__r.Name;
            this.unitmeasure   = prod.QuantityUnitOfMeasure;
            this.hasExcluded   = prodExcluded != null;
            this.hasStock = false;
            this.checkTitle();
        }
        public StockData(ProductManagement__c prod, SalesTeam__c salesteam, ProductManagement__c prodExcluded){
            this.recordId      = prod.Id;
            this.productName   = prod.Product2__r.name;
            this.productCode   = prod.Product2__r.ProductCode;
            this.hasCrop       = prod.Crop__c != null;
            this.cropId   = prod.Crop__c;
            this.cropName = prod.Crop__r?.Name;            
            this.showTolerance = true;
            this.salesTeamId   = salesteam.id;
            this.salesTeamName = salesteam.DisplayName__c == null ? salesteam.Name: salesteam.DisplayName__c;
            this.externalId    = prod.ExternalId__c;
            this.stock         = prod.AvailableInventory__c;
            this.stockBaseCalc = (prod.AvailableInventory__c != null ? prod.AvailableInventory__c : 0) - (prod.Tolerance__c != null ? prod.Tolerance__c : 0);
            this.tolerance     = this.stockBaseCalc != 0 ? (((prod.Tolerance__c != null ? prod.Tolerance__c : 0) * 100) / this.stockBaseCalc) : 0;
            this.isBlocked     = prod.Block__c;
            this.distId        = prod.DistributionCenter__c;
            this.distName      = prod.DistributionCenter__r.Name;
            this.unitmeasure   = prod.UnitMeasurement__c;
            this.hasExcluded   = prodExcluded != null;
            this.hasStock = true;
            this.checkTitle();
        }
        public void checkPermission(Boolean isAdmin){
            this.showActive = isAdmin && (this.hasStock);
            this.showTolerance = isAdmin && (this.hasStock);
        }
        public void checkTitle(){
            this.styleColor    = 'border: 2px solid {recordData} !important;';
            if((this.stock > 0 && !this.isBlocked) || this.stock == null){
                this.styleText = 'Produto disponível para venda';
                this.styleColor = this.styleColor.replace('{recordData}', 'green');
                this.styleTextColor = 'color: green;';
            }else{
                if(this.stock < 0 && this.isBlocked ){
                    this.styleText = 'Este produto não possui estoque para venda. Em caso de dúvida, contatar Customer Service';
                    this.styleColor = this.styleColor.replace('{recordData}', 'red');
                    this.styleTextColor = 'color: red;';
                }
                /*else if(this.stock < 0 && !this.isBlocked ){
                    this.styleText = 'Atenção, este produto pode não ter estoque disponível. Em caso de dúvida, contatar Customer Service';
                    this.styleColor = this.styleColor.replace('{recordData}', 'red');
                    this.styleTextColor = 'color: red;';
                }*/
            }

            if(this.hasExcluded){
                this.styleText = 'Produto marcado para exclusão';
                this.styleColor = this.styleColor.replace('{recordData}', 'red');
                this.styleTextColor = 'color: red;';
            }
        }
    }
    
    public static Set<String> getProduct2IdSet(String[] prodIdParam, String principles){
        Set<String> prodIdSet = new Set<String>();
        if(principles != null){
            prodIdParam.add(principles);
        }
        for(Product2 prod : [SELECT id 
                            FROM Product2 
                            WHERE isActive = true
                            AND (Family__c IN :prodIdParam
                                OR ActivePrinciple__c IN :prodIdParam
                                OR Id IN :prodIdParam) ORDER BY  Name ASC ]){
            prodIdSet.add(prod.id);
        }
        return prodIdSet;
    }

    public static Map<String, ProductManagement__c> getExclusionList(String[] cropId, Set<String> productIdList, Map<String, SalesTeam__c>  centerIdMap){
        Map<String, ProductManagement__c> prodMap = new Map<String, ProductManagement__c>();
        for(ProductManagement__c prod : [SELECT id, SalesTeam__c, Product2__c FROM ProductManagement__c WHERE  RecordType.DeveloperName = 'ExclusionList' AND (Crop__c IN :cropId OR Crop__c = null) AND SalesTeam__c IN :Collection.of(centerIdMap.values()).pluckIds() AND IsActive__c = true  AND Product2__c IN :productIdList  ]){
            prodMap.put(prod.Product2__c+'_'+prod.SalesTeam__c, prod);
        }
        return prodMap;
    }
    public static Map<String, SalesTeam__c> getCenterId(String[] salesTeamId){
        Map<String, SalesTeam__c> prodIdMap = new Map<String, SalesTeam__c>();

        if(salesTeamId.isEmpty()){
            for(SalesTeam__c sales : [SELECT id, DistributionCenter__c, DisplayName__c, Name, DistributionCenter__r.Name FROM SalesTeam__c])
                prodIdMap.put(sales.DistributionCenter__c, sales);

        }else{
            for(SalesTeam__c sales : [SELECT id, DistributionCenter__c, DisplayName__c, Name, DistributionCenter__r.Name FROM SalesTeam__c WHERE id IN :salesTeamId OR DistributionCenter__c IN :salesTeamId])
                prodIdMap.put(sales.DistributionCenter__c, sales);
        }

        System.debug('prodIdMap => ' + prodIdMap);

        return prodIdMap;
    }

    public static Map<String, StockData> getStockData(String[] cropId, String clusterId, Boolean isActive, Set<String> productIdList, Map<String, SalesTeam__c>  centerIdMap, Map<String, ProductManagement__c> prodMap){
        Map<String, StockData> pricListDataMap = new Map<String, StockData>();
        Set<String> centerIdSet = null;

        Map<String, SalesTeam__c> prodIdMap = new Map<String, SalesTeam__c>();
        for(SalesTeam__c sales : [SELECT id, DistributionCenter__c, DisplayName__c, Name, DistributionCenter__r.Name, ParentId__r.ParentId__c FROM SalesTeam__c]){
            prodIdMap.put(sales.DistributionCenter__c, sales);
            if(clusterId != null && sales.ParentId__r.ParentId__c == clusterId && centerIdMap.isEmpty()){
                centerIdMap.put(sales.DistributionCenter__c, sales);
            }
        }
            

        String query = ' SELECT Id, Product2__r.name, Tolerance__c, Crop__c, Crop__r.name, Product2__r.ProductCode, AvailableInventory__c, Block__c, DistributionCenter__r.Name, DistributionCenter__c, ExternalId__c, Product2__c, UnitMeasurement__c FROM ProductManagement__c WHERE RecordType.DeveloperName LIKE \'%Stock%\' ';

        if(!centerIdMap.isEmpty()){
            centerIdSet = centerIdMap.keySet(); 

            query += ' AND DistributionCenter__c IN :centerIdSet ';
        }

        if(productIdList != null && !productIdList.isEmpty()){
            query += ' AND Product2__c IN :productIdList ';
        }

        if(!cropId.isEmpty()){
            query += ' AND (Crop__c IN :cropId OR Crop__c = null) ';
        }

        if(isActive != null){
            query += ' AND (Block__c = :isActive) ';
        }

        query += ' Order By Product2__r.Name ASC ';
        query += ' LIMIT 1000';

        System.debug('query => ' + query);
        System.debug('query => ' + isActive);
        System.debug('query => ' + productIdList);
        System.debug('query => ' + centerIdMap);

        List<ProductManagement__c> prodList =  (List<ProductManagement__c>)Database.query(query);
        for(ProductManagement__c prod : prodList){
            if(!prodIdMap.containsKey(prod.DistributionCenter__c)) continue;
            SalesTeam__c sales = prodIdMap.get(prod.DistributionCenter__c);

            String key = prod.Product2__c+'_'+sales.Id;

            ProductManagement__c prodExcluded = prodMap.containsKey(key) ? prodMap.get(key) : null;
            
            pricListDataMap.put(key+'_'+prod.Crop__c, new StockData(prod, sales, prodExcluded));
        }
        System.debug('pricListDataMap => ' + pricListDataMap);

        return pricListDataMap;
    }
    
    public static void getInventoryNewRecords(Map<String, StockData> priceData, Set<String> productIdList, Map<String, SalesTeam__c>  centerIdMap, Map<String, ProductManagement__c> prodMap){
        for(Product2 prod : [SELECT id, name, ProductCode, QuantityUnitOfMeasure FROM Product2 WHERE Id = :productIdList]){
           for(SalesTeam__c sales : centerIdMap.values()){
               String key = prod.id+'_'+sales.id;
                ProductManagement__c prodExcluded = prodMap.containsKey(key) ? prodMap.get(key) : null;
            
               if(!priceData.containsKey(key)){
                   priceData.put(key, new StockData(prod, sales, prodExcluded));
               }
           }
        }
    }
    public static Boolean getProfileName(){        
        User us = [SELECT id, Profile.Name FROM User WHERE Id =: Userinfo.getUserId()];
        
        return us.Profile.Name.contains('Admin') || us.Profile.Name.contains('Service') ;
    }
    public static void handleProfileName(Map<String, StockData> priceData){        
        Boolean isAdmin = getProfileName();
        for(StockData stck : priceData.values()){
            stck.checkPermission(isAdmin);
        }
    }
    @AuraEnabled
    public static Boolean getProfileCheck(){
        return getProfileName();
    }
    @AuraEnabled
    // public static List<StockData> getStock(String cropId, Boolean isActive, String productId, String clusterId, String salesTeamId, String principleActive, String productFamily){
    public static List<StockData> getStock(Boolean isActive, String clusterId, String[] idsSet, String[] centerSet, String[] cropIdSet, String principleActive){
        // idsSet.add(principleActive); 
        Set<String> prodIdList = getProduct2IdSet(idsSet, principleActive);
         Map<String, SalesTeam__c> salesIdMap = getCenterId(centerSet);
         Map<String, ProductManagement__c> exclusionListMap = getExclusionList(cropIdSet, prodIdList, salesIdMap);

         Map<String, StockData> priceData =  getStockData(cropIdSet, clusterId, isActive, prodIdList, salesIdMap, exclusionListMap);

        //  getInventoryNewRecords(priceData, prodIdList, salesIdMap, exclusionListMap);

         System.debug('priceData => ' + priceData);

         handleProfileName(priceData);

        return priceData.values();
    }
    
    @AuraEnabled
    public static void activeList(List<String> priceIdList, Boolean actualValue) {
        List<ProductManagement__c> productManagementList = new List<ProductManagement__c>();
        for (String priceData : priceIdList) {
            if(!priceData.contains('_')){
                productManagementList.add(new ProductManagement__c(
                    Id = priceData,
                    Block__c = actualValue
                ));
            }
        }

        update productManagementList;
    }

}