force-app/main/default/objects/CampaignProduct__c/CampaignProduct__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena produtos ( Produto, Família ou Fornecedor ) da Campanha.</description>
    
    <label>Produto da Campanha</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos da Campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignProduct__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campanha</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Produtos da Campanha</relationshipLabel>
    <relationshipName>Produtos_da_Campanha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/CanActivateRules__c.field-meta.xml
<CustomField>
    <fullName>CanActivateRules__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Caso este campo esteja marcado, o produto será considerado para ativar as regra da campanha.</description>
    <inlineHelpText>Caso este campo esteja marcado, o produto será considerado para ativar as regra da campanha.</inlineHelpText>
    <label>Este produto ativa as regras?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/CanReceiveDiscount__c.field-meta.xml
<CustomField>
    <fullName>CanReceiveDiscount__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Caso este campo esteja marcado, ele vai receber o desconto estipulado nas regras da campanha.</description>
    <inlineHelpText>Caso este campo esteja marcado, ele vai receber o desconto estipulado nas regras da campanha.</inlineHelpText>
    <label>Este produto recebe desconto?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/ComercialName__c.field-meta.xml
<CustomField>
    <fullName>ComercialName__c</fullName>
    <label>Nome Comercial</label>
    <length>255</length>
    <inlineHelpText>Nome comercial dos produtos da ForcaAgro</inlineHelpText>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/ExternalIdIndex__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdIndex__c</fullName>
    <description>Campo para armazenar nome do Produto da Campanha e não permitir criação de Produto duplicado</description>
    <externalId>true</externalId>
    <label>ExternalIdIndex</label>
    <length>140</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Familia</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Produtos da Campanha</relationshipLabel>
    <relationshipName>FamiliaCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Fornecedor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/MaxQuantity__c.field-meta.xml
<CustomField>
    <fullName>MaxQuantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade limite</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos da Campanha</relationshipLabel>
    <relationshipName>ProdutosCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    
    <label>Família de Produto</label>
    <nameField>
        <label>Nome de Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Família de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Product2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Fabricante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ImportCampaignProduct.cls
public without sharing class ImportCampaignProduct {
    public ImportCampaignProduct(ApexPages.StandardController stdController) { }
    @RemoteAction
    public static String createRecords(String entryList){

        List<CampaignProductData> excelDataList = (List<CampaignProductData>)JSON.deserialize(entryList, List<CampaignProductData>.class);
        Map<String, sObject> lookups = new Map<String, sObject>();
        for(CampaignProductData oppData : excelDataList){
            lookups.put(oppData.campaignNumber, null);
            lookups.put(oppData.productCode, null);
            lookups.put(oppData.familyCode, null);
        }

        for(Campaign prod : [SELECT id, name FROM Campaign WHERE Name IN : lookups.keySet()]){
            lookups.put(prod.name, prod);
        }

        for(Product2 prod : [SELECT id, Name, ProductCode FROM Product2 WHERE Name IN : lookups.keySet()]){
            lookups.put(prod.ProductCode, prod);
        }
        
        for(Family__c prod : [SELECT id, Name, ExternalId__c FROM Family__c WHERE Name IN : lookups.keySet()]){
            lookups.put(prod.ExternalId__c, prod);
        }

        Map<String, CampaignProduct__c> oppLineItemMap = new Map<String, CampaignProduct__c>();
        for(CampaignProductData oppData : excelDataList){
            CampaignProduct__c prod  = oppData.getCampaignProductData(lookups);
            oppLineItemMap.put(prod.ExternalIdIndex__c, prod);
        }
        
        if(!oppLineItemMap.isEMpty()){
            Database.insert(oppLineItemMap.values());
        }

        return 'Sucesso';
    }
    public class CampaignProductData{
        public String campaignNumber {get;set;}
        public String productCode {get;set;}
        public String familyCode {get;set;}
        public String Manufacturer {get;set;}
        public String comercialName {get;set;}
        public String quantity {get;set;}
        public String rules {get;set;}
        public String discounts {get;set;}
        public CampaignProductData(Boolean isTest){
            if(isTest){
                this.campaignNumber = 'CAM-0190';
                this.productCode    = '100231';
                this.familyCode     = '1002';
                this.Manufacturer     = 'BAYER';
                this.comercialName  = 'FOX XPRO';
                this.quantity       = '100';
                this.rules          = 'true';
                this.discounts      = 'false';
            }
        }
        public CampaignProduct__c getCampaignProductData(Map<String, sObject> lookups){
        CampaignProduct__c campaignProduct = new CampaignProduct__c(
            Campaign__c = (Id)lookups.get(this.campaignNumber).get('Id'),
            CanActivateRules__c = this.rules == 'true',
            CanReceiveDiscount__c = this.discounts == 'true',
            CurrencyIsoCode = 'BRL',
            Manufacturer__c = this.Manufacturer,
            ComercialName__c = this.comercialName,
            Family__c = (Id)lookups.get(this.familyCode).get('Id'),
            Product2__c  = (Id)lookups.get(this.productCode).get('Id'),
            MaxQuantity__c = Decimal.valueOf(this.quantity)
        );
        campaignProduct.ExternalIdIndex__c = 
            (this.Manufacturer != null ? this.Manufacturer : 
            this.comercialName != null ? this.comercialName : 
            campaignProduct.Product2__c != null ? (String)lookups.get(this.productCode).get('Name') : 
            campaignProduct.Family__c != null ? (String)lookups.get(this.familyCode).get('Name') :  '') + ' - '+(String)lookups.get(this.campaignNumber).get('Name');
        return campaignProduct;
        }
    }
}