force-app/main/default/objects/CampaignProduct__c/CampaignProduct__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena produtos ( Produto, Família ou Fornecedor ) da Campanha.</description>
    
    <label>Produto da Campanha</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos da Campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignProduct__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campanha</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Produtos da Campanha</relationshipLabel>
    <relationshipName>Produtos_da_Campanha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/CanActivateRules__c.field-meta.xml
<CustomField>
    <fullName>CanActivateRules__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Caso este campo esteja marcado, o produto será considerado para ativar as regra da campanha.</description>
    <inlineHelpText>Caso este campo esteja marcado, o produto será considerado para ativar as regra da campanha.</inlineHelpText>
    <label>Este produto ativa as regras?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/CanReceiveDiscount__c.field-meta.xml
<CustomField>
    <fullName>CanReceiveDiscount__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Caso este campo esteja marcado, ele vai receber o desconto estipulado nas regras da campanha.</description>
    <inlineHelpText>Caso este campo esteja marcado, ele vai receber o desconto estipulado nas regras da campanha.</inlineHelpText>
    <label>Este produto recebe desconto?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/ComercialName__c.field-meta.xml
<CustomField>
    <fullName>ComercialName__c</fullName>
    <label>Nome Comercial</label>
    <length>255</length>
    <inlineHelpText>Nome comercial dos produtos da ForcaAgro</inlineHelpText>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/ExternalIdIndex__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdIndex__c</fullName>
    <description>Campo para armazenar nome do Produto da Campanha e não permitir criação de Produto duplicado</description>
    <externalId>true</externalId>
    <label>ExternalIdIndex</label>
    <length>140</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Familia</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Produtos da Campanha</relationshipLabel>
    <relationshipName>FamiliaCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Fornecedor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/MaxQuantity__c.field-meta.xml
<CustomField>
    <fullName>MaxQuantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade limite</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignProduct__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos da Campanha</relationshipLabel>
    <relationshipName>ProdutosCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    
    <label>Família de Produto</label>
    <nameField>
        <label>Nome de Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Família de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Product2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Fabricante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateProductCampaignController.cls
public with sharing class CreateProductCampaignController {

    @AuraEnabled
    public static CampaignData getScenarioRecords(String campaignId) {
        CampaignData campaignDatas = new CampaignData();
        for (CampaignProduct__c campProd : [SELECT Id, Campaign__c, Campaign__r.Name, ComercialName__c, Product2__r.Name, Product2__c, Family__c, Family__r.Name, MaxQuantity__c, CanReceiveDiscount__c, CanActivateRules__c, Manufacturer__c FROM CampaignProduct__c WHERE Campaign__c = :campaignId ORDER BY CreatedDate ASC]) {
            campaignDatas.addProduct(campProd);
        }
        return campaignDatas;
    }

    @AuraEnabled
    public static Response upsertProduct(String campaignId, String prod) {
        ProductData ProductData = (ProductData)JSON.deserialize(prod, ProductData.class);
        System.debug('converteu');
        CampaignProduct__c projStep = new CampaignProduct__c(
            Id                    = ProductData.id,
            Name                  = ProductData.name,
            ExternalIdIndex__c    = ProductData.name,

            Campaign__c           = ProductData.campaign,
            Product2__c           = ProductData.product2?.id,
            Family__c             = ProductData.family?.id,
            Manufacturer__c       = ProductData.manufacturer,
            ComercialName__c      = ProductData.comercialName,
            MaxQuantity__c        = ProductData.max,

            CanReceiveDiscount__c = ProductData.receive,
            CanActivateRules__c   = ProductData.activates
        );

        try {
            //upsert projStep CampaignProduct__c.ExternalIdIndex__c; 
            upsert projStep;
            return new Response(false, 'Success');
        } catch (Exception e) {
            return new Response(true, e.getMessage());
        }
    }

    @AuraEnabled
    public static Response deleteProduct(String prod) {
        ProductData ProductData = (ProductData)JSON.deserialize(prod, ProductData.class);
        System.debug('converteu');
        CampaignProduct__c projStep = new CampaignProduct__c(
            Id                    = ProductData.id,
            Name                  = ProductData.name,
            ExternalIdIndex__c    = ProductData.name,

            Campaign__c           = ProductData.campaign,
            Product2__c           = ProductData.product2?.id,
            Family__c             = ProductData.family?.id,
            Manufacturer__c       = ProductData.manufacturer,
            ComercialName__c      = ProductData.comercialName,
            MaxQuantity__c        = ProductData.max,

            CanReceiveDiscount__c = ProductData.receive,
            CanActivateRules__c   = ProductData.activates
        );

        try {
            //upsert projStep CampaignProduct__c.ExternalIdIndex__c; 
            delete projStep;
            return new Response(false, 'Success');
        } catch (Exception e) {
            return new Response(true, e.getMessage());
        }
    }

    public class Response {
        @AuraEnabled
        public Boolean hasError {get;set;}
        @AuraEnabled
        public String  message  {get;set;}

        public Response(Boolean hasError, String message) {
            this.hasError = hasError;
            this.message  = message;
        }
    }

    public class CampaignData {
        @AuraEnabled public String campaignId    {get;set;}
        @AuraEnabled public String campaignName    {get;set;}
        @AuraEnabled public List<ProductData> productDataList    {get;set;}
        public CampaignData () {}

        public void addProduct(CampaignProduct__c campaignProd){
            this.campaignId = campaignProd.Campaign__c;
            this.campaignName = campaignProd.Campaign__r.Name;

            if(this.productDataList == null)
                this.productDataList = new List<ProductData>();
            
            this.productDataList.add(new ProductData(campaignProd));
        }
    }
    public class ProductData {
        @AuraEnabled public String id                    {get;set;}
        @AuraEnabled public String url                    {get;set;}
        @AuraEnabled public String name                    {get;set;}
        @AuraEnabled public ObjectLinkData product2                    {get;set;}
        @AuraEnabled public ObjectLinkData family                    {get;set;}
        @AuraEnabled public String manufacturer                    {get;set;}
        @AuraEnabled public String comercialName {get;set;}
        @AuraEnabled public Decimal max                    {get;set;}
        @AuraEnabled public Boolean receive                    {get;set;}
        @AuraEnabled public Boolean activates                    {get;set;}
        @AuraEnabled public String campaign {get;set;}

        public ProductData() {}

        public ProductData(CampaignProduct__c prods) {
            this.id                 = prods.Id;
            this.url                = '/' + prods.Id;
            this.name               = prods.product2__r.Name + ' - '+prods.Campaign__r.Name;
            this.product2           = prods.Product2__c == null ? null : new ObjectLinkData(prods.Product2__c, prods.Product2__r.Name);
            this.family             = prods.Family__c   == null ? null : new ObjectLinkData(prods.Family__c, prods.Family__r.Name);
            this.comercialName      = prods.ComercialName__c;
            this.manufacturer       = prods.Manufacturer__c;
            this.campaign           = prods.Campaign__c;

            this.max = prods.MaxQuantity__c;

            this.receive  = prods.CanReceiveDiscount__c;
            this.activates = prods.CanActivateRules__c;
        }
    }
    public class ObjectLinkData {
        @AuraEnabled public String Id                   {get;set;}
        @AuraEnabled public String Name                 {get;set;}

        public ObjectLinkData(String p_id, String p_name) { 
            this.id = p_id;
            this.name = p_Name;
            // this.url = '/'+p_id;
        }
    }


}