force-app/main/default/objects/ListPrice__c/ListPrice__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena dos dados do catalogo de preço, esse objeto será alimentado através de integração com o SAP, o SAP irá manipular os registros através da API padrão do  salesforce.</description>
    
    <label>Catálogo de preço</label>
    <nameField>
        <displayFormat>CAT-{0000}</displayFormat>
        <label>Nome do Catalogo de preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Catalogos de preço</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ListPrice__c/fields/ActivitySector__c.field-meta.xml
<CustomField>
    <fullName>ActivitySector__c</fullName>
    <description>Este campo armazena os valores referentes ao campo VBAK - SPART no SAP.</description>
    <inlineHelpText>Este campo armazena os valores referentes ao campo VBAK - SPART no SAP.</inlineHelpText>
    <label>Setor de Atividade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>Agricultura</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Pecuária</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Maquinas Implementos</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Commodities</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>Outras Saídas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Valor utilizado durante o calculo de margem do produto do pedido.</inlineHelpText>
    <label>Custo</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo que informa se o catalogo de preços esta ativo.</description>
    <inlineHelpText>Campo que informa se o catalogo de preços esta ativo.</inlineHelpText>
    <label>Ativo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Catalogos de preço</relationshipLabel>
    <relationshipName>ListPrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <description>Valor unitário do produto, referente ao campo KONP - KBETR no SAP.</description>
    <inlineHelpText>Valor unitário do produto, referente ao campo KONP - KBETR no SAP.</inlineHelpText>
    <label>Valor</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractEndDate__c.field-meta.xml
<CustomField>
    <fullName>ContractEndDate__c</fullName>
    <description>Data referente ao termino do contrato de venda de insumos</description>
    <inlineHelpText>Data referente ao termino do contrato de venda de insumos</inlineHelpText>
    <label>Data Fim Contrato de Insumos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractOrder__c.field-meta.xml
<CustomField>
    <fullName>ContractOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos (Contrato de Pedido)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>ContractStartDate__c</fullName>
    <description>Data referente ao contrato de venda de insumos</description>
    <inlineHelpText>Data referente ao contrato de venda de insumos</inlineHelpText>
    <label>Data Inicio Contrato de Insumos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/StatusSAP__c.field-meta.xml
<CustomField>
    <fullName>StatusSAP__c</fullName>
    <label>StatusSAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Em análise de Crédito</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Crédito Bloqueado</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Crédito Liberado</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Faturado Parcial</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Concluído</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/StatusSF__c.field-meta.xml
<CustomField>
    <fullName>StatusSF__c</fullName>
    <label>Status SF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em digitação</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Retorna RTV</fullName>
            </value>
            <value>
                <fullName>Em aprovação grãos</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Valor Commodity Líquido</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/BarterSale.recordType-meta.xml
<RecordType>
    <fullName>BarterSale</fullName>
    <active>true</active>
    <description>Indica se o pedido é uma venda de barter</description>
    <label>Negociação Barter</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/ZCCO.recordType-meta.xml
<RecordType>
    <fullName>ZCCO</fullName>
    <active>true</active>
    <label>Contrato Conta e Ordem</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/ZCNO.recordType-meta.xml
<RecordType>
    <fullName>ZCNO</fullName>
    <active>true</active>
    <label>Contrato Venda Moeda</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/ActivePrinciple__c.field-meta.xml
<CustomField>
    <fullName>ActivePrinciple__c</fullName>
    <formula>Product2.ActivePrinciple__c</formula>
    <label>Principio Ativo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AdditionAmount__c.field-meta.xml
<CustomField>
    <fullName>AdditionAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valor de acréscimo</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AdditionPercent__c.field-meta.xml
<CustomField>
    <fullName>AdditionPercent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Percentual de acréscimo</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ContractProductCredit__c.field-meta.xml
<CustomField>
    <fullName>ContractProductCredit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Saldo Restante em Contrato</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Custo</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cultura</label>
    <referenceTo>Culture__c</referenceTo>
    <relationshipLabel>Produtos do pedido</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <label>Valor Desconto</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <label>Percentual de desconto</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LastChangedPriceList__c.field-meta.xml
<CustomField>
    <fullName>LastChangedPriceList__c</fullName>
    <description>Toda vez que um produto do pedido for inserido dentro da tela, é colocado a data do dia dentro do campo</description>
    <label>Ultima Data Lista de Preço</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ListPrice__c.field-meta.xml
<CustomField>
    <fullName>ListPrice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Catálogo de preço</label>
    <referenceTo>ListPrice__c</referenceTo>
    <relationshipLabel>Produtos do pedido</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PriceListEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>PriceListEffectiveDate__c</fullName>
    <label>Data efetiva da lista de preço</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantidade Total</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/RefuseReason__c.field-meta.xml
<CustomField>
    <fullName>RefuseReason__c</fullName>
    <label>Motivo Recusa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/UnitMeasure__c.field-meta.xml
<CustomField>
    <fullName>UnitMeasure__c</fullName>
    <label>Unidade de Medida</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ActivePrinciple__c.field-meta.xml
<CustomField>
    <fullName>ActivePrinciple__c</fullName>
    <label>Principio Ativo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Product2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Peso Bruto</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/GrossWeightUnity__c.field-meta.xml
<CustomField>
    <fullName>GrossWeightUnity__c</fullName>
    <label>Unidade de Medida do Peso Bruto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Multiplicity__c.field-meta.xml
<CustomField>
    <fullName>Multiplicity__c</fullName>
    <label>Multiplicidade do Item</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RemoveFreightValue__c.field-meta.xml
<CustomField>
    <fullName>RemoveFreightValue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remover Valor de Frete?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShippingDivision__c/ShippingDivision__c.object-meta.xml
<CustomObject>
    
    <label>Divisão de Remessa</label>
    <nameField>
        <label>Divisão de Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisões de Remessa</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingDivision__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do pedido</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Divisões de Remessa</relationshipLabel>
    <relationshipName>ShippingDivisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingDivision__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ShippingDivision__c/fields/RefuseReason__c.field-meta.xml
<CustomField>
    <fullName>RefuseReason__c</fullName>
    <label>Motivo de Recusa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomLookupController.cls
public with sharing class CustomLookupController {
    
    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecords(String objectApiName, String fieldApiName, String fieldApiNames, String filter, String searchTerm, String recordId, Boolean byFocus) {
        System.debug(objectApiName);
        System.debug(fieldApiName);
        System.debug(filter);
        System.debug(searchTerm);
        System.debug(recordId);
        System.debug(fieldApiNames);

        if(recordId == null) {
            recordId = '';
        } else if (filter == null) {
            filter = '';
        }
        System.debug((recordId != null));
        System.debug((recordId != ''));
        System.debug(filter.contains('replace'));
        if((recordId != null && recordId != '') && (filter.contains('replace'))) {
            filter = filter.replace('replace', recordId);
            System.debug('filter: '+ filter);
        }
        if(byFocus == true) {
            String query = 'SELECT Id, ' + fieldApiNames +
                            ' FROM '    + objectApiName +
                            ' WHERE ';
                List<String> fieldList = fieldApiName.split(';');
                List<String> conditions = new List<String>();
                for (String field : fieldList) {
                    conditions.add(' ' + field + ' LIKE \'%' + searchTerm + '%\'');
                }
                query += '(' + String.join(conditions, ' OR ') + ')';
                query += filter + ' LIMIT 10';

                List<SObject> recordsList =
                Database.query(query);

                return recordsList;
        } else {
            if(String.isNotBlank(searchTerm)) {
                String query = 'SELECT Id, ' + fieldApiNames +
                                ' FROM '    + objectApiName +
                                ' WHERE ';
                List<String> fieldList = fieldApiName.split(';');
                List<String> conditions = new List<String>();
                for (String field : fieldList) {
                    conditions.add(' ' + field + ' LIKE \'%' + searchTerm + '%\'');
                }
                query += '(' + String.join(conditions, ' OR ') + ')';
                query += filter + ' LIMIT 10';

                List<SObject> recordsList =
                Database.query(query);

                return recordsList;
            }
            else {
                return NULL;
            }
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordContracts(String client, String parentAccountId, String searchTerm, String recordType) {
        List<String> recordTypeList = new List<String>();
        if (recordType == 'ZCCO' || recordType == 'ZCNO') {
            recordTypeList.add('BarterSale');
        }
        recordTypeList.add(recordType);
        List<String> orderIdList = new List<String>();
        System.debug(client);
        String searchLike = '%'+searchTerm+'%';
        if(String.isNotBlank(client)) {
            List<Order> recordsList =[SELECT Id, OrderNumber, ContractOrder__c, ContractOrder__r.Id, RecordType.Name
            FROM Order 
            WHERE (RecordType.DeveloperName IN: recordTypeList)
            AND ContractStartDate__c <= TODAY 
            AND ContractEndDate__c >= TODAY 
            AND (AccountId =: client OR AccountId =: parentAccountId)
            AND (StatusSAP__c = '3' OR StatusSAP__c = '4') 
            AND (OrderNumber LIKE :searchLike OR RecordType.Name LIKE :searchLike)
            ORDER BY OrderNumber ASC];

            for(Order record : recordsList){
                orderIdList.add(record.Id);
            }

            List<String> prodContractList = getRecordValidsContracts(orderIdList);
            List<SObject> recordsListWithProducts =[SELECT Id, OrderNumber, ContractOrder__c, ContractOrder__r.Id, RecordType.Name
            FROM Order 
            WHERE (RecordType.DeveloperName IN: recordTypeList)
            AND Id =: prodContractList
            AND ContractStartDate__c <= TODAY 
            AND ContractEndDate__c >= TODAY 
            AND (AccountId =: client OR AccountId =: parentAccountId)
            AND (StatusSAP__c = '3' OR StatusSAP__c = '4') 
            AND (OrderNumber LIKE :searchLike OR RecordType.Name LIKE :searchLike) 
            ORDER BY OrderNumber ASC];

            return recordsListWithProducts;
        }
        else {
            return NULL;
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<String> getRecordValidsContracts(List<String> ordersIds){
        System.debug(ordersIds);
        Map<Id,Decimal> shipMap = new Map <Id,Decimal>();
        Map<Id,Decimal> shipContractMap = new Map <Id,Decimal>();
        Map<Id,Map<Id, Decimal>> balance = new Map<Id,Map<Id, Decimal>>();
        List<Id> contractsList = new List<Id>();
        for(ShippingDivision__c sd : [SELECT Id, OrderItem__c, Quantity__c, RefuseReason__c, OrderItem__r.OrderId, OrderItem__r.Product2Id 
                                        FROM ShippingDivision__c 
                                        WHERE (OrderItem__r.Order.ContractOrder__c IN: ordersIds OR OrderItem__r.OrderId IN :ordersIds)
                                        AND OrderItem__r.Order.StatusSF__c NOT IN ('Em digitação', 'Retorna RTV', 'Cancelado')
                                        AND OrderItem__r.Order.StatusSAP__C NOT IN ('X')]){
            populateMapShip(sd.OrderItem__r.Product2Id, (ordersIds.contains(sd.OrderItem__r.OrderId) ? shipContractMap : shipMap), sd);
            if(balance.containsKey(sd.OrderItem__r.OrderId)){
                balance.get(sd.OrderItem__r.OrderId).put(sd.OrderItem__r.Product2Id, 0);
            }else{
                balance.put(sd.OrderItem__r.OrderId, new Map<Id, Decimal>{sd.OrderItem__r.Product2Id => 0});
            }
        }
        System.debug('balance: ' + balance);
        for(Id prodMapId : balance.keySet()){
            for(Id prodId : balance.get(prodMapId).keySet()){
                Decimal qtdProduct = (shipMap.containsKey(prodId) ? shipMap.get(prodId) : 0);
                Decimal qtdContractProduct = shipContractMap.containsKey(prodId) ? shipContractMap.get(prodId) : 0;
                System.debug('(qtdContractProduct - qtdProduct): ' + (qtdContractProduct - qtdProduct));
                if((qtdContractProduct - qtdProduct) > 0 && qtdContractProduct != null && qtdProduct != null){
                    if(!contractsList.contains(prodMapId)){
                        System.debug('novo na lista');
                        contractsList.add(prodMapId);
                    }
                }
                System.debug('contractsList: ' + contractsList);
            }    
        }
        return contractsList;
    }

    @AuraEnabled(cacheable=true)
    public static Map<Id, Decimal> getRecordContractsProducts(List<String> ordersIds){
        System.debug(ordersIds);
        Map<Id,Decimal> shipMap = new Map <Id,Decimal>();
        Map<Id,Decimal> shipContractMap = new Map <Id,Decimal>();
        Map<Id, Decimal> balance = new Map<Id, Decimal>();
        for(ShippingDivision__c sd : [SELECT Id, OrderItem__c, Quantity__c, RefuseReason__c, OrderItem__r.OrderId, OrderItem__r.Product2Id 
                                        FROM ShippingDivision__c 
                                        WHERE (OrderItem__r.Order.ContractOrder__c IN: ordersIds OR OrderItem__r.OrderId IN :ordersIds)
                                        AND OrderItem__r.Order.StatusSF__c NOT IN ('Em digitação', 'Retorna RTV', 'Cancelado')
                                        AND OrderItem__r.Order.StatusSAP__C NOT IN ('X')]){
            populateMapShip(sd.OrderItem__r.Product2Id, (ordersIds.contains(sd.OrderItem__r.OrderId) ? shipContractMap : shipMap), sd);
            balance.put(sd.OrderItem__r.Product2Id, 0);

            System.debug(shipContractMap);
            System.debug(shipMap);
        }
        for(Id prodId : balance.keySet()){
            System.debug(shipContractMap);
            System.debug(prodId);
            Decimal qtdProduct = (shipMap.containsKey(prodId) ? shipMap.get(prodId) : 0);
            Decimal qtdContractProduct = shipContractMap.containsKey(prodId) ? shipContractMap.get(prodId) : 0;
            System.debug(qtdProduct);
            System.debug(qtdContractProduct);
            System.debug(balance);
            if((qtdContractProduct - qtdProduct) > 0) {
                balance.put(prodId, qtdContractProduct - qtdProduct);
            }
        }
        return balance;
    }
    public static void populateMapShip(Id key, Map<Id, Decimal> shipMap, ShippingDivision__c sd){
        if(!shipMap.containsKey(key))
            shipMap.put(key, 0);
        shipMap.put(key, shipMap.get(key) + getQuantityShip(sd));
    }
    public static Decimal getQuantityShip(ShippingDivision__c sd){
        System.debug(sd);
        return sd.Quantity__c * (sd.RefuseReason__c == null ? 1 : -1);
    }

    /*@AuraEnabled(cacheable=true)
    public static Map<String, Decimal> getRecordContractsProducts(List<String> ordersIds) {
        List<SObject> recordsList;
        List<String> productsIds = new List<String>();
        System.debug('ordersIds: ' + ordersIds);
        Map<String, Decimal> productMap = new Map<String, Decimal>();
        List<OrderItem> recordsProductsList = [
            SELECT Id, Quantity, Product2Id, Product2.Id FROM OrderItem WHERE OrderId =: ordersIds];
        System.debug('recordsProductsList: ' + recordsProductsList);
        if(recordsProductsList != null){
            for (OrderItem orderItens : recordsProductsList) {
                System.debug('orderItem: ' + orderItens.Id);
                productsIds.add(orderItens.Id);
                productMap.put(orderItens.Id,orderItens.Quantity);
            }
        }
        System.debug('productsIds: ' + productsIds);
        Map<String, Decimal> orderItemMap = new Map<String, Decimal>();
        if(productsIds != null){
            List<ShippingDivision__c> shippingDivisionList = [
                SELECT Id, Quantity__c, OrderItem__c, RefuseReason__c FROM ShippingDivision__c WHERE OrderItem__c =: productsIds
            ];
        
            System.debug('shippingDivisionList: ' + shippingDivisionList);
            if (shippingDivisionList != null) {
                for (ShippingDivision__c shippingList : shippingDivisionList) {
                    if (shippingList.RefuseReason__c == null) {
                        if (orderItemMap.containsKey(shippingList.OrderItem__c)) {
                            Decimal quantity = orderItemMap.get(shippingList.OrderItem__c);
                            orderItemMap.put(shippingList.OrderItem__c,(shippingList.Quantity__c + quantity));
                        }
                        else {
                            orderItemMap.put(shippingList.OrderItem__c, shippingList.Quantity__c);
                        }
                    }
                }
                System.debug('orderItemMap: ' + orderItemMap);
                Map<String, Decimal> productsrecords = new Map<String, Decimal>();
                for (OrderItem orderItem : recordsProductsList) {
                    Decimal orderItemShippingQuantity =  orderItemMap.get(orderItem.Id);
                    System.debug('entrou: ' + orderItemShippingQuantity);
                    System.debug('orderItem.Quantity: ' + orderItem.Quantity);
                    if((orderItem.Quantity - orderItemShippingQuantity) > 0 ){
                        System.debug('chegou: ');
                        productsrecords.put(orderItem.Product2.Id,(orderItem.Quantity - orderItemShippingQuantity));
                    }
                }
                System.debug('productsrecords: ' + productsrecords);
                if (productsrecords.isEmpty()) {
                    System.debug('productsrecords2: ' + productsrecords);
                    return null;
                }
                return productsrecords;
            }else{
                return productMap;
            }
        }else{
            return null;
        }
    }*/
    @AuraEnabled(cacheable=true)
    public static Decimal getProductCost(String productId){
        List<ListPrice__c> curPrices =[SELECT Id, Cost__c, Product2Id__c
            FROM ListPrice__c
            WHERE IsActive__c =true
                AND Product2Id__c =:productId
            LIMIT: 1];  
        if (curPrices.isEmpty()){
            return null;
        }
        return curPrices[0].Cost__c;
    }

    @AuraEnabled(cacheable=true)
    public static OrderItem getContractInfo(String orderId, String productId) {

        OrderItem recordsList = [SELECT  Id, Cost__c, Culture__c,Culture__r.Name,ListPrice__c, ContractProductCredit__c, LastChangedPriceList__c, ListPrice__r.Name, ListPrice__r.UnitPrice__c, UnitPrice, Quantity, TotalPrice, DiscountAmount__c, DiscountPercent__c, UnitMeasure__c, AdditionPercent__c, PriceListEffectiveDate__c, AdditionAmount__c
        FROM OrderItem WHERE OrderId =: orderId AND Product2Id =: productId LIMIT 1];
        return recordsList;
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordTypePrincipleName(String filter) {

        List<SObject> recordsList = [SELECT  Id, Name, RemoveFreightValue__c, ActivePrinciple__c, Multiplicity__c, QuantityUnitOfMeasure, ProductCode, GrossWeightUnity__c,Family__c, Family__r.Id, Family__r.Name, GrossWeight__c, ActivitySector__c 
        FROM Product2 WHERE ActivePrinciple__c =: filter AND IsActive = True];
        return recordsList;
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordTypePrincipleNameWithContract(String filter, List<String> contract) {

        List<SObject> recordsList = [SELECT  Id, Name, RemoveFreightValue__c, ActivePrinciple__c, Multiplicity__c, QuantityUnitOfMeasure, ProductCode, GrossWeightUnity__c,Family__c, Family__r.Id, Family__r.Name, GrossWeight__c, ActivitySector__c 
        FROM Product2 WHERE ActivePrinciple__c =: filter AND IsActive = True AND Id =: contract];
        return recordsList;
    }
    @AuraEnabled(cacheable=true)
    public static List<Product2> getRecordPrincipleName(String familyName, String searchValue) {
        List<String> productStringList = new List<String>();
        List<Product2> productList = new List<Product2>();
        List<Product2> recordsList = new List<Product2>();
        if (searchValue == null) {
            recordsList = [SELECT  Id, Name, RemoveFreightValue__c, ActivePrinciple__c, Multiplicity__c, QuantityUnitOfMeasure, ProductCode, GrossWeightUnity__c,Family__c, Family__r.Id, Family__r.Name, GrossWeight__c, ActivitySector__c 
            FROM Product2 WHERE ActivePrinciple__c != null AND Family__r.Name =: familyName AND IsActive = True LIMIT 10];
        }else{
            recordsList = [SELECT  Id, Name, RemoveFreightValue__c, ActivePrinciple__c, Multiplicity__c, QuantityUnitOfMeasure, ProductCode, GrossWeightUnity__c,Family__c, Family__r.Id, Family__r.Name, GrossWeight__c, ActivitySector__c 
            FROM Product2 WHERE ActivePrinciple__c != null AND Family__r.Name =: familyName AND IsActive = True AND ActivePrinciple__c LIKE: searchValue LIMIT 10];
        }
        for(Product2 record : recordsList){
            String recordActivePrinciple = record.ActivePrinciple__c;
            if(!productStringList.contains(record.ActivePrinciple__c)){
                productList.add(record); 
                productStringList.add(record.ActivePrinciple__c); 
            }
        }
        return productList;
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordPrincipleAndFamilyName(String principle, String family) {

        List<SObject> recordsList = [SELECT  Id, Name, RemoveFreightValue__c, ActivePrinciple__c, Multiplicity__c, QuantityUnitOfMeasure, ProductCode, GrossWeightUnity__c,Family__c, Family__r.Id, Family__r.Name, GrossWeight__c, ActivitySector__c 
        FROM Product2 WHERE ActivePrinciple__c =: principle AND Family__r.Name =: family AND IsActive = True];
        
        return recordsList;
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordPrincipleAndFamilyNameWithContract(String principle, String family, List<String> contract) {

        List<SObject> recordsList = [SELECT  Id, Name, RemoveFreightValue__c, ActivePrinciple__c, Multiplicity__c, QuantityUnitOfMeasure, ProductCode, GrossWeightUnity__c,Family__c, Family__r.Id, Family__r.Name, GrossWeight__c, ActivitySector__c 
        FROM Product2 WHERE ActivePrinciple__c =: principle AND Family__r.Name =: family AND IsActive = True AND Id =: contract];
        
        return recordsList;
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordTypeIds(String objectApiName, String fieldApiName, String filter, String filterSales) {
        System.debug(objectApiName);

        if(String.isNotBlank(objectApiName)) {

            User currentUser = [SELECT Id, AvaliableNegotiations__c FROM User WHERE Id =: UserInfo.getUserId()];
            String avaliableNegotiations = currentUser.AvaliableNegotiations__c;

            String avaliableNegotiationFilter = '';
            if(avaliableNegotiations == null){
                avaliableNegotiationFilter = ' AND DeveloperName = null';
            }else if (!avaliableNegotiations.contains('All')) {
                
                List<String> availableNegotiationList = avaliableNegotiations.split(';');

                List<String> escapedParameters = new List<String>();
                for(String parameter : availableNegotiationList) {
                    escapedParameters.add('\'' + parameter + '\'');
                }
                avaliableNegotiationFilter = ' AND DeveloperName IN (' + String.join(escapedParameters, ',') + ') ';
            }
            
            if(filterSales == null){
                avaliableNegotiationFilter += ' AND DeveloperName = null ';
            }else{
                
                List<String> availableNegotiationList = (filterSales == 'Sales' ? OrderTypes__c.getAll().get('Tipos de Pedidos').SalesOrders__c.split(';') : OrderTypes__c.getAll().get('Tipos de Pedidos').SalesContracts__c.split(';'));

                List<String> escapedParameters = new List<String>();
                for(String parameter : availableNegotiationList) {
                    escapedParameters.add('\'' + parameter + '\'');
                }
                avaliableNegotiationFilter += ' AND DeveloperName IN ( ' + String.join(escapedParameters, ',') + ' ) ';
            }

            List<SObject> recordsList =
            Database.query(
                'SELECT Id, ' + fieldApiName  +
                ' FROM '      + objectApiName +
                ' WHERE '     + filter +
                avaliableNegotiationFilter + 
                ' ORDER BY Name ASC'
            );

            return recordsList;
        }
        else {
            return NULL;
        }
    }
@AuraEnabled(cacheable=true)
    public static List<SObject> getRecordPrincipleAgregate(String objectApiName, String fieldApiName, String filter, String searchValue) {
        System.debug(objectApiName);
        if(String.isNotBlank(objectApiName)) {
            if(searchValue != null){
                List<SObject> recordsList =
                Database.query(
                    'SELECT ' + fieldApiName  +
                    ' FROM '      + objectApiName +
                    ' WHERE ActivePrinciple__c ' + ' LIKE \'%' + searchValue + '%\'' + ' AND ' + filter 
                ); 
                System.debug('recordsList: ' + recordsList);
                return recordsList;
            }else{
                List<SObject> recordsList =
                Database.query(
                    'SELECT ' + fieldApiName  +
                    ' FROM '      + objectApiName +
                    ' WHERE '  + filter
                );
                return recordsList;
            }
        }
        else {
            return NULL;
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordSalesTeam(String objectApiName, String fieldApiName, String fieldApiNames, String filter, String searchTerm, String recordId, List<String> salesTeamList, Boolean byFocus) {

        if(byFocus == true) {
            if(!salesTeamList.isEmpty()) {
                System.debug('recordId: ' + salesTeamList);
                
                filter = filter.contains('replace') ? filter.replace('replace', returnListSalesTeam(salesTeamList)) : '';
                System.debug('filter: ' + filter);
                List<String> fieldList = fieldApiName.split(';');
                String query = 'SELECT Id, ' + String.join(fieldList, ', ') + fieldApiNames +
                            ' FROM '    + objectApiName +
                            ' WHERE ';
                List<String> conditions = new List<String>();
                for (String field : fieldList) {
                    conditions.add(' ' + field + ' LIKE \'%' + searchTerm + '%\'');
                }
                query += '(' + String.join(conditions, ' OR ') + ')';
                query += filter + ' LIMIT 10';
            
                List<SObject> recordsList =
                Database.query(query);
                return recordsList;
            }
            else {
                return NULL;
            }
        } else {
            if(!salesTeamList.isEmpty() && String.isNotBlank(searchTerm)) {
                System.debug('recordId: ' + salesTeamList);
                
                filter = filter.contains('replace') ? filter.replace('replace', returnListSalesTeam(salesTeamList)) : '';
                System.debug('filter: ' + filter);                
                List<String> fieldList = fieldApiName.split(';');
                String query = 'SELECT Id, ' + String.join(fieldList, ', ')  + fieldApiNames +
                                ' FROM '    + objectApiName +
                                ' WHERE ';
                List<String> conditions = new List<String>();
                for (String field : fieldList) {
                    conditions.add(' ' + field + ' LIKE \'%' + searchTerm + '%\'');
                }
                query += '(' + String.join(conditions, ' OR ') + ')';
                query += filter + ' LIMIT 10';

                List<SObject> recordsList =
                Database.query(query);
            return recordsList;
            }
            else {
                return NULL;
            }
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordRtvs(String objectApiName, String fieldSearchNames, String fieldApiName, String filter, String searchTerm, String recordId, List<String> idsRtvs, Boolean byFocus) {
        System.debug('idsRtvs: ' + idsRtvs);
        System.debug('recordId: ' + recordId);
        if(byFocus == true) { 
            if(!idsRtvs.isEmpty() && String.isNotBlank(recordId)) {
                filter = filter.contains('replace') ? filter.replace('replace', returnListSalesTeam(idsRtvs)) : '';
                filter = filter.contains('recordId') ? filter.replace('recordId', recordId) : '';
                System.debug('filter: ' + filter);
                List<SObject> recordsList =
                Database.query(
                    'SELECT Id, ' + fieldSearchNames  + 
                    ' FROM '      + objectApiName +
                    ' WHERE '     + fieldApiName  + ' LIKE \'%' + searchTerm + '%\'' 
                                  + filter        + ' LIMIT 10'
                );
            return recordsList;
            }
            else {
                return NULL;
            }
        }
        else {
            if(!idsRtvs.isEmpty() && String.isNotBlank(searchTerm) && String.isNotBlank(recordId)) {
                filter = filter.contains('replace') ? filter.replace('replace', returnListSalesTeam(idsRtvs)) : '';
                filter = filter.contains('recordId') ? filter.replace('recordId', recordId) : '';
                System.debug('filter: ' + filter);
                List<SObject> recordsList =
                Database.query(
                    'SELECT Id, ' + fieldSearchNames  + 
                    ' FROM '      + objectApiName +
                    ' WHERE '     + fieldApiName  + ' LIKE \'%' + searchTerm + '%\'' 
                                  + filter        + ' LIMIT 10'
                );
            return recordsList;
            }
            else {
                return NULL;
            }
        }
    }

    public static String returnListSalesTeam(List<String> listSalesTeam) {
        String stringRight = '';
        System.debug('listSalesTeam: ' + listSalesTeam);
        for(String s : listSalesTeam) {
            stringRight += '\'' + s + '\',';
        }

        stringRight = stringRight.removeEnd(',');

        return stringRight;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordsProduct(String objectApiName, String fieldApiName, String fieldApiNames, String filter, String searchTerm, String recordId, String familyId, List<String> idsProducts, String activitySector, Boolean byFocus) {
        System.debug(objectApiName);
        System.debug(fieldApiName);
        System.debug(filter);
        System.debug(searchTerm);
        System.debug(recordId);
        System.debug(fieldApiNames);
        System.debug(familyId);
        System.debug('idsProducts: ' + idsProducts);
        System.debug('activitySector: ' + activitySector);

        List<String> recordActivityChannelList = new List<String>();
        
        filter = activitySector != null && filter.contains('replaceActivitySector') ? filter.replace('replaceActivitySector', activitySector) : filter.replace('ActivitySector__c == \'replaceActivitySector\' OR ', '');
        filter = familyId != null && filter.contains('replaceFamily') ? filter.replace('replaceFamily', familyId) : filter.replace('AND Family__c = \'replaceFamily\'', '');
        filter = idsProducts != null && filter.contains('replaceId') ? filter.replace('replaceId', returnListSalesTeam(idsProducts)) : '';
        System.debug('filter: ' + filter);

        if(byFocus == true) { 
            if(!idsProducts.isEmpty()) {
                    List<SObject> recordsList =
                    Database.query(
                        'SELECT Id, ' + fieldApiName  + fieldApiNames +
                        ' FROM '      + objectApiName +
                        ' WHERE '     + fieldApiName  + ' LIKE \'%' + searchTerm + '%\'' 
                                      + filter        + ' LIMIT 50'
                    );
                    return recordsList;
                } else  {
                    return null;
                }
        } else {
            if(String.isNotBlank(searchTerm) && !idsProducts.isEmpty()) {

                if(searchTerm != '') {
                    List<SObject> recordsList =
                    Database.query(
                        'SELECT Id, ' + fieldApiName  + fieldApiNames +
                        ' FROM '      + objectApiName +
                        ' WHERE '     + fieldApiName  + ' LIKE \'%' + searchTerm + '%\'' 
                                      + filter        + ' LIMIT 50'
                    );
                    return recordsList;
                } else  {
                    return null;
                }
            } else {
                return null;
            }
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordsProductWithContract(String objectApiName, String fieldApiName, String fieldApiNames, String filter, String searchTerm, String recordId, String familyId, List<String> idsProducts, String activitySector, Boolean byFocus, List<String> contract) {
        System.debug('Contract:' + contract);
        System.debug(objectApiName);
        System.debug(fieldApiName);
        System.debug(filter);
        System.debug(searchTerm);
        System.debug(recordId);
        System.debug(fieldApiNames);
        System.debug(familyId);
        System.debug('idsProducts: ' + idsProducts);
        System.debug('activitySector: ' + activitySector);

        List<String> recordActivityChannelList = new List<String>();
        List<String> newProductsIds = new List<String>();
        if(idsProducts != null){
            for(String product : idsProducts){
                if(contract.contains(product)){
                    newProductsIds.add(product);
                }
            }
        }
        filter = activitySector != null && filter.contains('replaceActivitySector') ? filter.replace('replaceActivitySector', activitySector) : filter.replace('ActivitySector__c == \'replaceActivitySector\' OR ', '');
        filter = familyId != null && filter.contains('replaceFamily') ? filter.replace('replaceFamily', familyId) : filter.replace('AND Family__c = \'replaceFamily\'', '');
        filter = newProductsIds != null && filter.contains('replaceId') ? filter.replace('replaceId', returnListSalesTeam(newProductsIds)) : '';
        System.debug('filter: ' + filter);
        if(byFocus == true) { 
            if(!newProductsIds.isEmpty()) {
                    List<SObject> recordsList =
                    Database.query(
                        'SELECT Id, ' + fieldApiName  + fieldApiNames +
                        ' FROM '      + objectApiName +
                        ' WHERE '  + fieldApiName  + ' LIKE \'%' + searchTerm + '%\'' 
                                      + filter        + ' LIMIT 10'
                    );
                    return recordsList; 
                } else  {
                    return null;
                }
        } else {
            if(String.isNotBlank(searchTerm) && !newProductsIds.isEmpty()) {

                if(searchTerm != '') {
                    List<SObject> recordsList =
                    Database.query(
                        'SELECT Id, ' + fieldApiName  + fieldApiNames +
                        ' FROM '      + objectApiName +
                        ' WHERE '  + fieldApiName  + ' LIKE \'%' + searchTerm + '%\'' 
                                      + filter        + ' LIMIT 10'
                    );
                    return recordsList; 
                } else  {
                    return null;
                }
            } else {
                return null;
            }
        }
    }
    public static String getStringToSend(String recordString) {
        String s = recordString;

        List<String> sList = new List<String>();
        String sList2 = '';
        sList = s.split(';');
        
        for(String str : sList) {
            sList2 += '\'' + str + '\',';
        }

        sList2 = sList2.removeEnd(',');

        return sList2;
    }
}