force-app/main/default/objects/Crop__c/Crop__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Safra provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Safra</label>
    <nameField>
        <label>Nome de Safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crop__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Código externo, chave primária utilizada pelo SAP para identificar o registro.</description>
    <externalId>true</externalId>
    <inlineHelpText>Código externo, chave primária utilizada pelo SAP para identificar o registro.</inlineHelpText>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CropDAO.cls
public with sharing class CropDAO {
    
    public static List<Crop__c> getCropByExternalId(List<String> externalIds, Set<String> cropUsedFields) {

        String query = new Q(Crop__c.SObjectType)
            .selectFields(cropUsedFields)
            .add(Q.condition('ExternalId__c').isIn(externalIds))
            .build();
            
        return Database.query(query);
    }

    public static List<Crop__c> getCropById(List<String> ids, Set<String> cropUsedFields) {

        String query = new Q(Crop__c.SObjectType)
            .selectFields(cropUsedFields)
            .add(Q.condition('Id').isIn(ids))
            .build();
            
        return Database.query(query);
    }

}