force-app/main/default/objects/Crop__c/Crop__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Safra provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Safra</label>
    <nameField>
        <label>Nome de Safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Culture__c/Culture__c.object-meta.xml
<CustomObject>
    
    <label>Cultura</label>
    <nameField>
        <label>Nome da Cultura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DelimitedLand__c/DelimitedLand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os talhões, talhão é um terreno delimitado.</description>
    
    <label>Talhão</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talhões</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DelimitedLand__c/fields/AreaCultivated__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivated__c</fullName>
    <label>Área de Plantio</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/DelimitedLandCultures__c.object-meta.xml
<CustomObject>
    
    <label>Cultura do Talhão</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Culturas dos Talhões</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DelimitedLandCultures__c/fields/AreaCultivated__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivated__c</fullName>
    <label>Área Cultivada</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Culturas dos Talhões</relationshipLabel>
    <relationshipName>Culturas_dos_Talhoes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/Culture__c.field-meta.xml
<CustomField>
    <fullName>Culture__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cultura</label>
    <referenceTo>Culture__c</referenceTo>
    <relationshipLabel>Culturas dos Talhões</relationshipLabel>
    <relationshipName>Culturas_dos_Talhoes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Data de Plantio</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/DelimitedLand__c.field-meta.xml
<CustomField>
    <fullName>DelimitedLand__c</fullName>
    <label>Talhão</label>
    <referenceTo>DelimitedLand__c</referenceTo>
    <relationshipLabel>Culturas dos Talhões</relationshipLabel>
    <relationshipName>Culturas_dos_Talhoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/TechnologicalLevel__c.field-meta.xml
<CustomField>
    <fullName>TechnologicalLevel__c</fullName>
    <label>Nível Tecnológico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Média</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Baixa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DelimitedLandCultures__c/fields/WarehouseCapability__c.field-meta.xml
<CustomField>
    <fullName>WarehouseCapability__c</fullName>
    <label>Capacidade do armazém</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateDelimitedLandCulturesController.cls
@RestResource(urlMapping='/ForcaAgroApp/1_0/sendDelimitedLandCulturesData/*')
global with sharing class CreateDelimitedLandCulturesController {

    @HttpPost
    global static DelimitedLandCulturesResponse createDelimitedLandCulturesApp(String delimitedLandCulturesReq){
        DelimitedLandCulturesResponse delimitedLandCulturesResponse = null;
        Savepoint sp = null;

        DelimitedLandCulturesRequest delimitedLandCulturesRequest = (DelimitedLandCulturesRequest)JSON.deserialize(delimitedLandCulturesReq, DelimitedLandCulturesRequest.class);
        try{
            sp = Database.setSavepoint();

            DelimitedLandCultures__c delimitedLandCultures = serializeDelimitedLandCultures(delimitedLandCulturesRequest);

            if (delimitedLandCulturesRequest.deleted) {
                List<DelimitedLandCultures__c> delimitedLandCulturesList = [
                    SELECT Id FROM DelimitedLandCultures__c WHERE Id = :delimitedLandCultures.Id
                ];
                if (delimitedLandCulturesList.size() > 0) {
                    Database.DeleteResult delResult = Database.delete(delimitedLandCultures, false);

                    if(delResult.isSuccess()){
                        return new DelimitedLandCulturesResponse(delimitedLandCulturesRequest, delResult.getId());
                    } else {
                        return new DelimitedLandCulturesResponse(delResult.getErrors()[0].getMessage(), delimitedLandCulturesRequest);
                    }
                } else {
                    return new DelimitedLandCulturesResponse(delimitedLandCulturesRequest, delimitedLandCultures.Id);
                }
            } else {
                Boolean updateContext = (delimitedLandCultures.Id != null);

                Database.SaveResult upsResult = updateContext ? Database.update(delimitedLandCultures, false) : Database.insert(delimitedLandCultures, false); 

                if(upsResult.isSuccess()){
                    return new DelimitedLandCulturesResponse(delimitedLandCulturesRequest, upsResult.getId());
                } else {
                    return new DelimitedLandCulturesResponse(upsResult.getErrors()[0].getMessage(), delimitedLandCulturesRequest);
                }
            }

        } catch (Exception e) {
            Database.rollback(sp);
            delimitedLandCulturesResponse = new DelimitedLandCulturesResponse(e, delimitedLandCulturesRequest);
        }

        return delimitedLandCulturesResponse;
    }

    global abstract class DelimitedLandCulturesBaseRequest{
        public String  id                   {get;set;}
        public Integer appCode              {get;set;}
        public String  cropId               {get;set;}
        public String  cultureId            {get;set;}
        public String  plantingDate         {get;set;}
        public String  delimitedLand        {get;set;}
        public Decimal areaCultivated       {get;set;}
        public String  technologicalLevel   {get;set;}
        public Decimal warehouseCapability  {get;set;}
        public Boolean deleted              {get;set;}
    }

    global class DelimitedLandCulturesRequest extends DelimitedLandCulturesBaseRequest{}

    public static DelimitedLandCultures__c serializeDelimitedLandCultures(DelimitedLandCulturesRequest delimitedLandCulturesRequest) {
        DelimitedLandCultures__c delimitedLandCultures = new DelimitedLandCultures__c(
            Id                      = delimitedLandCulturesRequest.id,
            AreaCultivated__c       = delimitedLandCulturesRequest.areaCultivated,
            Crop__c                 = delimitedLandCulturesRequest.cropId,
            Culture__c              = delimitedLandCulturesRequest.cultureId,
            Date__c                 = Date.valueOf(delimitedLandCulturesRequest.plantingDate),
            DelimitedLand__c        = delimitedLandCulturesRequest.delimitedLand,
            WarehouseCapability__c  = delimitedLandCulturesRequest.warehouseCapability
        );
        if (!String.isBlank(delimitedLandCulturesRequest.technologicalLevel)) {
            delimitedLandCultures.TechnologicalLevel__c = delimitedLandCulturesRequest.technologicalLevel;
        }
        return delimitedLandCultures;
    }

    global class DelimitedLandCulturesResponse extends DelimitedLandCulturesBaseRequest{
        @AuraEnabled public Boolean hasError {get;set;}
        @AuraEnabled public String errorMsg  {get;set;}

        public DelimitedLandCulturesResponse(Exception ex, DelimitedLandCulturesRequest delimitedLandCulturesRequest){
            this.hasError = true;
            this.errorMsg = ex.getMessage() + '\n Erro :' + ex.getStackTraceString();
            this.appCode  = delimitedLandCulturesRequest.appCode;
            this.deleted  = delimitedLandCulturesRequest.deleted;
        } 
        public DelimitedLandCulturesResponse(String error, DelimitedLandCulturesRequest delimitedLandCulturesRequest){
            this.hasError = true;
            this.errorMsg = error;
            this.appCode  = delimitedLandCulturesRequest.appCode;
            this.deleted  = delimitedLandCulturesRequest.deleted;
        }
        public DelimitedLandCulturesResponse(DelimitedLandCulturesRequest delimitedLandCulturesRequest, String accountId){
            this.hasError = false;
            this.errorMsg = null;
            this.id       = accountId;
            this.appCode  = delimitedLandCulturesRequest.appCode;
            this.deleted  = delimitedLandCulturesRequest.deleted;
        }  
    }
}