force-app/main/default/objects/Crop__c/Crop__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Safra provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Safra</label>
    <nameField>
        <label>Nome de Safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crop__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Data de validada final da safra.</description>
    <inlineHelpText>Data de validada final da safra.</inlineHelpText>
    <label>Data final</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Crop__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Código externo, chave primária utilizada pelo SAP para identificar o registro.</description>
    <externalId>true</externalId>
    <inlineHelpText>Código externo, chave primária utilizada pelo SAP para identificar o registro.</inlineHelpText>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Centros de Distribuição provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome de Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Product2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/ProductManagement__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para controlar os produtos que podem ser vendidos, stop de vendas e que cairão para aprovação</description>
    
    <label>Controle de produto</label>
    <nameField>
        <displayFormat>PMG-{0000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controle de produtos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductManagement__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Controle de produtos</relationshipLabel>
    <relationshipName>Controle_de_produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Centro de distribuição onde esta localizado o estoque.</description>
    <inlineHelpText>Centro de distribuição onde esta localizado o estoque.</inlineHelpText>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Saldo de estoque</relationshipLabel>
    <relationshipName>Controle_de_produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data de Vigência Final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/InitialDate__c.field-meta.xml
<CustomField>
    <fullName>InitialDate__c</fullName>
    <label>Data Vigência Inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Controle de produtos</relationshipLabel>
    <relationshipName>Controle_de_produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Controle de produtos</relationshipLabel>
    <relationshipName>Controle_de_produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductManagement__c/recordTypes/ExclusionList.recordType-meta.xml
<RecordType>
    <fullName>ExclusionList</fullName>
    <active>true</active>
    <description>Tipo de registro utilizado para listas de exclusão</description>
    <label>Lista de exclusão</label>
</RecordType>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    
    <label>Organização de Vendas</label>
    <nameField>
        <label>Nome de Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizações de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrg__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesTeam__c/SalesTeam__c.object-meta.xml
<CustomObject>
    
    <label>Equipe de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes de Vendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Equipes de Vendas</relationshipLabel>
    <relationshipName>SalesTeams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Equipes de Vendas</relationshipLabel>
    <relationshipName>SalesTeams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductManagementHelper.cls
public with sharing class ProductManagementHelper {

    private static Boolean isEnabled;
    private static id exclusionListId;
    static{
        isEnabled = true;
        exclusionListId = Schema.SObjectType.ProductManagement__c.getRecordTypeInfosByDeveloperName().get('ExclusionList').getRecordTypeId();
    }

    public static Boolean isTriggerEnabled(){
        return isEnabled;
    }
    
    public static Boolean disableTrigger(){
        return isEnabled = false;
    }

    public static Boolean enableTrigger(){
        return isEnabled = true;
    }

    public static void setSalesOrgname(List<ProductManagement__c> productManagementList) {
        Map<Id, SalesTeam__c> salesMap = new Map<Id, SalesTeam__c>([SELECT Id, SalesOrg__r.ExternalId__c FROM SalesTeam__c WHERE Id IN :Collection.of(productManagementList).pluckIds(ProductManagement__c.SalesTeam__c)]);
        
        Map<Id, List<String>> distMap = new Map<Id, List<String>>();
        for(SalesTeam__c slTeam : [SELECT Id, SalesOrg__r.ExternalId__c, DistributionCenter__c FROM SalesTeam__c WHERE DistributionCenter__c IN :Collection.of(productManagementList).pluckIds(ProductManagement__c.DistributionCenter__c)]){
            if(!distMap.containsKey(slTeam.DistributionCenter__c))
                distMap.put(slTeam.DistributionCenter__c, new List<String>());
            distMap.get(slTeam.DistributionCenter__c).add(slTeam.SalesOrg__r.ExternalId__c);
        }
        
        for(ProductManagement__c productManagement : productManagementList){
            List<String> salesOrgList = new List<String>();

            if(productManagement.SalesTeam__c != null && salesMap.containsKey(productManagement.SalesTeam__c))
                salesOrgList.add(salesMap.get(productManagement.SalesTeam__c).SalesOrg__r.ExternalId__c);
                
            if(productManagement.DistributionCenter__c != null && distMap.containsKey(productManagement.DistributionCenter__c))
                salesOrgList.addAll(distMap.get(productManagement.DistributionCenter__c));

            productManagement.SalesOrgName__c = String.join(salesOrgList, ';');
        }
    }
    public static void setExternalId(List<ProductManagement__c> productManagementList) {
        List<String> salesTeamIds = new List<String>();
        List<String> distributionCenterIds = new List<String>();
        List<String> productIds = new List<String>();
        List<String> cropIds = new List<String>();

        for (ProductManagement__c productManagement : productManagementList) {
            if (productManagement.RecordTypeId == exclusionListId) {
                salesTeamIds.add(productManagement.SalesTeam__c);
                cropIds.add(productManagement.Crop__c);
            }
            cropIds.add(productManagement.Crop__c);
            distributionCenterIds.add(productManagement.DistributionCenter__c);
            productIds.add(productManagement.Product2__c);
        }

        Map<Id, SalesTeam__c> salesTeamMap = new Map<Id, SalesTeam__c>(
            SalesTeamDAO.getSalesTeamById(salesTeamIds, new Set<String>{'Id', 'ExternalId__c'})
        );
        Map<Id, DistributionCenter__c> distributionCenterMap = new Map<Id, DistributionCenter__c>(
            DistributionCenterDAO.getDistributionCenterBylId(distributionCenterIds, new Set<String>{'Id', 'ExternalId__c'})
        );
        Map<Id, Product2> productMap = new Map<Id, Product2>(
            Product2DAO.getProduct2ById(productIds, new Set<String>{'Id', 'ExternalId__c'})
        );
        Map<Id, Crop__c> cropMap = new Map<Id, Crop__c>(
            CropDAO.getCropById(cropIds, new Set<String>{'Id', 'ExternalId__c'})
        );

        for (ProductManagement__c productManagement : productManagementList) {
            if (productManagement.RecordTypeId == exclusionListId) {
                String initialDate = productManagement.InitialDate__c != null ? String.valueOf(productManagement.InitialDate__c).replaceAll('-', '') : ''; 
                String endDate     = productManagement.EndDate__c != null ? String.valueOf(productManagement.EndDate__c).replaceAll('-', '') : ''; 
                productManagement.ExternalId__c = productMap.get(productManagement.Product2__c)?.ExternalId__c      + '-' +
                                                  salesTeamMap.get(productManagement.SalesTeam__c)?.ExternalId__c   + '-' +
                                                  cropMap.get(productManagement.Crop__c)?.ExternalId__c;
            } else {
                productManagement.ExternalId__c = productMap.get(productManagement.Product2__c)?.ExternalId__c + '-' +
                                                  distributionCenterMap.get(productManagement.DistributionCenter__c)?.ExternalId__c+ '-' +
                                                  cropMap.get(productManagement.Crop__c)?.ExternalId__c;
            }
        }
    }
}