force-app/main/default/objects/Crop__c/Crop__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os registros de Safra provenientes do SAP, alimentado através de carga de dados.</description>
    
    <label>Safra</label>
    <nameField>
        <label>Nome de Safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crop__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Descrição da safra.</description>
    <inlineHelpText>Descrição da safra.</inlineHelpText>
    <label>Descrição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Crop__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Data de validada final da safra.</description>
    <inlineHelpText>Data de validada final da safra.</inlineHelpText>
    <label>Data final</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Crop__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Código externo, chave primária utilizada pelo SAP para identificar o registro.</description>
    <externalId>true</externalId>
    <inlineHelpText>Código externo, chave primária utilizada pelo SAP para identificar o registro.</inlineHelpText>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ListPrice__c/ListPrice__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena dos dados do catalogo de preço, esse objeto será alimentado através de integração com o SAP, o SAP irá manipular os registros através da API padrão do  salesforce.</description>
    
    <label>Catálogo de preço</label>
    <nameField>
        <displayFormat>CAT-{0000}</displayFormat>
        <label>Nome do Catalogo de preço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Catalogos de preço</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ListPrice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Catalogos de preço</relationshipLabel>
    <relationshipName>ListPrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/CalculatedInterest__c.field-meta.xml
<CustomField>
    <fullName>CalculatedInterest__c</fullName>
    <description>Formula para calcular a porcentagem unitária já considerando a multiplicidade do SAP.</description>
    <formula>IF(OR(0 == 0, 0 == 0), 1, UnitPrice__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula para calcular a porcentagem unitária já considerando a multiplicidade do SAP.</inlineHelpText>
    <label>Juros Calculado</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/CalculatedUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>CalculatedUnitPrice__c</fullName>
    <description>Formula para calcular o valor unitário já considerando a multiplicidade do SAP.</description>
    <formula>IF(OR(UnitPrice__c == 0, PriceMultiplier__c == 0), 1, UnitPrice__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula para calcular o valor unitário já considerando a multiplicidade do SAP.</inlineHelpText>
    <label>Preço Unitário Calculado</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Catalogos de preço</relationshipLabel>
    <relationshipName>ListPrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Campo que armazena o tipo de moeda utilizada no catalogo de preço, referente ao campo KONP - KONWA no SAP.</description>
    <inlineHelpText>Campo que armazena o tipo de moeda utilizada no catalogo de preço, referente ao campo KONP - KONWA no SAP.</inlineHelpText>
    <label>Moeda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/CustomerGroup__c.field-meta.xml
<CustomField>
    <fullName>CustomerGroup__c</fullName>
    <description>Este campo armazena o valor do campo VBKD - KDGRP no SAP.</description>
    <inlineHelpText>Este campo armazena o valor do campo VBKD - KDGRP no SAP.</inlineHelpText>
    <label>Grupo de Clientes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Descrição do catalogo de preço.</description>
    <inlineHelpText>Descrição do catalogo de preço</inlineHelpText>
    <label>Descrição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <description>Data efetiva do catalogo de preços, recebe o valor do campo KONP - VALDT no SAP.</description>
    <inlineHelpText>Data efetiva do catalogo de preços, recebe o valor do campo KONP - VALDT no SAP.</inlineHelpText>
    <label>Data Efetiva</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Data da vigência final do Catalogo de preço, este campo armazena os valores KONH - DATBi no SAP.</description>
    <inlineHelpText>Data da vigência final do Catalogo de preço, este campo armazena os valores KONH - DATBi no SAP.</inlineHelpText>
    <label>Data Vigência Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo que identifica o catalogo de preço no SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Campo que identifica o catalogo de preço no SAP.</inlineHelpText>
    <label>Código SAP</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo que recebe o valor da organização de vendas, referente ao campo VBKD - PLTYP no SAP.</description>
    <inlineHelpText>Campo que recebe o valor da organização de vendas, referente ao campo VBKD - PLTYP no SAP.</inlineHelpText>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Catalogos de preço</relationshipLabel>
    <relationshipName>ListPrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo que armazena a Equipe de vendas, referente ao campo  VBAK - VKGRP no SAP.</description>
    <inlineHelpText>Campo que armazena a Equipe de vendas, referente ao campo  VBAK - VKGRP no SAP.</inlineHelpText>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Catalogos de preço</relationshipLabel>
    <relationshipName>ListPrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ListPrice__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <description>Valor unitário do produto, referente ao campo KONP - KBETR no SAP.</description>
    <inlineHelpText>Valor unitário do produto, referente ao campo KONP - KBETR no SAP.</inlineHelpText>
    <label>Valor</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Safra</label>
    <referenceTo>Crop__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Moeda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CustomerGroup__c.field-meta.xml
<CustomField>
    <fullName>CustomerGroup__c</fullName>
    <label>Grupo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesTeam__c.field-meta.xml
<CustomField>
    <fullName>SalesTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipe de Vendas</label>
    <referenceTo>SalesTeam__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Valor Commodity Líquido</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesCondition__c/SalesCondition__c.object-meta.xml
<CustomObject>
    
    <label>Condição de venda</label>
    <nameField>
        <label>Nome de Condição de venda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de venda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesCondition__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código da condição de venda</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cluster</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Escritórios de Vendas</relationshipLabel>
    <relationshipName>SalesOffices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    
    <label>Organização de Vendas</label>
    <nameField>
        <label>Nome de Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizações de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrg__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesTeam__c/SalesTeam__c.object-meta.xml
<CustomObject>
    
    <label>Equipe de Vendas</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes de Vendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTeam__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Escritório de Vendas</label>
    <referenceTo>SalesOffice__c</referenceTo>
    <relationshipLabel>Equipes de Vendas</relationshipLabel>
    <relationshipName>SalesTeams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesTeam__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organização de Vendas</label>
    <referenceTo>SalesOrg__c</referenceTo>
    <relationshipLabel>Equipes de Vendas</relationshipLabel>
    <relationshipName>SalesTeams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A1</fullName>
    </customValue>
    <customValue>
        <fullName>A2</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>C1</fullName>
    </customValue>
    <customValue>
        <fullName>C2</fullName>
    </customValue>
    <masterLabel>Categoria do Cliente</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InterestListController.cls
public with sharing class InterestListController {
    public class InterestListData{
        public String productFamilyId {get;set;}
        public String productId       {get;set;}
        public String salesTeamId     {get;set;}
        public String salesOfficeId   {get;set;}
        public String currencyType    {get;set;}
        public String cropId          {get;set;}
        public String salesCondition  {get;set;}
        public String listPriceType   {get;set;}
    }
   
    @AuraEnabled(cacheable=true)
    public static ListPrice__c getInterestListData(String priceData) {

        System.debug('priceData: ' + priceData);

        InterestListData interestListData    = new interestListData();

        interestListData = (InterestListData)JSON.deserialize(priceData, InterestListData.class);

        ListPrice__c priceReturnMap = new ListPrice__c();

        try {
            SalesTeam__c salesTeam = SalesTeamDAO.getSalesTeamById(new List<String>{interestListData.salesTeamId}, new Set<String>{'Id', 'ParentId__c', 'SalesOrg__c'})[0];

            priceReturnMap = getAllPriceData(interestListData, salesTeam);

        } catch(Exception ex) {
            priceReturnMap = null;
        }
		System.debug('priceReturnMap: ' + priceReturnMap);

        return priceReturnMap;
    }

    public static ListPrice__c getAllPriceData(InterestListData priceData, SalesTeam__c salest) {
        List<ListPrice__c> lp = new List<ListPrice__c>();
        
        lp = [
            SELECT Id, OwnerId, IsDeleted,
            Name, RecordTypeId, CreatedDate, CreatedById, LastModifiedDate,
            LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate,
            LastReferencedDate, Account__c, CalculatedInterest__c,
            CalculatedUnitPrice__c, Crop__c, Currency__c,
            CustomerGroup__c, Description__c, EffectiveDate__c,
            EndDate__c, ExternalId__c, InitialDate__c, InterestValue__c,
            IsActive__c, PriceMultiplier__c, Priority__c, Product2Id__c,
            ProductFamily__c, SalesCondition__c, SalesOffice__c, SalesOrg__c,
            ActivitySector__c, SalesTeam__c, UnitMeasurement__c, UnitPrice__c, RecordType.DeveloperName
            FROM ListPrice__c 
            WHERE (InitialDate__c <= TODAY AND EndDate__c >= TODAY  
                    AND IsActive__c               = true
                    AND RecordType.DeveloperName  = :priceData.listPriceType
                    AND (SalesOffice__c           = :priceData.salesOfficeId   OR SalesOffice__c     = null)
                    AND (Currency__c              = :priceData.currencyType    OR Currency__c        = null)
                	AND (ProductFamily__c         = :priceData.productFamilyId OR ProductFamily__c   = null)
                    AND (Product2Id__c            = :priceData.productId       OR Product2Id__c      = null)
                	AND (SalesCondition__c        = :priceData.salesCondition  OR SalesCondition__c  = null)
                	AND (Crop__c                  = :priceData.cropId          OR Crop__c            = null)
                	AND (SalesOrg__c              = :salest.SalesOrg__c)) ORDER BY InterestPriority__c DESC NULLS LAST LIMIT 1];

        return lp == null || lp.isEmpty() ? null : lp[0];
    }
}