force-app/main/default/objects/FieldDependency__c/FieldDependency__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Dependência de Campo</label>
</CustomObject>

force-app/main/default/objects/FieldDependency__c/fields/DependencyField__c.field-meta.xml
<CustomField>
    <fullName>DependencyField__c</fullName>
    <label>Campo Dependente</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldDependency__c/fields/DependencyFieldKey__c.field-meta.xml
<CustomField>
    <fullName>DependencyFieldKey__c</fullName>
    <label>Campo Chave</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldDependency__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FieldDependencyDAO.cls
public with sharing class FieldDependencyDAO {
    
    public static FieldDependency__c getFieldDependency(String dependencyFieldKey, String dependencyField, String value, Set<String> fieldDependencyUsedFields) {

        String query = new Q(FieldDependency__c.SObjectType)
            .selectFields(fieldDependencyUsedFields)
            .add(Q.condition('DependencyFieldKey__c').equalsTo(dependencyFieldKey))
            .add(Q.condition('DependencyField__c').equalsTo(dependencyField))
            .add(Q.condition('Value__c').equalsTo(value))
            .addLimit(1)
            .build();
            
        return Database.query(query);
    }


}