force-app/main/default/objects/SalesOrg__c/SalesOrg__c.object-meta.xml
<CustomObject>
    
    <label>Organização de Vendas</label>
    <nameField>
        <label>Nome de Organização de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizações de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrg__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SalesOrgDAO.cls
public with sharing class SalesOrgDAO {
    
    public static List<SalesOrg__c> getSalesOrgById(List<String> ids, Set<String> salesOrgUsedFields) {

        String query = new Q(SalesOrg__c.SObjectType)
            .selectFields(salesOrgUsedFields)
            .add(Q.condition('Id').isIn(ids))
            .build();
            
        return Database.query(query);
    }
    
    public static List<SalesOrg__c> getSalesOrgByExternalId(List<String> externalIds, Set<String> salesOrgUsedFields) {

        String query = new Q(SalesOrg__c.SObjectType)
            .selectFields(salesOrgUsedFields)
            .add(Q.condition('ExternalId__c').isIn(externalIds))
            .build();
            
        return Database.query(query);
    }

}