force-app/main/default/objects/ShippingDivision__c/ShippingDivision__c.object-meta.xml
<CustomObject>
    
    <label>Divisão de Remessa</label>
    <nameField>
        <label>Divisão de Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisões de Remessa</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingDivision__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código Linha</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ShippingDivisionDAO.cls
public with sharing class ShippingDivisionDAO {

    public static List<ShippingDivision__c> getShippingDivisionByExternalId(List<String> externalIds, Set<String> shippingDivisionUsedFields) {

        String query = new Q(ShippingDivision__c.SObjectType)
            .selectFields(shippingDivisionUsedFields)
            .add(Q.condition('ExternalId__c').isIn(externalIds))
            .build();
            
        return Database.query(query);
    }


}