force-app/main/default/objects/DelimitedLand__c/DelimitedLand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os talhões, talhão é um terreno delimitado.</description>
    
    <label>Talhão</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talhões</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DelimitedLand__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Name</field>
            <operation>contains</operation>
            <value>Propriedade</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Talhões</relationshipLabel>
    <relationshipName>Talhoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaCultivated__c.field-meta.xml
<CustomField>
    <fullName>AreaCultivated__c</fullName>
    <label>Área de Plantio</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaNotAllocated__c.field-meta.xml
<CustomField>
    <fullName>AreaNotAllocated__c</fullName>
    <label>Área Não Alocada</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaPasture__c.field-meta.xml
<CustomField>
    <fullName>AreaPasture__c</fullName>
    <label>Área de pastagem</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/AreaPreservation__c.field-meta.xml
<CustomField>
    <fullName>AreaPreservation__c</fullName>
    <label>Área de preservação ambiental</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/ContractDate__c.field-meta.xml
<CustomField>
    <fullName>ContractDate__c</fullName>
    <label>Data de vencimento do contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrição</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/OwnerName__c.field-meta.xml
<CustomField>
    <fullName>OwnerName__c</fullName>
    <label>Nome do Proprietario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Arrendatario?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/TenantArea__c.field-meta.xml
<CustomField>
    <fullName>TenantArea__c</fullName>
    <label>Quantidade Hec Arrendatario</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/TenantCulture__c.field-meta.xml
<CustomField>
    <fullName>TenantCulture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultura de Arrendamento</label>
    <referenceTo>Culture__c</referenceTo>
    <relationshipLabel>Talhões</relationshipLabel>
    <relationshipName>Talhoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/TenantTax__c.field-meta.xml
<CustomField>
    <fullName>TenantTax__c</fullName>
    <label>Valor Taxa de Arrendamento</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/TenantValue__c.field-meta.xml
<CustomField>
    <fullName>TenantValue__c</fullName>
    <label>Valor Arrendamento</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DelimitedLand__c/fields/UnitMeasurement__c.field-meta.xml
<CustomField>
    <fullName>UnitMeasurement__c</fullName>
    <description>Lista de seleção com todas as unidades de medidas</description>
    <label>Unidade de Medida</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hectare</fullName>
            </value>
            <value>
                <fullName>Are</fullName>
            </value>
            <value>
                <fullName>Centiare</fullName>
            </value>
            <value>
                <fullName>Alqueire Mineiro</fullName>
            </value>
            <value>
                <fullName>Alqueire Goiano</fullName>
            </value>
            <value>
                <fullName>Alqueire Paulista</fullName>
            </value>
            <value>
                <fullName>Alqueire do norte</fullName>
            </value>
            <value>
                <fullName>Alqueire do RJ</fullName>
            </value>
            <value>
                <fullName>Alqueire Baiano</fullName>
            </value>
            <value>
                <fullName>Litro</fullName>
            </value>
            <value>
                <fullName>Metro Quadrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateDelimitedLandController.cls
@RestResource(urlMapping='/ForcaAgroApp/1_0/sendDelimitedLandData/*')
global with sharing class CreateDelimitedLandController {

    @HttpPost
    global static DelimitedLandResponse createDelimitedLandApp(String delimitedLandReq){
        DelimitedLandResponse delimitedLandResponse = null;
        Savepoint sp = null;

        DelimitedLandRequest delimitedLandRequest = (DelimitedLandRequest)JSON.deserialize(delimitedLandReq, DelimitedLandRequest.class);
        try{
            sp = Database.setSavepoint();

            DelimitedLand__c delimitedLand = serializeDelimitedLand(delimitedLandRequest);

            if (delimitedLandRequest.deleted) {
                List<DelimitedLand__c> delimitedLandList = [SELECT Id FROM DelimitedLand__c WHERE Id = :delimitedLand.Id];
                if (delimitedLandList.size() > 0) {
                    Database.DeleteResult delResult = Database.delete(delimitedLand, false);

                    if(delResult.isSuccess()){
                        return new DelimitedLandResponse(delimitedLandRequest, delResult.getId());
                    } else {
                        return new DelimitedLandResponse(delResult.getErrors()[0].getMessage(), delimitedLandRequest);
                    }
                } else {
                    return new DelimitedLandResponse(delimitedLandRequest, delimitedLand.Id);
                }
            } else {
                Boolean updateContext = (delimitedLand.Id != null);

                Database.SaveResult upsResult = updateContext ? Database.update(delimitedLand, false) : Database.insert(delimitedLand, false); 

                if(upsResult.isSuccess()){
                    return new DelimitedLandResponse(delimitedLandRequest, upsResult.getId());
                } else {
                    return new DelimitedLandResponse(upsResult.getErrors()[0].getMessage(), delimitedLandRequest);
                }
            }

        } catch (Exception e) {
            Database.rollback(sp);
            delimitedLandResponse = new DelimitedLandResponse(e, delimitedLandRequest);
        }

        return delimitedLandResponse;
    }

    global abstract class DelimitedLandBaseRequest{
        public String  id                {get;set;}
        public Integer appCode           {get;set;}
        public String  name              {get;set;}
        public String  description       {get;set;}
        public String  accountId         {get;set;}
        public String  unitMeasurement   {get;set;}
        public Decimal areaCultivated    {get;set;}
        public Decimal areaNotAllocated  {get;set;}
        public Decimal areaPasture       {get;set;}
        public Decimal areaPreservation  {get;set;}
        public String  ownerName         {get;set;}
        public String  tenantCultureId   {get;set;}
        public Decimal tenantValue       {get;set;}
        public Decimal tenantTax         {get;set;}
        public Boolean tenant            {get;set;}
        public Decimal tenantArea        {get;set;}
        public String  contractDate      {get;set;}
        public Boolean deleted           {get;set;}
    }

    global class DelimitedLandRequest extends DelimitedLandBaseRequest{}

    public static DelimitedLand__c serializeDelimitedLand(DelimitedLandRequest delimitedLandRequest) {
        DelimitedLand__c delimitedLand = new DelimitedLand__c(
            Id                  = delimitedLandRequest.id,
            Name                = delimitedLandRequest.name,
            Description__c      = delimitedLandRequest.description,
            Account__c          = delimitedLandRequest.accountId,
            AreaCultivated__c   = delimitedLandRequest.areaCultivated,
            AreaNotAllocated__c = delimitedLandRequest.areaNotAllocated,
            AreaPasture__c      = delimitedLandRequest.areaPasture,
            AreaPreservation__c = delimitedLandRequest.areaPreservation,
            UnitMeasurement__c  = delimitedLandRequest.unitMeasurement,
            OwnerName__c        = delimitedLandRequest.ownerName,
            TenantValue__c      = delimitedLandRequest.tenantValue,
            TenantTax__c        = delimitedLandRequest.tenantTax,
            Tenant__c           = delimitedLandRequest.tenant,
            TenantArea__c       = delimitedLandRequest.tenantArea
        );
        if (delimitedLandRequest.tenantCultureId != null) {
            delimitedLand.TenantCulture__c = delimitedLandRequest.tenantCultureId;
        }
        if (delimitedLandRequest.contractDate != null) {
            delimitedLand.ContractDate__c = Date.valueOf(delimitedLandRequest.contractDate);
        }
        return delimitedLand;
    }


    global class DelimitedLandResponse extends DelimitedLandBaseRequest{
        @AuraEnabled public Boolean hasError {get;set;}
        @AuraEnabled public String errorMsg  {get;set;}

        public DelimitedLandResponse(Exception ex, DelimitedLandRequest delimitedLandRequest){
            this.hasError = true;
            this.errorMsg = ex.getMessage() + '\n Erro :' + ex.getStackTraceString();
            this.appCode  = delimitedLandRequest.appCode;
            this.deleted  = delimitedLandRequest.deleted;
        } 
        public DelimitedLandResponse(String error, DelimitedLandRequest delimitedLandRequest){
            this.hasError = true;
            this.errorMsg = error;
            this.appCode  = delimitedLandRequest.appCode;
            this.deleted  = delimitedLandRequest.deleted;
        }
        public DelimitedLandResponse(DelimitedLandRequest delimitedLandRequest, String delimitedLandId){
            this.hasError = false;
            this.errorMsg = null;
            this.id       = delimitedLandId;
            this.appCode  = delimitedLandRequest.appCode;
            this.deleted  = delimitedLandRequest.deleted;
        }  
    }
}